### ISSUE TITLE
Documentation for anyFirst is either incorrect or counter-intuitive

### ISSUE THREAD

**Issue by ben-turner** [gajus/slonik#102]
[In the README](https://github.com/gajus/slonik#slonik-query-methods-anyfirst), it says that anyFirst throws a data integrity error if multiple rows are returned. This seems like it should be what maybeOneFirst does.

I think it should read "multiple columns", but can't verify what the actual behavior is right now. I've created https://github.com/gajus/slonik/pull/103 if someone can confirm the behavior.

**Comment by gajus** [comment]
Thank you
