### ISSUE TITLE
use interceptors to provide results rows without a pg connection

### ISSUE THREAD

**Issue by benjamine** [gajus/slonik#104]
I'm trying to mock pg sql queries during automated testing, but would like to still have slonik assertions execute (`.one` etc.).

I found `beforeQueryExecution` can be used to provide result rows, although you still need a pg connection unless you intercept `beforePoolConnection`.
then if you do intercept `beforePoolConnection` you're forced to implement methods like `.one`, `.stream`, etc.

Is there a way to intercept `beforeQueryExecution` (mocking the pg result) but still get the rest of slonik to execute? (without having to reimplement a pool)

**Comment by gajus** [comment]
> without having to reimplement a pool

This would be the way to go. Also, a good package to contribute to the community. Would add it under `@slonik/mock`.

**Comment by gajus** [comment]
With the recent changes, you can either:

1. Instantiate `createMockPool` and use that.
2. Use `createPool` but override connection as needed using `beforePoolConnection`.
