### ISSUE TITLE
enhancement: support passing around connections and transactions 

### ISSUE THREAD

**Issue by alidcastano** [gajus/slonik#108]
it'd be great to ensure safe connections/transactions at the framework level

being able to pass around connection/transaction object is useful for replacing connection with a transaction during testing, so you can automatically rollback all operations after each test

**Comment by gajus** [comment]
Not clear what the issue is asking for.

**Comment by alidcastano** [comment]
to be able to pass these objects around, not just have them as a callback, i.e.
```
const connection = await pool.startConnection()
cosnt trx = await connection.startTransaction()

new ApolloServer({ context: () => ({ db: trx }) })

// then somewhere later 
trx.rollback() // or trx.commit()
connection.release()
```

**Comment by gajus** [comment]
It is explained in the documentation.

https://github.com/gajus/slonik#protecting-against-unsafe-connection-handling

**Comment by alidcastano** [comment]
yes, I read that part of the documentation, which is why I mentioned that rather than handling unsafe connections at the at the client level (via callbacks only), it should be handled at the framework level (i.e. ensuring that at the end of each response a transaction is cleaned up and released.
