### ISSUE TITLE
slonik and notice log from database

### ISSUE THREAD

**Issue by dmpvost** [gajus/slonik#110]
Hi,
I’m trying Slonik and Roarr by the way

I made it for migrate pg-async to slonik for some query, my test work

And now I try to get all log from slonik. I have installed roarr and roarr-cli, 

I try to get NOTICE log from database, and get it on console. It work but it’s too verbose. I use notice a lot in database, and I just want to print a simple line when it’s notice
I’m interested to get more details when it’s an error

Is it possible to read the "log NOTICE" stream in nodeJs? And not with bash?

Currently I have 5 lines for a notice message, output from roarr. 
```
[1] [2019-10-08T15:55:25.916Z] INFO (30) (@slonik): notice message
[1] poolId: 01DPP1A3NNYA7JN6VGFTE4N234
[1] notice:
[1]   level:   notice
[1]   message: hello world
```

My goal is to connect notice message in the NodeJS console, with all others messages
and have this format
```
[1] [2019-10-08T15:55:25.916Z] INFO (30) (@slonik): hello world
```
Any help could be very nice!

**Comment by gajus** [comment]
https://github.com/gajus/slonik/issues/97

**Comment by dmpvost** [comment]
it's not about NOTIFY/LISTEN postgresql feature, but just show log of NOTICE level

in SQL 

"RAISE NOTICE blablabla" ?

**Comment by gajus** [comment]
If there was a way to subscribe to NOTICE events (there isn't at the moment), then you could log them however you want.

**Comment by dmpvost** [comment]
Ok, so my question is more about Roarr, how to control log on NodeJS and get it in JSON format in NodeJS? So I would be able to parse it myself?

thank

**Comment by gajus** [comment]
If you just run your program without using `roarr pretty-print`, you will get logs in JSON format. You cannot get them in the same process, though – this is by design.

**Comment by dmpvost** [comment]
And there is a trick maybe? hack? middleware way to get them?

In pg lib, I had to modify by hand to show log, but still not in my process
thank

**Comment by dmpvost** [comment]
Finally, I have time now to move on Slonik. 

Begin a bit difficult, but it's start to work well.

I notice that, on the returned object of a query, there is a field "notices" 


command:  SELECT
fields:
  \ -
    dataTypeId: 16
    name:       query
notices:
   (empty array)
rowCount: 1
rows:
 \  -
     query: true

**Comment by gajus** [comment]
If backend raises a notice during a query execution, then that notice is associated with that query execution and available in the `notices` result property.

**Comment by dmpvost** [comment]
I have try a lot of different combinaison, but I go no log in this fields

Any help for put that with slonik?

client.on('notice', msg => console.warn('notice:', msg))

How can I have acmes to "client.on" ? outside of slonik lib? 
Or If I should, I can fork slonik.. or do something to have get access..

**Comment by dmpvost** [comment]
I have try different solution, my backend raises notice, but nothing in this array

**Comment by gajus** [comment]
Please create a test case in https://github.com/gajus/slonik/blob/master/test/slonik/integration.js

**Comment by dmpvost** [comment]
I create the test case here :  

https://github.com/dmpvost/slonik/commit/5a5d76a17d1fc412aca268b2376ec375d5ae42e0

I have fork-it, not able to create a new branch in the project.

The test work, and it seams that I have notices log....
So I don't understand what I missed in my project.. I should investigate again

**Comment by dmpvost** [comment]
It was because I had pg and pg native installed on my package.
After that I remove them, i got all NOTICES.

Everything work very well, but I saw that I don't got NOTICES when there is an error.

The NOTICES stack messages are not ship in the error constructor.
Is it to possible to catch them and add it?

**Comment by gajus** [comment]
The last thing you've described sounds like a bug.

It should certainly be possible to do that.

Take a look at the code. I will prioritise merging this.

**Comment by dmpvost** [comment]
> The last thing you've described sounds like a bug.
> 
> It should certainly be possible to do that.
> 
> Take a look at the code. I will prioritise merging this.

Great! I will follow.



> It was because I had pg and pg native installed on my package.
> After that I remove them, i got all NOTICES.
> 
> Everything work very well, but I saw that I don't got NOTICES when there is an error.
> 
> The NOTICES stack messages are not ship in the error constructor.
> Is it to possible to catch them and add it?

It could be nice to add a warning in the documentation, about pg/pg-native, that if it's installed, it's impossible to get the log. I was looking a long time before find this information somewhere around all your post in the web. Thank!

**Comment by dmpvost** [comment]
Ok I will try to code it, I was not sure, if it was to me to do it, or if you will do it.
I will look if I find a way to add it on slonik.

**Comment by dmpvost** [comment]
@gajus, I will start to work in this feature. 

How should I process? Create a branch? I cannot push a new branch, it's restricted

**Comment by gajus** [comment]
This describes the process of forking and raising a PR.

https://auth0.com/blog/a-first-timers-guide-to-an-open-source-project/

**Comment by dmpvost** [comment]
Ok, I've add it, and test associate.

But I've some issue to configure a clean test suite.
What configuration you use for your docker image etc.

To be sure to execute test like you.

I cannot commit right now, pre-commit failed lol
