### ISSUE TITLE
Insert an array of SQL fragments

### ISSUE THREAD

**Issue by bartolkaruza** [gajus/slonik#116]
For my particular use case, I'm generating an array of SQL fragments that depend on each other. The resulting SQL is something like this:

```
with 1 as (...)
with 2 as (... FROM 1)
with n as (... FROM n-1)
SOME MORE SQL
```

The number of layers is dynamic and generated as an array. The first implementation using slonik I tried:

```js
const levels = [];
for (let x = 2; x < n; ++x) {
 levels.push(sql`with ${x} as (SELECT ... FROM ${x - 1})`
}

const mainQuery = sql`with 1 as (SELECT ...) ${levels} SOME MORE SQL`
```

The array of SQL fragments, unfortunately, is not interpreted and the outer sql tag leads to `token.sql.replace is not a function`. Because the length of levels is dynamic, there is no practical way to unroll that for loop.

Is there any other way to achieve this with slonik sql tags? We are now solving the problem with raw js template strings, which don't protect against SQL injection in any way.

```
const mainQuery = sql`with 1 as (SELECT ...) ${sql.raw(levels)} SOME MORE SQL`
```

**Comment by gajus** [comment]
https://github.com/gajus/slonik#slonik-query-building-sql-join
