### ISSUE TITLE
Question: How to insert an unwrapped array of values that contain an array?

### ISSUE THREAD

**Issue by danabrams** [gajus/slonik#117]
I apologize, I know there are similar issues but I've been through them all a few times and can't figure it out.

I'm trying to insert multiple rows at once where each row contains 2 arrays.

The schema looks like this:

```
CREATE TABLE soundtracks (
    performers TEXT[],
    composers TEXT[],
    song TEXT,
    id SERIAL
)
```
and my current attempt is this:
```
function soundtracksQuery() {
    const soundtracks = item.soundtracks.map(soundtrack => [
      sql.array(soundtrack.performers, 'text'),
      sql.array(soundtrack.composers, 'text'),
      soundtrack.song
    ]);
    return sql`INSERT INTO soundtracks(performers, composers, song)
    SELECT * 
    FROM ${sql.unnest(soundtracks, ['text[]', 'text[]', 'text'])}
    `;
  }
```
However, I get the following error:
`error: column "artists" is of type text[] but expression is of type text`.

Any help would be much appreciated.

**Comment by gajus** [comment]
```diff
function soundtracksQuery() {
  const soundtracks = item.soundtracks.map(soundtrack => [
-    sql.array(soundtrack.performers, 'text'),
-    sql.array(soundtrack.composers, 'text'),
+    soundtrack.performers,
+    soundtrack.composers,
    soundtrack.song
  ]);
  return sql`INSERT INTO soundtracks(performers, composers, song)
  SELECT * 
  FROM ${sql.unnest(soundtracks, ['text[]', 'text[]', 'text'])}
  `;
}

```

This should work. If not, please use https://github.com/gajus/slonik-interceptor-query-logging and `ROARR_LOG=true` to export what is the actual query and values that are being sent.

**Comment by danabrams** [comment]
I continue to get the same error with your suggestion: `error: column "performers" is of type text[] but expression is of type text.`

The roarr logger appears to give a valid query, with the array fields represented as `$1::\"text\"[][]`, but I get an error with code 42804, `you will need to rewrite or cast the expression`

**Comment by gajus** [comment]
I will need more information to debug this.

Please amend the code in `./node_modules/slonik/dist/routines/executeQuery.js` to capture the query that is being executed and the values that are being passed to `node-postgres` query. If the issue persists despite query/ parameters appearing right, then this is an issue with `node-postgres`.

**Comment by nikhilag** [comment]
@gajus This is not working for me either. I am adding the code, generated query and values:-

Code:-
``` 
const insertQuery = sql`
        INSERT INTO district_module_steps
        (${sql.join(identifiers, sql`, `)})
        SELECT * FROM
        ${sql.unnest(values, values_types)}
        RETURNING *
```

values:-
```
[["17","PPPC","pending","2021-01-06T11:16:00.231Z",[],null,null],
["17","IRR-MULTICROPPED","inactive",null,[],null,null],
["17","LAND-SCH-AREAS","inactive",null,[],null,null]]
```

Generated sql query:-
```
INSERT INTO district_module_steps
        ("district_id", "cms_module_step_id", "status", "activated_on", "activated_by_steps", "due_on", "warn_on")
        SELECT * FROM
        unnest($1::"int4"[], $2::"text"[], $3::"step_status"[], $4::"timestamptz"[], $5::"text"[][], $6::"timestamptz"[], $7::"timestamptz"[])
        RETURNING *
```

Error: `"error: column \"activated_by_steps\" is of type text[] but expression is of type text\n    at`

**Comment by gajus** [comment]
@nikhilag The best thing to do would be to contribute a failing integration test showing your use case.
