### ISSUE TITLE
Pass custom log function

### ISSUE THREAD

**Issue by moltar** [gajus/slonik#119]
It would be great to be able to replace Roarr with a custom logger.

Use case:

I'm currently using simple `debug`, and only in testing environment. This place very nicely with Jest.

Roarr output is JSON, and it cannot be parsed well when mixed with Jest output.

**Comment by gajus** [comment]
No intent to support custom logger.

Roarr is used by many sub-packages of Slonik.

Consider replacing debug with Roarr: https://medium.com/free-code-camp/roarr-the-perfect-json-logger-node-js-and-browser-935180bda529

**Comment by moltar** [comment]
Any suggestions as to how make it work mixed with other output?

E.g. as part of running tests.

**Comment by gajus** [comment]
Requirements are unclear. Please clarify requirements and I am happy to help.
