### ISSUE TITLE
Ensure that each pool.connect() is getting a new connection

### ISSUE THREAD

**Issue by gajus** [gajus/slonik#121]
pg-pool keeps connections open for `idleConnectionMillis` after they are released. This is normally a desired behaviour. However, in the context of Slonik, it can have undesired consequences, e.g.

```js
pool.connect((connection1) => { setTimeout(() => { connection1; }, 1000) });
pool.connect((connection2) => { setTimeout(() => { connection2; }, 1000) });

```

In the above example, it would be normally expected that `connection1` can no longer be used after promise from the parent `pool.connect` is returned. However, due to connection pooling and how Slonik manages acquiring idle connections from the pool, it is possible that access to `connection1` will persist if there is another `pool.connect` that recycles the connection.

This can produce nasty, hard to debug bugs/ memory leaks.

A quick fix is to disable connection recycling.

A long-term fix might be:

* Disable and acknowledge that we do not support idle connection pooling. This is my preferred solution. It ensures that we always have a fresh connection. Connection pooling should be handled by pg-bouncer, etc. The only concern here is what is the performance impact, i.e. what is the additional time it takes to acquire a new connection.
* Continue to terminate the connection, but create a new connection and put it in idle state.
* Create new connection state every time connection is created or acquired. Track when connection is terminated and restrict invocation of query methods for terminated connections (as dictated by the state that we keep). My concern with this approach is that it will cause bugs such as this https://github.com/gajus/slonik/issues/121. It is not clear what makes the queries hang, other than that they are being recycled.

Note: In all scenarios, user can still use `minimumPoolSize` to pro-actively keep X number of active/ idle connections.

**Comment by gajus** [comment]
Temporary fix is implemented. Need to design long-term fix.

**Comment by gajus** [comment]
The most reasonable solution seems to be:

* discard connections that were acquired explicitly, i.e. `pool.connect`
* release connections that were acquired implicitly, i.e. `pool.query`
* before releasing connections execute `DISCARD ALL`

This has been implemented: https://github.com/gajus/slonik/commit/1e84a0c733c364cfadbcd5d9fba2151a9c66bbf6

**Comment by gajus** [comment]
Please elaborate what is the problem.

**Comment by adriancooney** [comment]
Sorry @gajus, reading back over my comment, it wasn't very helpful.

For my tests, Slonik's mocking doesn't fit my requirements unfortunately. I want to be able to commit to a test database and rollback any changes after each tests execution. This solution has been working fine with `pg` where I execute a `BEGIN`, install a `SAVEPOINT` and at the end of the test `ROLLBACK` to the savepoint. This is a standard strategy for integration testing.

With Slonik, there are two barriers to this method. For every most methods, they are `IMPLICIT_QUERY` which execute a `DISCARD ALL` which cannot be executed inside a transaction. I managed to hack a fix around that but ran into another issue where explicitly acquiring a connection via `connect` closes the connection once it completes and in the process breaking the transaction. For my use case, I need a single connection that can maintain a transaction throughout the lifetime of a test. 

I'm aware of Slonik's `transaction` and nested transactions but that requires wrapping the test inside a callback which, at the current state, is unfeasible for me.

**Comment by gajus** [comment]
I don't recommend using transactions for isolating tests. Run tests sequentially and re-create the database after every test. This is what I do, for what it is worth.

Anyway, what is the fix that you are proposing?

**Comment by skarbovskiy** [comment]
is it desired behavior to close connection in `IMPLICIT TRANSACTION` query? Faced an issue when heavily loaded app with a lot of transactions usage opens 100+ connections per second
