### ISSUE TITLE
Using Slonik with an external connection pooler

### ISSUE THREAD

**Issue by SirensOfTitan** [gajus/slonik#123]
I apologize for the non-issue issue, more of a question or perhaps a feature request:  how might one go about using slonik with an external connection pooler like PGBouncer?   `createPool` is the only `create` method that seems to be exported, so we couldn't just use and then close connections as we go, allowing `PGBouncer` to handle the pooling.

**Comment by gajus** [comment]
If you wanted to always have a single connection (and let pgbouncer to manage pooling), then you would simply use `createPool` and configure `maximumPoolSize` to `1`. I do not recommend this. There are many cases where you application can benefit from having access to multiple connections. If you simply want to ensure that idle connections are not held for a long time, then configure `idleTimeout` to a low value.

The default configuration (`maximumPoolSize` 10 and `idleTimeout` 5000 (5 seconds)), is already designed to work with an external load balancer and without.
