### ISSUE TITLE
Slonik unexpectedly tries to open a connection to localhost:5432

### ISSUE THREAD

**Issue by aandreev** [gajus/slonik#125]
Hi,

I'm pretty sure the issue is on my side, but I would appreciate any advice.

I am using slonik inside a nest.js app, loading it in a provider like this:
```typescript
import { Injectable } from '@nestjs/common';
import {
  createPool,
  DatabasePoolType,
} from 'slonik';
import { ConfigService } from '../config/config.service';

@Injectable()
export class ConnectionProvider {
  public pool: DatabasePoolType;

  constructor(config: ConfigService) {
  this.pool = createPool(config.postgresUrl);
  }
}
```

This is the only place in my code that invokes createPool(), and, when debugging, it does so during DI successfully, and with the correct server connection string. I see the connection open on the Postgres side.

When I call an API endpoint, i get the following 
```
ConnectionError: connect ECONNREFUSED 127.0.0.1:5432
    at createConnection (/[redacted]/node_modules/slonik/dist/factories/createConnection.js:34:11)
    at process._tickCallback (internal/process/next_tick.js:68:7)
Executed 'Functions.main' (Succeeded, Id=c1573583-dc32-4856-828e-3f37e7e89997)
Executed HTTP request: {
  "requestId": "d5f03541-615d-4872-b780-cf0f62c01832",
  "method": "GET",
  "uri": "/api/secret",
  "identities": [
    {
      "type": "WebJobsAuthLevel",
      "level": "Admin"
    }
  ],
  "status": 500,
  "duration": 2761
```

For clarity, nest runs inside an Azure Functions wrapper.

If I start postgres locally with no security, the queries actually run fine.

Why would slonik call createConnection again, and without the connection string parameter? Can pools be created automatically? Am I messing things up with DI, singletons etc?

Thanks,

Andrey

**Comment by gajus** [comment]
I cannot think of a single reason for this to happen other than your DNS resolving whatever the DSN you are using to localhost. The first thing I would try is to replicate the same behaviour using node-postgres.

I am closing the issue, but please continue to post and I will continue to answer.

**Comment by aandreev** [comment]
I resolved the issue, it was on my side (although an error could have been reported here).

Reproducing the code in node-postgres worked as expected, with no error. In trying to isolate the error with, I reduced the code to just:

```typescript
const pool = createPool(url);
const res = await pool.one(sql`select 1 as foo`);
```

which would attempt to open a connection to `127.0.0.1:5432`.

#### Root cause

I was using a `dbname?parm1=val1&parm2=val2` style of URL, which is apparently unsupported, but parses as a URL, leaving values uninitialized and defaulting to `localhost:5432`. 

I suspect slonik or the upstream library could do well by not using defaults for a connection string. Why this works in node-postgres and not here I have not tried to find out.

I was also wrong about the connection being established properly at the DI stage, as reported initially. The open connection came from other tooling.

**Comment by gajus** [comment]
Unfortunately connection string parsing is handled by a third-party library.

**Comment by gajus** [comment]
This can be definitely improved on our side.

**Comment by aandreev** [comment]
It would be helpful to state at the README.md docs that `postgres://` URIs are the the only valid parameter format. This could have saved me a day or two, pondering if it is DI or race conditions that I have messed up.

By the way, cheers for building a very cool tool! I love it and it works just the way I want it to!

**Comment by gajus** [comment]
Addressed in this PR https://github.com/gajus/slonik/commit/6c3b178c9b52418b348fb0d8a7a8e75fb31047f1
