### ISSUE TITLE
Treat undefined values as NULL

### ISSUE THREAD

**Issue by jabas06** [gajus/slonik#128]
Hi @gajus,

Correct me if I'm wrong. My understating is that slonik doesn't allow to bind `undefined` values. Don't you think it would be good to allow to bind `undefined`? `node-postgres` treats `undefined` as NULL internally.

This way we can remove a lot of checks like the following before executing queries:

```js
const col1 = A === undefined ? null : A
const col2 = B === undefined ? null : B
```

Even better, we could use optional chaining for nested properties in our templates:
```js
sql`INSERT INTO table (col1, col2) values (${parent.prop1}, ${parent.child.?nestedProp})`
```

**Comment by gajus** [comment]
Not allowing `undefined` values is very much by design.

It guards against false references, e.g.

```js
sql`INSERT INTO table (col1, col2) values (${parent.prop1}, ${parent.popr2})

```

If `col2` accepted NULL values, then the `popr2` typo could go unnoticed for a long time.

**Comment by weeksie** [comment]
@gajus that's what typescript is for. `null` is a weird beast in javascript and really shouldn't be used.
