### ISSUE TITLE
source-map dependency causing errors

### ISSUE THREAD

**Issue by jabas06** [gajus/slonik#129]
Hi, 

With a fresh install of `slonik`, I'm experiencing the same issue reported  [here](https://github.com/gajus/get-stack-trace/pull/2), because my environment has a `fetch` function. 

I noticed that `get-stack-trace` version `2.0.1`  is supposed to use a newer version of `source-map`. But looking at package-lock.json, it keeps installing version `0.7.3` of `source-map` which is the package with the problem.

Is maybe something wrong with `get-stack-trace@2.0.1` published package because is not reflecting the `source-map` update?

![image](https://user-images.githubusercontent.com/3453385/69363151-8f0d7a00-0c55-11ea-817e-be5b5fcf4b76.png)

**Comment by gajus** [comment]
I have bumped all dependencies, just in case.

**Comment by jabas06** [comment]
Thank you! @gajus, the error is gone in the new versions 🎉
