### ISSUE TITLE
[Documentation] `sql.identifier` documentation is unclear for arrays

### ISSUE THREAD

**Issue by ben-turner** [gajus/slonik#132]
https://github.com/gajus/slonik#sqlidentifier

The documentation doesn't explicitly say that arrays are turned into schema.table and the example doesn't make sense. I'm assuming that `['foo', 'bar']` would become `"foo"."bar"` but I'm not totally sure. It would also be great if that section could talk about how values are escaped.

Thanks!

**Comment by gajus** [comment]
What about example does not make sense?

**Comment by ben-turner** [comment]
```
sql`
  SELECT 1
  FROM ${sql.identifier(['bar', 'baz'])}
`;
```
Produces:

```
{
  sql: 'SELECT 1 FROM "bar"."bar"',
  values: []
}
```

If my assumption is correct that should produce `"bar"."baz"` not `"bar"."bar"`
