### ISSUE TITLE
Guidance now that normalizeIdentifier was removed

### ISSUE THREAD

**Issue by hjr3** [gajus/slonik#133]
With regards to https://github.com/gajus/slonik/commit/91b60472a6ff61f3ff8b573999df015f12836571#diff-94ace983602ad557b56264c8586daec1

we were doing something like:

```typescript
const idents = Object.keys(req.body).map(ident => sql.identifier([normalizeIdentifier(ident)]));
```

to transform a camelCase into snake_case. Is the recommended solution to use `snakeCase` directly from lodash now?

**Comment by gajus** [comment]
I would just use snakeCase, but abstract it with a local utility – `normalizeIdentifier`.
