### ISSUE TITLE
Connection Error: connectionHandler is not a function

### ISSUE THREAD

**Issue by s888** [gajus/slonik#134]
Hi,

I am migrating from knex to Slonik.

So I wanted to test the perfomance.
But I am getting errors while creating a connection
Here is the code:

```
import { createPool } from 'slonik'
const connectString = `postgresql://${encodeURIComponent(config.user)}:${encodeURIComponent(config.password)}@${config.host}:${config.port}/${config.database}`
const pool = createPool(connectString);
async function init() {
    const connection = await pool.connect();
    let res = await connection.query(sql`SELECT 1`);
    console.log("res",res);
}
init();
```
But I am getting this error:
```
(node:22608) UnhandledPromiseRejectionWarning: TypeError: connectionHandler is not a function
    at /xxx/node_modules/slonik/dist/binders/bindPool.js:34:16
    at createConnection
```
Thanks in advance.

**Comment by tranzium** [comment]
The `connect()` method does not return the `connection` object but the response of the provided `connectionHandler` callback function.

`async function init() {
    const res = await pool.connect((connection) => {
		return connection.query(sql`SELECT 1`);
    });
	console.log("res", res);
}`
