### ISSUE TITLE
Is there a way to dynamically pass an operand?  

### ISSUE THREAD

**Issue by scottyj503** [gajus/slonik#136]
We currently have implemented the following:
      sql` ${sql.identifier(['alias', 'fieldName'])} = ${value}`

What we would like to do is: 
      sql` ${sql.identifier(['alias', 'fieldName'])} ${operand} ${value}`

In looking through the docs and various articles, we were unable to determine if this is possible.  

When we try the second option in code, it errors out: "error: syntax error at or near \"$3\"

~ Thanks

**Comment by gajus** [comment]
Just use `sql`.

```js
sql`${sql.identifier(['alias', 'fieldName'])} ${someCondition ? sql`=` : sql`!=`} ${value}`
```
