### ISSUE TITLE
ts-sql-plugin idea

### ISSUE THREAD

**Issue by darky** [gajus/slonik#137]
https://github.com/xialvjun/ts-sql-plugin
This project do something like static type compilation of sql queries.
It work due to EXPLAIN of sql queries under hood.
Also, ts-sql-plugin have cli tool for CI/CD
Would be awesome to have similar in slonik 🚀

**Comment by gajus** [comment]
This would only be safe for simple SELECT queries that would fail upon execution anyway. You couldn't execute queries that include function invocations (as they might be mutating) and other **C**R**UD**.

That said, there is already https://www.npmjs.com/package/@slonik/typegen.
