### ISSUE TITLE
Prepared statement fails on binding parameters

### ISSUE THREAD

**Issue by micheleriva** [gajus/slonik#138]
Hi,
I'm trying to run the following query using Slonik:

```js
sql`
 SELECT users.id, first_name, last_name, biography,
 admin.id AS id_admin,
 admin.role,
 admin.company

 FROM users

 LEFT JOIN admin
 ON articles.id_author = authors.id

 WHERE to_tsvector(biography || '. ' || first_name || last_name) @@ plainto_tsquery('${searchTerm}');
`
```

but I always get back the following error:

```
bind message supplies 1 parameters, but prepared statement "" requires 0 
```

of course, `searchTerm` variable is in scope when running the query.

I've noticed that the same issue occures with `pg` (https://stackoverflow.com/questions/43755454/bind-message-supplies-1-parameters-but-prepared-statement-requires-2) and knex (https://github.com/knex/knex/issues/1207), but I couldn't find any reference with Slonik yet.

Thanks!

**Comment by micheleriva** [comment]
Ok I've finally found how to fix it.

```js
const searchTerm = `'${term}'`;

sql`
 SELECT users.id, first_name, last_name, biography,
 admin.id AS id_admin,
 admin.role,
 admin.company

 FROM users

 LEFT JOIN admin
 ON articles.id_author = authors.id

 WHERE to_tsvector(biography || '. ' || first_name || last_name) @@ plainto_tsquery(${searchTerm});
`
```

I just had to get rid of the quotes inside the `sql` query.
I think that it should be documented, 'cause it's not so intuitive 😞

**Comment by nodefish** [comment]
I'm encountering this issue in an `ALTER TABLE` scenario and with `sql.raw` being deprecated I don't see any simple way to get around it.

I'm doing the following:

```js
await tx.query(sql`alter table ${sql.identifier([table_name])} add check(length(${col_name}) <= ${col.maxlength})`);
```

This is producing the following error:

```
error: bind message supplies 1 parameters, but prepared statement "" requires 0
```
