### ISSUE TITLE
[Discussion]: How does this sql tagged template differ to other solutions

### ISSUE THREAD

**Issue by pke** [gajus/slonik#139]
I wonder how this project's `sql` tagged template differs from those two other ones:

[1] https://github.com/felixfbecker/node-sql-template-strings
[2] https://github.com/blakeembrey/sql-template-tag
[3] https://github.com/TehShrike/sql-tagged-template-literal

I for one do not use pg (at the moment) but use the `sql` template to secure my queries.
What are the pros/cons over the other mentioned projects?

Could we maybe put a `Related` section in the readme like [here](https://github.com/blakeembrey/sql-template-tag#related)?

**Comment by gajus** [comment]
No, outside of scope for this project to list only marginally related projects.
