### ISSUE TITLE
Question: use of transaction

### ISSUE THREAD

**Issue by dmpvost** [gajus/slonik#149]
I see in tutorial, that we can open a transaction, be we need to put all call together.
It's not all the time easy to do that.

I would like to try for some use case, to open a transaction for one Api-transaction

Open with a middleware when a call arrive a transaction "BEGIN"
That all call coming SQL query are tagged to this transaction for this in this context.
And "COMMIT" on the end.

Something like this is possible?
Or some other alternative

**Comment by gajus** [comment]
I strongly do not recommend doing this for the reasons discussed in the documentation. You are running a high-risk of mishandling transactions. Transactions need to be short-lived and isolated from anything else. Not everything needs to be a transaction.

Anyway, you can always just use good old SQL yourself to start/ commit/ rollback a transaction.

```js
pool.connect(async (connection) => {
	await connection.query(sql`BEGIN`);
	await connection.query(sql`UPDATE [..]`);
	await connection.query(sql`COMMIT`);
});

```

**Comment by dmpvost** [comment]
I got it, thank!
