### ISSUE TITLE
syntax error at or near "$1" when running `SET`

### ISSUE THREAD

**Issue by AndrewO** [gajus/slonik#150]
```js
db.query(sql`SET foo.bar TO ${foobar}`);
```

throws `syntax error at or near "$1"`. From what I understand, this is actually a limitation with PostgreSQL where [not every statement supports prepared statements/parameter binding](https://github.com/brianc/node-postgres/issues/539#issuecomment-37708098), so this isn't an issue in particular to Slonik.

However, the solutions I see elsewhere suggest using raw string interpolation, which is something that Slonik actively works to prevent (for good reason). And this inconsistency in Postgres breaks the abstraction for Slonik a bit...

This seems to work:

```js
db.query(sql`SET foo.bar TO ${sql.indentifier([foobar.toString()])}`);
```

But that doesn't feel like the proper use of `indentifier` and I don't know if I'm just getting lucky with my input so far.

So this is more of a question than a bug: what's the safest and least hacky way to do this from Slonik?

## Expected Behavior

```js
sql`SET some.var TO ${foobar}`
```
works

## Current Behavior

Error from underlying DB: `syntax error at or near "$1"`

## Possible Solution

```js
sql`SET some.var TO ${sql.someSanitzingFunction(foobar)}`
```

I dunno... Right now the underlying PG library takes care of safely binding things, so it doesn't feel great to have to duplicate that in Slonik. Or is that what `sql.identifier` is doing? In that case, maybe just allow it to take a single argument as well as an array?

But I'm definitely not advocating enhancing `sql` to be aware of the query within it to determine if it supports binding. This is enough of an edge case that the programmer should be expected to do a little work.

**Comment by gajus** [comment]
`SET` accepts value quoted in double quotes. `sql.identifier` quotes and inlines value. This is why it works.

I think this calls for another method, e.g.

```js
sql`SET foo TO ${sql.inlineValue(bar)}`

```

Similar to `sql.indentifier`, this would single-quote the value and inline it.

Will leave this open for couple of days in case anyone who is following comes up with a better proposal.

Note that Slonik does support string execution as a query through https://github.com/gajus/slonik-sql-tag-raw. The only valid use case for it is when you are loading the query from some external input.

**Comment by danielhep** [comment]
I'm currently encountering this issue, but I'm using the sql-tag-raw plugin. I'm loading a .sql file from a file and passing it to raw():

`pool.query(sql`${raw(initFile, { schema: flags.schemaName })}`)`

The :schema variable occurs several times inside my initFile, but for some reason I'm getting `syntax error at or near "$1"` when I run it. How am I supposed to be using the raw plugin, because this doesn't seem to be working?

**Comment by gajus** [comment]
You can now use `sql.literalValue`.

**Comment by inspiraller** [comment]
I am having same problem:
example
```js
pool.connect(async (connection) => {
      try {
        const result = await connection.query(
          sql`
        CREATE TABLE ${PG_TABLE}(
          id SERIAL PRIMARY KEY,
          name VARCHAR(500) NOT NULL,
          completed BOOLEAN NOT NULL);
      `
        );
        // never gets here
      } catch (err) {
        // error: 
        // error: syntax error at or near "$1"
        
        // My db log: Is not passing the variable name via this approach.
        // CREATE TABLE $1(...)
      }
    });
```
