### ISSUE TITLE
Thoughts on making it possible to add stuff to the executionContext of a query?

### ISSUE THREAD

**Issue by adevine** [gajus/slonik#151]
The executionContext that is made available to interceptors has a 'sandbox' property for adding arbitrary data. What are your thoughts on making it possible for the code making the actual query to add stuff to this context?

Use case is in my current logging framework I always pass around my own 'loggingContext' object (e.g. data that in the Java world I would set on something like a NestedDiagnosticContext on a ThreadLocal, but in Node you need to pass it around). For example, all incoming requests add a request ID that I log everywhere. I'd like to add this request ID so that my logging interceptor can access it.

Wouldn't want to overcomplicate what is a nice, very straightforward API, just curious on your thoughts.

**Comment by adevine** [comment]
Wow, @gajus , you are a beast! Just saw this blog post by you:

https://dev.to/gajus/ultimate-guide-to-concurrent-logging-in-node-js-18h7

Will try that out and play with Roarr more.

**Comment by gajus** [comment]
I believe this to be no longer relevant as you can achieve this using `AsyncLocalContext`.
