### ISSUE TITLE
Is it possible to import Slonik natively in Node?

### ISSUE THREAD

**Issue by MattCarr147** [gajus/slonik#153]
Sorry if I'm missing something obvious here, my brain is struggling to stay engaged amidst this confusion around imports.

## Expected Behavior
I'm developing a nodejs-based API and I'm trying to use ES6 import syntax and avoid dependencies on Babel, esm or similar when doing so. To this end, I'm using the experimental modules behaviour in NodeJS (actually running v13 at the moment so it's enabled by default). 

I expect to be able to `import { createPool, sql } from 'slonik'` in my code. 

## Current Behavior
`SyntaxError: The requested module 'slonik' does not provide an export named 'sql'` 

(or createPool, etc).

**Comment by gajus** [comment]
I am not familiar with Babel/ native incompatibilities. Cannot answer.

**Comment by MattCarr147** [comment]
@gajus no probs, that makes two of us!

I've had some luck importing/using as follows:

```
import Slonik from 'slonik'

const pool = Slonik.createPool('postgres://');
etc.
```

I now remember making a similar change when importing hapi. 

I'm relatively new to NodeJS, if any of this becomes clearer to me in the future I'll try and clarify with regards to a possible fix, if one is even required. 

Cheers

**Comment by jgonera** [comment]
Slonik seems to be transpiled to ES5 or lower:
https://unpkg.com/browse/slonik@22.4.4/dist/index.js

You need ES6 modules in the distributed package to be able to do it. One way would be for Slonik to have an alternative ES6 build target that `package.json` would point to by using `module` property (while `main` would still point to the ES5 build):

```json
"main": "./dist/index.js",
"module": "./esm/index.js",
```

I don't know Slonik's build pipeline so not sure how easy this is to add.

**Comment by mrjjwright** [comment]
This also worked for me...

```js
import Slonik from 'slonik'

const pool = Slonik.createPool('postgres://');
etc.
```

**Comment by gajus** [comment]
This should already work in latest Slonik.
