### ISSUE TITLE
Values other than string | number in a createMockQueryResult?

### ISSUE THREAD

**Issue by cronin4392** [gajus/slonik#154]
Hey there,

I was implementing some mock queries using `createMockQueryResult` and am running into an issue. I'd like to mock some data that contains keys that are types other than `string | number`. `createMockQueryResult` is expecting all the columns to be type of `QueryResultRowColumnType = string | number` therefore I am not able to mock any other types of data.

For example, I'd like to have a boolean value. My current work around has been to cast this as a `1` or `0` but this is not reflective of the result I would expect to normally get from a real query. Maybe I am not thinking of this in the right way? Would be curious how it would be recommended to approach this.

Thanks!

**Comment by gajus** [comment]
Is the problem the type declaration?

If yes, is this referring to TS or Flow?

Either way, you should be able to just suppress the warnings. In Flow that would be `// $FlowFixMe`.

See this discussion. https://github.com/gajus/slonik/issues/146
