### ISSUE TITLE
Query Building Help: Insert

### ISSUE THREAD

**Issue by konsumer** [gajus/slonik#155]
Forgive me if this is the wrong place to ask questions. If so, please tell me where to go.

I'd like to safely create generate `INSERT` statements from JS objects. I am writing a lot of code that uses logic switches to manually run queries based on which fields are in the object, and it seems simpler to just make a general method that assembles the query from an object, directly.

My first pass is this:

```js
const insert = (table, object) => {
  return sql`
    INSERT INTO ${table} (
      ${sql.join(Object.keys(object), sql`, `)}
    ) VALUES (
      ${sql.join(Object.values(object), sql`, `)}
    )
  `
}
```

which makes an invalid query:

```js
console.log(insert('Stuff', {
  id: '85d8d76b-a15b-5e3e-b160-2f477f32fd64',
  name: 'My Favorite Chair',
  color: 'black'
}))

/*
{
  sql: '\n' +
    '    INSERT INTO $1 (\n' +
    '      $2, $3, $4\n' +
    '    ) VALUES (\n' +
    '      $5, $6, $7\n' +
    '    )\n' +
    '  ',
  type: 'SLONIK_TOKEN_SQL',
  values: [
    'Stuff',
    'id',
    'name',
    'color',
    '85d8d76b-a15b-5e3e-b160-2f477f32fd64',
    'My Favorite Chair',
    'black'
  ]
}
*/
```

Which gives me `error: syntax error at or near "$1"` when I try to `query` it, so I assume I am inserting the table-name incorrectly.

Is there a better way to do this?

**Comment by konsumer** [comment]
I tried this, too, thinking I probly need to use `identifier` to escape the table/field-names:

```js
const insert = (table, object) => {
  return sql`
    INSERT INTO ${sql.identifier([table])} (
      ${Object.keys(object).map(f => sql.identifier([table, f]))}
    ) VALUES (
      ${sql.join(Object.values(object), sql`, `)}
    )
  `
}
```
which resulted in `TypeError: Unexpected value expression.`

I also tried just quoting the table-name, but leaving fields dynamic:

```js
const insert = (table, object) => {
  return sql`
    INSERT INTO ${sql.identifier([table])} (
      ${sql.join(Object.keys(object), sql`, `)}
    ) VALUES (
      ${sql.join(Object.values(object), sql`, `)}
    )
  `
}
```
Which doesn't error at generation time, but also produces invalid SQL:

```
{
  sql: '\n' +
    '    INSERT INTO "Stuff" (\n' +
    '      $1, $2, $3\n' +
    '    ) VALUES (\n' +
    '      $4, $5, $6\n' +
    '    )\n' +
    '  ',
  type: 'SLONIK_TOKEN_SQL',
  values: [
    'id',
    'name',
    'color',
    '85d8d76b-a15b-5e3e-b160-2f477f32fd64',
    'My Favorite Chair',
    'black'
  ]
}
```

**Comment by konsumer** [comment]
Sorry for the noise, this actually works great:

```js
const insert = (table, object) => {
  return sql`
    INSERT INTO ${sql.identifier([table])} (
      ${sql.join(Object.keys(object).map(f => sql.identifier([f])), sql`, `)}
    ) VALUES (
      ${sql.join(Object.values(object), sql`, `)}
    )
  `
}```

Is this a terrible thing I am doing? Is there a more "slonik way"?

**Comment by gajus** [comment]
Looks reasonable. You can also have a look at how https://github.com/gajus/slonik-utilities is implemented.

**Comment by charlex** [comment]
This would be helpful to document for others in the README. For reference, I was searching with these keywords to find this:

- dynamic value names
- dynamic column names
- serializing insert variables vars
