### ISSUE TITLE
No documentation for SSL

### ISSUE THREAD

**Issue by SkeLLLa** [gajus/slonik#159]
Slonik lib doesn't have any documentation regarding SSL. Also I didn't find any way of passing `rejectUnauthorized` option to underlying `pg`.

Is it available? Or it's not implemented yet?

Thanks.

**Comment by hjr3** [comment]
This is not currently possible because https://github.com/brianc/node-postgres/tree/master/packages/pg-connection-string does not support setting this parameter into the ssl object. One of two things needs to happen:

1. Slonik accepts a connection object.
2. `pg-connection-string` connection string is updated to support something like `var connectionString = 'pg:///?sslRejectAuthorization=true';`

**Comment by aimee-gm** [comment]
@SkeLLLa as of v8.1.0 of `pg`, this can be configured using a query parameter on the connection string, or an environment variable: https://github.com/brianc/node-postgres/blob/f0bf3cda7b05be77e84c067a231bbb9db7c96c39/CHANGELOG.md#pg810

**Comment by matthew-white** [comment]
Slonik itself seems to specify `false` for `rejectUnauthorized` when SSL options are specified:

https://github.com/gajus/slonik/blob/6ec1299fbb7d0d8b9bc45bfff2311a20eb94d421/src/factories/createPoolConfiguration.ts#L31-L36

However, I don't see a way to specify `true`. Slonik uses `pg-connection-string`, but I don't see a `pg-connection-string` option that would result in `true` for `rejectUnauthorized`. (There's `sslmode=no-verify`, but that sets `rejectUnauthorized` to `false`.) Similarly, `pg` looks at the `PGSSLMODE` environment variable, but there doesn't seem to be a way to use that to set `rejectUnauthorized` to `true`. (There's also the `pg` option `ssl=no-verify`, but I think `pg-connection-string` will parse that out, and again, that sets `rejectUnauthorized` to `false`.)

**Comment by gajus** [comment]
Would be open to a custom `pg-connection-string` implementation that respects these settings. Never got around to do it myself, though that is a pretty simple and valuable contribution anyone could make.

**Comment by gajus** [comment]
You now have two options:

* `sslmode` URI parmeter https://github.com/gajus/slonik#connection-uri
* `ssl` configuration parameter https://github.com/gajus/slonik#api
