### ISSUE TITLE
TypeScript definitions

### ISSUE THREAD

**Issue by comerc** [gajus/slonik#16]
Please add TS definitions.

**Comment by knpwrs** [comment]
Would @gajus be opposed to a gradual conversion of the project to TypeScript? I may some from free time to help with such a task. TypeScript has saved my butt more times than I care to admit.

**Comment by gajus** [comment]
I would have no issue with someone maintaining `@types/slonik`.

Though no plan of converting Slonik codebase to TS.

**Comment by zone117x** [comment]
Converting to typescript is pretty easy since the type annotation syntax is almost the same. Well worth it in my opinion.

**Comment by knpwrs** [comment]
There are some nuances for sure, but it's very doable. I've done it myself. I don't mean to dog-pile on to the issue in any way, but in my experience TypeScript is far superior to Flow. It catches more errors and has more community support.

**Comment by gajus** [comment]
> It catches more errors [..]

Please provide one example and I will change Flow to TS in this library.

**Comment by knpwrs** [comment]
Unfortunately any specific examples I'd be able to provide would be related to React and the way Flow handles prop checking across components, which is not explicitly relevant to this project. Beyond that, we've experienced a lot of friction in the way Flow handles typings for third-party dependencies. With TypeScript you install the appropriate `@types` dependency and you're good to go. Flow has a CLI tool to install third-party typings, typically run at install time. These third party typings don't get package-locked and end up breaking _all the time_. Facebook's official recommended solution is to commit third-party typings to your repository.

Our problems with Flow have been detrimental enough that we've converted a project with more than 1500 JavaScript files over to TypeScript. The end result is a project which is a lot more stable.

I'll definitely post here if anything comes to mind regarding Flow outside of React and third-party dependencies.

**Comment by gajus** [comment]
> With TypeScript you install the appropriate `@types` dependency and you're good to go.

I don't understand this issue then – what is the reason this cannot be a community maintained typing?

What is the reason (by the sound of this issue) to request removal of Flow in favor of TS?

I don't want to make this thread about Flow VS TS. If there is demand for TS, I will support the adoption of TS. It however cannot (without good grounds) be at the cost of removing Flow from this codebase.

To make this conversation more productive: What are the steps that need to be taken to make @types available for TS?

**Comment by knpwrs** [comment]
The steps for getting an `@types` package published are available here: https://github.com/DefinitelyTyped/DefinitelyTyped#create-a-new-package

That said, most newer projects I'm familiar with have starting shipping their own TypeScript typings even if they are written in JavaScript. You just need to make the appropriate `.d.ts` files and add a `typings` or `types` (they're the same) entry to your `package.json`. Case in point: [`immer`](https://github.com/mweststrate/immer). The GitHub breakdown is 88.7% JavaScript and 11.3% TypeScript. The TypeScript percentage is just the `.d.ts` files along with some tests.

**Comment by zone117x** [comment]
@gajus We run into problems with Flow on various types of codebases all the time. It's death by a thousand cuts, not necessarily one major issue. I don't really want to go into a specific issue I've dealt with, but there are countless valid bugs and issues that can be seen here:
https://github.com/facebook/flow/issues
https://github.com/flowtype/flow-bin/issues

The js ecosystem as a whole is moving towards Typescript. Lots of notable projects, including ones maintained by Facebook, are moving from Flow to Typescript. 

In addition, maintaining a separate, manually defined `.d.ts` file causes a lot of issues from human-entry mistakes, minor API / version mismatches, etc.

**Comment by gajus** [comment]
> I don't really want to go into a specific issue I've dealt with, but there are countless valid bugs and issues that can be seen here.

There are 1,117 open bug reports for TypeScript.

https://github.com/Microsoft/TypeScript/labels/Bug

I don't think this argument works in favour of TypeScript.

> The js ecosystem as a whole is moving towards Typescript. Lots of notable projects, including ones maintained by Facebook, are moving from Flow to Typescript.

There is a hype around TS.

If you want to have TS support, I encourage to start by contributing to `@types`. The same types can be leter used to migrate Slonik to TypeScript (should this become necessary).

Whether this library uses TS or Flow, does not define the key features of the library.

**Comment by zone117x** [comment]
I don't use this lib, just responding to an email asking for feedback :)
At a cursory glance over the codebase, it looks faster to convert the whole thing to typescript rather than write a full ts definitions. 
Next time I need to use pg from node, I'll check back in here and potentially do exactly that.

**Comment by gajus** [comment]
Thank you for the feedback @zone117x 

I will leave this conversation open.

If several people come onboard to support help maintaining TS types, I will work with them to support the addition.

**Comment by pocesar** [comment]
feedback from the email I received as well: any JS open source library should *at least* have the TS typings, because the typings can be used for plain ES code as well (notably, VSCode,  which is one of the most popular editors out there). but, converting the library to TS would kill two birds with one stone, provide type-safety for the code and typings out of the box without any "lag" between newly released versions and the actual typings (happens a lot with React, for example, the typings are separated from the main project). Plus, having TS means inline documentation inside the editor, which can drive up adoption significantly. I myself prefer picking libraries and modules that are either created in TS or have typings maintained by their owners.

**Comment by sebald** [comment]
@gajus Would you accept a PR to add typings to this repo? Adding `@†ypes/slonik` is okay, but inconvenient, because it's required to install another package.

**Comment by gajus** [comment]
> @gajus Would you accept a PR that adds TS typings to this repo? Adding `@†ypes/slonik` is okay, but inconvenient, because it's required to install another package.

Migrating TS to Flow and vice-versa is not a problem. There are projects such as https://github.com/bcherny/flow-to-typescript that more or less automate it.

There are currently a lot of features that are outstanding. As I am not deeply familiar with TS and there would be a learning curve, I would rather focus on developing the Slonik and API and migrate (if there is a requirement) to TS once the API becomes stable.

**Comment by sebald** [comment]
@gajus sorry if I didn't express myself well, my suggestion wasn't to migrate anything to TypeScript, but rather to add a `index.d.ts` so it is easier for TS users to consume the library.

I don't know how well [`dts-gen`](https://github.com/Microsoft/dts-gen) works. `material-ui` [decided against using it](https://github.com/mui-org/material-ui/pull/7553)). The current "trend" is to have TS typings inside the lib, this way it is usually easier to have the correct typings (prevents version mismatch and similar).

**Comment by orefalo** [comment]
There are 589 issues on node.js
   https://github.com/nodejs/node/issues

It's a valid argument to stop using node on this project!

Did you get my point ;-)

> > I don't really want to go into a specific issue I've dealt with, but there are countless valid bugs and issues that can be seen here.
> 
> There are 1,117 open bug reports for TypeScript.
> 
> https://github.com/Microsoft/TypeScript/labels/Bug
> 
> I don't think this argument works in favour of TypeScript.
> 
> > The js ecosystem as a whole is moving towards Typescript. Lots of notable projects, including ones maintained by Facebook, are moving from Flow to Typescript.
> 
> There is a hype around TS.
> 
> If you want to have TS support, I encourage to start by contributing to `@types`. The same types can be leter used to migrate Slonik to TypeScript (should this become necessary).
> 
> Whether this library uses TS or Flow, does not define the key features of the library.

**Comment by sebald** [comment]
@orefalo ... I don't think that kind of conversation is very constructive 😕

---

I started to create typings and hope to finish them tomorrow. I'll link the PR here.

But for now everyone can just copy+paste them into their project. They are mostly complete, I hope.

**Typings:**
https://github.com/Reservix/DefinitelyTyped/blob/c8d656e0d19673e684ce34aa8f682e5438cf26d4/types/slonik/index.d.ts

**Comment by orefalo** [comment]
@sebald agreed, deleted

**Comment by sebald** [comment]
PR for DefinitelyTyped: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/33371

**Comment by mkusher** [comment]
so, since @sebald submitted `@types/slonik` package, should this issue be closed? Probably documentation should be updated

**Comment by orefalo** [comment]
It should

**Comment by ben-pr-p** [comment]
Why does `@types/slonik` define `ClientUserConfigurationType` as 
```
export interface ClientUserConfigurationType<T = unknown> {
    /**
     * An array of [Slonik interceptors](https://github.com/gajus/slonik#slonik-interceptors)
     */
    interceptors?: InterceptorType[];
    /**
     * An array of [Slonik type parsers](https://github.com/gajus/slonik#slonik-type-parsers)
     */
    typeParsers?: TypeParserType[];
}
```

shouldn't it be something like ```
type ClientConfigurationType = {|
  +captureStackTrace?: boolean,
  +connectionTimeout?: number,
  +idleTimeout?: number,
  +interceptors?: $ReadOnlyArray<InterceptorType>,
  +maximumPoolSize?: number,
  +minimumPoolSize?: number,
  +typeParsers?: $ReadOnlyArray<TypeParserType>
|};
```

as see in the Slonik readme (https://github.com/gajus/slonik#slonik-usage-api)?

**Comment by gajus** [comment]
> Why does @types/slonik define ClientUserConfigurationType as

Are you sure you are viewing compatible versions of types?

There has been a major version upgrade since.

**Comment by mmkal** [comment]
@gajus FWIW, this sort of issue is part of the reason it'd be nice to have the definitions live in this repo. As things stand the definitions in DefinitelyTyped actually _prevent_ users from using the library correctly. If they lived in the repo the types would move along with the rest of the code, and get updated for breaking changes etc. (which would also make it much easier to get an old version and keep it in sync with the runtime code). Would you be open to accepting a PR moving the types into this repo?

**Comment by gajus** [comment]
> Would you be open to accepting a PR moving the types into this repo?

Not at the moment. I have shared the reasons earlier, but it is primarily surrounded around me not actively using TS anywhere.

Everyone is welcome to contribute to the public typings. If there is going to be a clear champion that keeps those types up to date, then the next step would be to ask/add that person as a contributor to Slonik and start gradual migration to full TS integration.

**Comment by gajus** [comment]
FYI

* https://github.com/gajus/slonik/releases/tag/v16.13.0
* https://github.com/gajus/slonik/releases/tag/v16.12.0

Have been released.

**Comment by hjr3** [comment]
It looks like types for slonik v16.16 landed recently: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/35023

**Comment by Wenzil** [comment]
It looks like the typings are lagging behind the current minor version, 16.19

**Comment by foucist** [comment]
Please rewrite this in Rust.

**Comment by Bessonov** [comment]
Still, to have typings in this repo improves developer experience a lot even without rewrite:
1. No need to install external typings (@typings/slonik)
2. Which versions are compatible (slonik vs. @types/slonik)?
3. Better IDE suppport for JS users out of the box

That's not a hype around TypeScript. TypeScript is so popular because it resolves real problems. But well, I've never understands the rationale behind flow in comparison to TypeScript.
