### ISSUE TITLE
Compile-time type constrains

### ISSUE THREAD

**Issue by mikicho** [gajus/slonik#160]
I got familiar with Slonk from this [article](https://medium.com/@gajus/stop-using-knex-js-and-earn-30-bf410349856c), refreshing I must say :)

I'm using typescript and one the cool things with ORMs that you get a compile-time type check, you can't set number to a column which expects a string for example, is it possible with Slonik?

```
sql`
UPDATE t SET num='dsdsa'; // compile-time/on-bootstrap error
`
```

Thanks,

**Comment by gajus** [comment]
No
