### ISSUE TITLE
How to use copyFromBinary with a stream source?

### ISSUE THREAD

**Issue by av8ta** [gajus/slonik#161]
Hi, thanks for this project, had heaps of fun playing with it today! I see in the docs there's an example of copyFromBinary writing from stdin using a tupleList array; is there a way to pipe a node stream instead of using an array? I'm looking for a performant way to ingest data from a stream :) I got it working using raw pg-copy-streams but I prefer your sql tagged template literal to protect against injection if possible.

**Comment by gajus** [comment]
I would encourage to continue using `pg-copy-streams`. I think that `copyFromBinary` might get removed at some point. It serves a pretty niche use case and it complicates types unnecessarily. Anyone who needs it can just use `pg-copy-streams`.

**Comment by gajus** [comment]
Just to be clear: It is not deprecated at the moment, but I've run into multiple issues related to it, and i tis on my todo list to consider deprecation.

**Comment by av8ta** [comment]
Okay thanks

**Comment by iMoses** [comment]
> I would encourage to continue using `pg-copy-streams`. I think that `copyFromBinary` might get removed at some point. It serves a pretty niche use case and it complicates types unnecessarily. Anyone who needs it can just use `pg-copy-streams`.

@gajus is it possible to use `pg-copy-streams` with `slonik`? 
Anyway to bypass this error? `Query must be constructed using `sql` tagged template literal.`

**Comment by gajus** [comment]
If you are using [`copyFromBinary`](https://github.com/gajus/slonik#slonik-query-methods-copyfrombinary), then `sql` tag will already work.

**Comment by iMoses** [comment]
I'm not, since this method doesn't provide the type of functionality I'm implementing
