### ISSUE TITLE
How do you dynamically create a where clause?

### ISSUE THREAD

**Issue by derekchiang** [gajus/slonik#162]
All existing documentations online seem to refer to the use of `sql.raw`, but the function doesn't exist anymore.  So how do you conditionally create a where clause?  I tried embedding:

```
sql`where key = ${val}`
```

but got an error saying: `error: syntax error at or near "where"`

**Comment by gajus** [comment]
This looks valid. Would need to see the rest of the query to comment.

**Comment by gajus** [comment]
Wrote an article walking through query building using Slonik.

https://contra.com/p/AqZWWoUB-writing-composable-sql-using-java-script

**Comment by james-gardner** [comment]
I used to use the inline sql pattern all the time (as per the blog post) but it doesn't appear that you can just use `sql` this way anymore. Unless I'm doing something foolish:

```
This expression is not callable.
  Type 'SqlTag<Record<PropertyKey, StandardSchemaV1<unknown, unknown>>>' has no call signatures.ts(2349)
```
