### ISSUE TITLE
Case sensitive queries

### ISSUE THREAD

**Issue by TriStarGod** [gajus/slonik#165]
Is there a way to keep the queries case sensitive without having to wrap columns with upper case letters in double quotes? Other query builders (from JavaScript's knex to C#'s Npgsql) keep the case sensitivity enabled.

Thanks for this project. Very useful.

## Expected Behavior

Keep queries case sensitive.
## Current Behavior

Changes text to lower case letters.
## Possible Solution

An option to turn on case sensitive.
## Steps to Reproduce

Any query with upper case letters in column names. If they aren't surrounded by quotes, they are converted or considered lower case.

**Comment by gajus** [comment]
Technically, there probably is a way to do it. What is the use case?

**Comment by TriStarGod** [comment]
Reduction of errors and typing when dealing with columns with camel or pascal naming conventions.
Converting projects that used knex can be further simplified.
Moving from MSSQL to postgres won't involve renaming or converting between column names.

**Comment by TriStarGod** [comment]
@gajus  
Reduction of errors and typing when dealing with columns with camel or pascal naming conventions.
Converting projects that used knex can be further simplified.
Moving from MSSQL to postgres won't involve renaming or converting between column names.

**Comment by gajus** [comment]
This could be written as an interceptor.

https://github.com/gajus/slonik#slonik-interceptors
