### ISSUE TITLE
Accurate Performance Benchmarks Compared to Postgres

### ISSUE THREAD

**Issue by mudgen** [gajus/slonik#166]
I am considering using slonik or [Postgres](https://github.com/porsager/postgres). One thing that would help me make a decision would be accurate performance benchmark comparisons.

The performance benchmark comparisons given here look wrong:
https://github.com/porsager/postgres-benchmarks

**Comment by gajus** [comment]
I believe this has been addressed now.

See this discussion https://github.com/porsager/postgres-benchmarks/issues/2#issuecomment-751516426
