### ISSUE TITLE
Possible EventEmitter memory leak detected with transaction

### ISSUE THREAD

**Issue by hsablonniere** [gajus/slonik#167]
## Context

Node: 13.12.0
Slonik: 22.4.4
Database used (not relevant I think): PG 11

## Simplified test case and behaviour

I tried to create a simplified test case for you.

FYI: My real case is with multiple "UPSERTS".

When I run this:

```js
const COUNT = 10;

await pool.transaction(async (tc) => {

  const allPromises = Array.from(new Array(COUNT))
    .map(() => {
	  return tc.many(sql`SELECT * FROM my_table`);
    });

  await Promise
    .all(allPromises)
    .then(console.log);
});
```

I get these warnings:

```
MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 notice listeners added to [Client]. Use emitter.setMaxListeners() to increase limit
```

If I change `COUNT` to 9 (or less), the warning disappears.

## Expected Behavior

Seems like all my requests work as expected but I guess I also expect slonik to handle my use case without such warnings. Maybe my use case is weird :wink:

## Possible Solution

I'm not sure how to fix it and if you want to fix it, maybe I should trigger my calls another way.

I investigated and it's caused by this `notice` event handler attached 10+ times on the same EventEmitter (connection).

https://github.com/gajus/slonik/blob/master/src/routines/executeQuery.js#L205

I wish you the best, thanks for this awesome projet.

**Comment by extradosages** [comment]
I can confirm that we are also getting this issue.

**Comment by gajus** [comment]
If there is a way to improve this, PR is welcome, though it sounds like expected behavior.

**Comment by hsablonniere** [comment]
@gajus this is great 🎉 thanks very much
