### ISSUE TITLE
Nested JSON sql template throws InvalidInputError on valid JSON

### ISSUE THREAD

**Issue by maricn** [gajus/slonik#172]
I'm using NodeJS v12.14.1, `"typescript": "^3.8.3"` and slonik `    "slonik": "^22.4.3"` (exactly those atm). I can't insert a row containing one JSON field using `sql.json()`. However, if I use `JSON.stringify` instead - it works fine all the way to the database.

## Expected Behavior
Nested sql template should work on valid JSON.

## Current Behavior
```
import { sql } from 'slonik';
...
    const event = {"meta": {"createdAt":1587324971000},"payload":{"context":{"watever":"yes"}}};
    const test = sql.json(event.payload);
    this.logger.debug('Payload JSON (%o): %o', typeof test.value, test);
    this.logger.debug(
      'This test passes: %o',
      sql`INSERT INTO lake.events (test) VALUES ${JSON.stringify(event.payload)})`,
    );
    this.logger.debug(
      'This test fails: %o',
      sql`INSERT INTO lake.events (payload) VALUES (${test})`,
    );
...
```

this throws:
```
JSON payload must be a primitive value or a plain object.. Stack: InvalidInputError: JSON payload must be a primitive value or a plain object.
    at createJsonSqlFragment (/REDACTED/node_modules/slonik/dist/sqlFragmentFactories/createJsonSqlFragment.js:31:11)
    at createSqlTokenSqlFragment (/REDACTED/node_modules/slonik/dist/factories/createSqlTokenSqlFragment.js:22:60)
    at Object.sql (/REDACTED/node_modules/slonik/dist/factories/createSqlTag.js:51:68)
    at EventsService.create (/REDACTED/dist/events/events.service.js:29:52)
 ...
```

## Possible Solution
I think this is related either to not managing token and values properly when passing them through nested templates or there's maybe something with typescript + `isPlainObject` compatibility.

## Steps to Reproduce

See above.
1.
2.
3.
4.

**Comment by maricn** [comment]
Just for the record, for now, I'm using this workaround:
```
sql`INSERT INTO lake.events (payload) VALUES (
  ${JSON.stringify(event.payload || 'null')}
)`
```

Since I'm using TypeScript and strict types, I just need a check for `undefined` and `null` values (number 0 won't pass my strict type check), so it should be as simple as that.

**Comment by gajus** [comment]
This sounds like TypeScript bug.
