### ISSUE TITLE
Performance advice (and is pool.connect / pool.transaction expected to be much slower than pool.any/one/etc?

### ISSUE THREAD

**Issue by tomm** [gajus/slonik#174]
Firstly, I love Slonik. It's now my favourite way to access postgres.

I've been benchmarking slonik to understand why my app, which was doing one pool.connect per HTTP request, was not performing well. Turns out of I just use pool.any/one/etc directly, the performance is much better. I'd like to add some performance advice to the Slonik documentation, but you might have some useful insights first. From the documentation it isn't clear that there should be such a huge performance difference between:

pool.connect(async c => c.any(...))

and

pool.any(...)

my expectation was that using pool.any would not guarantee that the same connection would be used between each call, but otherwise it should behave like pool.connect(async c => c.any(...)).

Here are my results:

```
0.0421 ms per query (pg-native)
0.311 ms per query (Slonik pool.query)
5.379 ms per query (Slonik pool.transaction(query))
4.386 ms per call (slonik pool.connect with no query)
0.1188 ms per query (slonik pool.connect once, then connection.query)
0.1145 ms per query (slonik pool.connect once, then connection.one)
0.1172 ms per query (slonik pool.connect once, then connection.oneFirst)
```

Here is the benchmark code:
```
const slonik = require('slonik');
const Client = require('pg-native');
const ITERS = 10000;

async function raw_query(client) {
  return new Promise((resolve, fail) => {
    client.query('SELECT now() as d', function(err, rows) {
      if (err) fail(err);
      //console.log(rows[0].d);
      resolve(rows[0].d);
    })
  });
}

function test_raw() {
  return new Promise((resolve, fail) => {
    var client = new Client();
    client.connect(async function(err) {
      if (err) {
        fail(err);
        return;
      }

      const t = Date.now();
      for(let i=0; i<ITERS; i++) {
        await raw_query(client);
      }
      const elapsed = Date.now() - t;
      console.log(`${elapsed/ITERS} ms per query (pg-native)`);

      client.end();
      resolve();
    });
  });
}

const pool = slonik.createPool(
  process.env['DATABASE_URL'],
  {
    captureStackTrace: false
  }
);

const slonik_query = async con => con.query(slonik.sql`select now()`);
const slonik_one = async con => con.one(slonik.sql`select now()`);
const slonik_oneFirst = async con => con.oneFirst(slonik.sql`select now()`);

async function test_slonik(name, query) {
  return pool.connect(async con => {
    const t = Date.now();
    for(let i=0; i<ITERS; i++) {
      await query(con);
    }
    const elapsed = Date.now() - t;
    console.log(`${elapsed/ITERS} ms per query (slonik pool.connect once, then connection.${name})`);
  });
}

async function test_slonik_pool_transaction() {
  const t = Date.now();
  for(let i=0; i<1000; i++) {
    await pool.transaction(async t => t.query(slonik.sql`select now()`))
  }
  const elapsed = Date.now() - t;
  console.log(`${elapsed/1000} ms per query (Slonik pool.transaction(query))`);
}

async function test_slonik_pool_query() {
  const t = Date.now();
  for(let i=0; i<1000; i++) {
    await pool.query(slonik.sql`select now()`)
  }
  const elapsed = Date.now() - t;
  console.log(`${elapsed/1000} ms per query (Slonik pool.query)`);
}

async function test_slonik_pool() {
  const t = Date.now();
  for(let i=0; i<1000; i++) {
    await pool.connect(async con => null);
  }
  const elapsed = Date.now() - t;
  console.log(`${elapsed/1000} ms per call (slonik pool.connect with no query)`);
}

async function test_all() {
  await test_raw();
  await test_slonik_pool_query();
  await test_slonik_pool_transaction();
  await test_slonik_pool();
  await test_slonik('query', slonik_query);
  await test_slonik('one', slonik_one);
  await test_slonik('oneFirst', slonik_oneFirst);
  pool.end();

}

test_all();
```

**Comment by tomm** [comment]
Also, the captureStackTrace option in createPool should probably not default to true. It is extremely detrimental to performance

**Comment by tomm** [comment]
with captureStackTrace disabled:
0.0401 ms per query (pg-native)
0.309 ms per query (Slonik pool.query)
5.433 ms per query (Slonik pool.transaction(query))
4.482 ms per call (slonik pool.connect connect)
0.1189 ms per query (slonik pool.query)
0.1139 ms per query (slonik pool.one)
0.1143 ms per query (slonik pool.oneFirst)

with captureStackTrace enabled (default):
0.0423 ms per query (pg-native)
1.472 ms per query (Slonik pool.query)
6.726 ms per query (Slonik pool.transaction(query))
4.424 ms per call (slonik pool.connect with no query)
0.8131 ms per query (slonik pool.connect once, then connection.query)
0.9045 ms per query (slonik pool.connect once, then connection.one)
0.968 ms per query (slonik pool.connect once, then connection.oneFirst)

**Comment by gajus** [comment]
> I've been benchmarking slonik to understand why my app, which was doing one pool.connect per HTTP request, was not performing well. Turns out of I just use pool.any/one/etc directly, the performance is much better. I'd like to add some performance advice to the Slonik documentation, but you might have some useful insights first. From the documentation it isn't clear that there should be such a huge performance difference between:

The difference between implicit connection (such as `pool.query`) vs explicit connection (such as `pool.connect`) is that Slonik never re-uses explicit connections.

That's documented here

https://github.com/gajus/slonik/blob/master/src/factories/createConnection.js#L177

There is not much we can do to improve performance here. 5ms to create a new connection is quite fast already.

**Comment by vjpr** [comment]
@gajus 

I got tripped up by the docs with same problem.

If someone is in a hurry they will look for usage instructions https://github.com/gajus/slonik#usage and the first example is:

```
pool.connect(async (connection) => {
  await connection.query(sql`SELECT 1`);
});
```

So you think that's the way to use it.

But this is really slow.

Maybe there should be a quick start that says to use the pool.

**Comment by gajus** [comment]
These benchmarks are outdated.
