### ISSUE TITLE
Support for arrays of custom types

### ISSUE THREAD

**Issue by Javarome** [gajus/slonik#181]
Cannot specify a custom type name as array member type given the strict signature of `sql.array`.
 
## Expected Behavior
Allow to specify any custom member type for arrays. 

## Current Behavior
Compilation error.

## Possible Solution
Casting the member type string as a `<TypeNameIdentifierType>` gets rid of the compilation error, but would this produce the expected behavior?

## Steps to Reproduce
For the record, I'm testing on a PostgreSQL database.

1. Define a custom type:  `CREATE TYPE values AS ENUM ('value1', 'value2', 'value3')`
2. Define a table with a column of this custom type : `CREATE TABLE my_table (value values)` and populate it.
3. Query that table with a filter on this custom-typed column `SELECT FROM my_table WHERE value = ANY(${sql.array(['value1', 'value3'], 'values')})`
4. You cannot compile line 3 because `'values'` is neither a `TypeNameIdentifierType` (which is a limited set of strings) nor a `SqlTokenType`.

## Logs
Compile error:
```
TS2345: Argument of type '"values"' is not assignable to parameter of type 'ArraySqlTokenType | "bool" | "bytea" | "float4" | "float8" | "int2" | "int4" | "json" | "text" | "timestamptz" | BinarySqlTokenType | ... 4 more ... | UnnestSqlTokenType'.
```

**Comment by gajus** [comment]
> Casting the member type string as a <TypeNameIdentifierType> gets rid of the compilation error, but would this produce the expected behavior?

Yes.

The primary reason for using:

```js
export type TypeNameIdentifierType =
  'bool' |
  'bytea' |
  'float4' |
  'float8' |
  'int2' |
  'int4' |
  'json' |
  'text' |
  'timestamptz';

```

is that it guards against people passing keywords (such as `int`) instead of type names. When you are sure about what you are doing, it is safe to just cast it to whatever you want.

I guess one workaround could be:

```diff
array: (
    values: $ReadOnlyArray<PrimitiveValueExpressionType>,
-    memberType: TypeNameIdentifierType | SqlTokenType
+    memberType: TypeNameIdentifierType | SqlTokenType | {|+typeName: string|}
) => ArraySqlTokenType,
```

**Comment by Javarome** [comment]
Yes or you could add some new well-defined type instantiated by a `sql.type('myCustomType')` that could be accepted as a member type.

**Comment by gajus** [comment]
I like that. I will add it.

**Comment by gajus** [comment]
I misread the original issue. It should be simply:

```js
sql`
SELECT FROM my_table
WHERE value = ANY(${sql.array(['value1', 'value3'], sql`values`)})
`

```
