### ISSUE TITLE
Should sql.array accept `bigint` as the value of `memberType`?

### ISSUE THREAD

**Issue by gavacho** [gajus/slonik#184]
The `memberType` argument of `sql.array` is typed as `TypeNameIdentifierType`:

```ts
export type TypeNameIdentifierType =
  'bool' |
  'bytea' |
  'float4' |
  'float8' |
  'int2' |
  'int4' |
  'json' |
  'text' |
  'timestamptz';
```

Which excludes `bigint`. Is that intentional? It seems like a potential oversight.

**Comment by gajus** [comment]
Does node-postgres even support bigint?

**Comment by gajus** [comment]
Just in case, this would be `int8`, not `bigint`. See [comments about keyword vs type name](https://github.com/gajus/slonik#sqlarray-membertype).

**Comment by gavacho** [comment]
Yeah, we're using bigint columns. Aren't numbers in js 8 bytes?

**Comment by hjr3** [comment]
The ask here is for `TypeNameIdentifierType` to accept `int8`. An 8byte integer is compatible with JS `Number` type. This is not asking for [BigInt in JS](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/BigInt) support.

**Comment by nonara** [comment]
> The ask here is for `TypeNameIdentifierType` to accept `int8`. An 8byte integer is compatible with JS `Number` type. This is not asking for [BigInt in JS](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/BigInt) support.

Correct. I can confirm using `<any>'int8'` works. This can be closed by adding `int8` to the `TypeNameIdentifierType` union
