### ISSUE TITLE
ConnectionError: Connection terminated due to connection timeout

### ISSUE THREAD

**Issue by attilaaf** [gajus/slonik#185]
Unable to connect to remote postgres server with slonik, despite being able to use the exact same credentials directly in `pg`.

## Expected Behavior
Slonik pool.connect() should successfully connect to remote postgres instance.

## Current Behavior
Connects correctly to localhost:5432 postgres:postgres (PostgreSQL 11.2 on x86_64-apple-darwin16.7.0, compiled by Apple LLVM version 8.1.0 (clang-802.0.42), 64-bit)

However it times out when connecting to production postgres 10.6.

The strange thing is that the postgres:// query string is identical and works with `pg` but when used in `slonik` the connection always times out.      I've verified that ports and access to the production database is available.

```
{"method":"","url":"","query":"","ip":"","error":{},"stack":"ConnectionError: Connection terminated due to connection timeout\n    at createConnection (/Users/user/app/node_modules/slonik/dist/factories/createConnection.js:69:15)\n    at process._tickCallback (internal/process/next_tick.js:68:7)","level":"info","message":"Exception","timestamp":"2020-06-21 18:19:44"}
```

## Possible Solution

n/a

## Steps to Reproduce

`Using slonik 22.4.11`

1.
2.
3.
4.

## Logs

Immediately on startup:

```
{"method":"","url":"","query":"","ip":"","error":{},"stack":"ConnectionError: Connection terminated due to connection timeout\n    at createConnection (/Users/user/app/node_modules/slonik/dist/factories/createConnection.js:69:15)\n    at process._tickCallback (internal/process/next_tick.js:68:7)","level":"info","message":"Exception","timestamp":"2020-06-21 18:19:44"}
```

Seems related to: https://github.com/gajus/slonik/issues/173

However I'm using node `v10.16.3` and also tested with node `v12.13.0`. Both exhibit the same problem.

**Comment by attilaaf** [comment]
Problem Solved.

There is a problem with parsing passwords that contain `#` in it.

For example:

 `postgresql://myuser:mypassword!#123@hostname:5432/dbschema` parses into this connection options:

```
{
  user: '',
  password: '',
  port: null,
  host: 'myuser',
  database: ':mypassword!',
  connectionTimeoutMillis: 5000,
  idleTimeoutMillis: 5000,
  max: 10
}
```

**Comment by attilaaf** [comment]
Closing issue. Hopefully this helps someone in the future.

**Comment by gajus** [comment]
The most likely candidate is that you are missing `?ssl=1` flag in your DSN and the service is expecting it.
