### ISSUE TITLE
Question: prepared statements?

### ISSUE THREAD

**Issue by rattrayalex** [gajus/slonik#187]
Hi there,

I'm not yet a user of slonik, but evaluating. It looks awesome! Also a big fan of some of your other work, including flow-runtime back in the day.

I was curious, does slonik automatically make use of prepared statements? You make several references to the benefits of `pg_stat_statements`, which leads me to believe that the entire query is sent every time, but in static syntax, such that it is usually easily looked up in `pg_stat_statements`. 

If this is so, it occurs to me that it may be a further small performance gain (in terms of query parse time and bytes over the wire) to attempt to use prepared statements automatically, by keeping track of which statements have been sent to which connections (if they haven't, give them a name, `prepare` and then `execute` them; if they have, just `execute`).

I think https://github.com/MagicStack/asyncpg has this behavior but I haven't been able to confirm.

I assume the performance gain of something like this would be relatively minor, and I'm not sure how big the risks would be, but I thought I'd ask if it was worth doing, or if this was already the behavior.

Thanks!
Alex

**Comment by gajus** [comment]
https://node-postgres.com/features/queries#Parameterized%20query

node-postgres, on top of which this library is built, already supports prepared statements.

Note the warning though:

> Be careful not to fall into the trap of premature optimization. Most of your queries will likely not benefit much, if at all, from using prepared statements. This is a somewhat "power user" feature of PostgreSQL that is best used when you know how to use it - namely with very complex queries with lots of joins and advanced operations like union and switch statements. I rarely use this feature in my own apps unless writing complex aggregate queries for reports and I know the reports are going to be executed very frequently.

I would be curious to measure what sort of improvement we are talking before attempting to implement it.

**Comment by rattrayalex** [comment]
Thanks, makes sense! If I ever give it a try I'll let you know what the perf implications are like for typical workloads. Otherwise let's assume that warning is correct and the feature wouldn't make sense as part of a default implementation.
Appreciate you taking a look!
