### ISSUE TITLE
Proposal: `sql.ands`, `sql.commas`, `sql.ors` helpers for query building

### ISSUE THREAD

**Issue by rattrayalex** [gajus/slonik#188]
Hi again,

Disclaimer: I'm not yet a user of slonik, so this may not be germane. However, it may also be useful to get the perspective of someone choosing a ~sql-first approach like slonik vs. an ORM like TypeORM or a query builder like knex.

As I was reading through [your post](https://dev.to/gajus/dynamically-generating-sql-queries-using-node-js-2c1g) on dynamic query building, I came across one of the sections most interesting to me, and most basic – dynamically adding multiple sql `and` clauses to a `where`, or dynamically changing which columns I want in my `select`.

In your [Stop using Knex](https://medium.com/@gajus/stop-using-knex-js-and-earn-30-bf410349856c) piece, you even say that cases like these sometimes drive you back to query builders like knex. But I love the idea of slonik and I wonder if there's a way to make it more convenient for these cases, and still safe.

Simple convenience wrappers might help, to be used like so (analogous to [your example](https://dev.to/gajus/dynamically-generating-sql-queries-using-node-js-2c1g#query-with-dynamic-where-clause-members)):

```ts
sql.ands = (...args) => {
  return sql.join(args.filter((x) => x != null).concat(sql`TRUE`), sql`AND`);
};
sql.ors = (...args) => {
  return sql.join(args.filter((x) => x != null).concat(sql`FALSE`), sql`OR`);
};
sql.commas = (...args) => {
  return sql.join(args.filter((x) => x != null), sql`, `);
};

commonCountryColumns = [
  sql`country.code_alpha_2 country_code`
  sql`country.name country_name`
]

const findCinemas = (root, parameters, context) => {
  const query = parameters?.input?.query;
  return context.pool.any(sql`
      SELECT ${sql.commas(
        sql`cinema.id`,
        sql`cinema.nid`,
        sql`cinema.name`,
        ...commonCountryColumns
      )}
      FROM cinema
      INNER JOIN country ON country.id = cinema.country_id
      WHERE ${sql.ands(
        query.countryId && sql`country.id = ${query.countryId}`,
        query.nid && sql`cinema.nid % ${query.nid}`,
        query.name && sql`cinema.name % ${query.name}`
      )}
    `);
};
```

This would not only alleviate my concern about the convenience of query building, but also some of my biggest annoyances of writing raw SQL – dealing with commas and `AND`s as I reorder, remove, and add columns to my `select` clauses and conditions to my `where` clauses.

Note that I did notice https://github.com/gajus/slonik/commit/910177db4e8bdb8f2d2b4a9e82bd017044a6801d and agree wholeheartedly with its spirit – in my experience, the small purpose-specific helpers like `booleanExpressions` do more harm than good, while little conveniences for extremely common use-cases around powerful, exposed primitives helps developer productivity immensely.

Thoughts? Would this be helpful to you in your applications? Do you already have helpers like this?=

Thanks,
Alex

PS – in any case, it may be worth updating your article on query building, since it still uses the old `booleanExpressions` functions.

**Comment by gajus** [comment]
Hey,

I appreciate a thoughtful post, but I won't be accepting a PR for this, and you've already identified the reason (https://github.com/gajus/slonik/commit/910177db4e8bdb8f2d2b4a9e82bd017044a6801d).

I would suggest to either release a utilities library that includes helpers such as the ones that you are proposing, or contributing to one of the existing utilities libraries, e.g. https://github.com/gajus/slonik-utilities

In general, this sort of abstraction is too minor even for a utility.

The difference between `sql.join([], sql`AND`)` and `sql.ands([])` is just a few characters at a cost of new API.

**Comment by rattrayalex** [comment]
Fair enough! Easy for me to wrap myself.

It may be worth mentioning `slonik-utilities` in the `slonik` readme, btw, I hadn't seen that before! Nice to have upsert helpers in particular.
