### ISSUE TITLE
Slonik QueryStream does not apply type parsers

### ISSUE THREAD

**Issue by aravindanve** [gajus/slonik#189]
I'm using the `slonik.stream()` API and it does not seem to apply the registered type parsers. Is this intentional?

**Comment by gajus** [comment]
Sounds more like a bug. However, should be a simple fix.

**Comment by gajus** [comment]
Are you available to debug and contribute a fix/ test?

**Comment by aravindanve** [comment]
Sure, I'll do it over the weekend

**Comment by aravindanve** [comment]
It appears to be a problem with the underlying `pg` and `pg-cursor` libraries. The connection executing the cursor does not seem to apply the types configured on the connection instance, only the ones explicitly configured on the cursor instance. 

https://github.com/gajus/slonik/blob/042669dab03421e18e8dda270c92a4089cbdedd7/src/connectionMethods/stream.js#L32

Ideally this `finalConnection` here should apply the configured types to the`query` (Cursor) passed to `.query()`.

Anyways, I've sent a PR , Travis CI build failed with `database "slonik_test" is being accessed by other users`. Tests are passing on my local machine, so I think if you re-run the job, it should pass

**Comment by gajus** [comment]
Thank you
