### ISSUE TITLE
Rewrite in TypeScript

### ISSUE THREAD

**Issue by gajus** [gajus/slonik#195]
I will be tackling this in the coming weeks.

Bear in mind that my familiarity with TS is limited. Therefore, expect a few rough iterations.

Anyone who is well versed in TS is more than welcome to jump in an lead.

This will be included in the next major release.

**Comment by gSarciotto** [comment]
Just learned about this module, I have some experience with TS, would be glad to help

**Comment by julianbei** [comment]
You might also be interested in: https://github.com/gcanti/fp-ts
This could help to enforce really strong typings with: https://github.com/gcanti/io-ts

The first steps are hard to do. But after a while, I cant get it out of my toolbelt anymore.
Cool thing though is, that you can expose a non `fp-ts` API but have a lot of compile time checks in place already. Reduces the Error window from typescript alone quite a bit.

- Easy to test
- Hard to do something stupid
- Hard to learn, easy to master (after learning it initially wich is a period of pure pain)

If you need any support, please ping me. Always glad to help.

**Comment by mmkal** [comment]
@gajus I'm a maintainer of the [@types/slonik](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/slonik) package, a repo of [slonik tool](https://github.com/mmkal/slonik-tools) and a [typescript type test/validation library](https://github.com/mmkal/ts/tree/main/packages/expect-type) so I can help!

Happy to start a branch/draft PR if you don't have one already?

**Comment by gajus** [comment]
> Happy to start a branch/draft PR if you don't have one already?

Yes please!
