### ISSUE TITLE
transactionQueries is not iterable

### ISSUE THREAD

**Issue by dmpvost** [gajus/slonik#196]
I got this issue often, when my cron run some tasks.
What this error mean? What can I do?

## Expected Behavior

No error

## Current Behavior

> [2020-08-18T09:25:04.046Z] ERROR (50) (@Cron) (#01EG0E5NHKBBWS6GP9TRX4C88Z:GET:/cron/task): InternalQuery / **transactionQueries is not iterable**
SLONIK:
QUERY:
  sql:    SELECT * FROM process_matchator( 5::INTEGER , $1::UUID , $2::INTEGER) as query;
  type:   SLONIK_TOKEN_SQL
  values:
    - null
    - 7

## Steps to Reproduce

I don't know how to reproduce it..

**Comment by gajus** [comment]
This sounds like it could be a transaction failing and Slonik not being able to re-attempt the transaction because (for some reason) `transactionQueries` is not set.
