### ISSUE TITLE
Why does casting an array value as citext in the query returns the array as string?

### ISSUE THREAD

**Issue by escobar5** [gajus/slonik#197]
Hi, I'm having some issue with a query, I don't really know if it's a bug or something I'm doing incorrectly.

I have this query:

```
const tags = await db.any<{id:number, name: string, values: string[]}>(
      sql`select id, name, (SELECT ARRAY(SELECT DISTINCT value FROM survey_config_tags where survey_tag_id = s.id)) as values from survey_tags s where survey_id = ${surveyId}`);
```

and it works, `tags.values` is a string array, but if I cast `value` as `citext` then it returns me the json as string:

```
const tags = await db.any<{id:number, name: string, values: string[]}>(
      sql`select id, name, (SELECT ARRAY(SELECT DISTINCT value::citext FROM survey_config_tags where survey_tag_id = s.id)) as values from survey_tags s where survey_id = ${surveyId}`);
```

## Expected Behavior
It should also return an array

## Current Behavior
It returns the json array as a string

I'm using the current latest version of slonik

**Comment by gajus** [comment]
`citext` is a contrib extension, as such, it is not included in the type preset.

You will need to provide your own type parser. See:

* https://github.com/brianc/node-postgres/issues/1620
* https://github.com/gajus/slonik#slonik-type-parsers
