### ISSUE TITLE
Create index named after a variable

### ISSUE THREAD

**Issue by silently** [gajus/slonik#200]
Hello,

I am trying to achieve:
```
CREATE INDEX my_index ON my_table (my_column);
```

Using the following:
```
const index = "my_index";
sql`CREATE INDEX ${index} ON my_table (my_column);`
```

But I get an "error: syntax error at or near "$1" from pg-protocol.

I also tried with sql.identifier

More generally, I would like to script migrations with slonik, and I find not so easy to do these typical operations:

- CREATE/DROP/ALTER TABLE (ok with sql.identifier, why not allowing ${table_name} directly?)
- CREATE/DROP/ALTER INDEX
- INSERT INTO (ok with sql.identifier)

...With **variable** table and index names. Currently I am using both slonik (for application queries) and node-posgres (for migration) connections. Using slonik only would be easier!

Thanks!

**Comment by gajus** [comment]
```js
sql`CREATE INDEX ${sql.identifier(['index_name'])} ON my_table (my_column);`
```
