### ISSUE TITLE
Alternative API proposal

### ISSUE THREAD

**Issue by sticker221** [gajus/slonik#205]
Ive been trying out Slonik and its good, though I think the API would make more sense if methods were called after the sql query
```js
const getUserById => (pool, id) => pool.query(sql`SELECT * FROM users WHERE id = ${id}`)

// I can either use it in cases I want it throw when no entity is found
getUserById(pool, 5).one()

// or when returning null is acceptable
getUserById(pool, 5).maybeOne()
```

**Comment by gajus** [comment]
Something like what you are suggested can be implemented as a utility. No plans in changing Slonik API.
