### ISSUE TITLE
Conditionally adding columns & values for insert operations

### ISSUE THREAD

**Issue by dmtomczyk** [gajus/slonik#208]
## Expected Behavior

I am unclear on how I would achieve something like the following with slonik.

Note: Basically, I'm looking to build the SQL string based on what input the user gives me, rather than creating 30 different static strings and using 1 of them based on the columns the user inputs. There will be roughly 400-500 endpoints, each with anywhere from 3-20+ columns that are almost entirely optionalfor the user.

```sql
var upsertInfoString = `insert into table_test
        (id
            ${req.body.comments !== undefined && req.body.comments !== null
                ? ', comments'
                : ''}
            )
        values
            (${req.body.id}
            ${req.body.comments !== undefined && req.body.comments !== null
                ? `, ${req.body.comments}`
                : ''}
            )
        on conflict (id)
            do update
            set id=${req.body.id}
                ${req.body.comments !== undefined && req.body.comments !== null
                    ? `, comments=${req.body.comments}`
                    : ''}
                ;`;
```

The above query was quickly written, so excuse typos, etc. but it should evaluate to 1 of 2 cases listed below.

**Case 1 (req.body.comments has a proper value)**
```sql
var upsertInfoString = `insert into table_test
        (id, comments)
        values (${req.body.id}, ${req.body.comments})
        on conflict (id)
            do update
            set id=${req.body.id},
                  comments=${req.body.comments};
```

**Case 2 (req.body.comments is undefined)**
```sql
var upsertInfoString = `insert into table_test
        (id)
        values (${req.body.id})
        on conflict (id)
            do update
            set id=${req.body.id};
```

## Current Behavior

Currently, slonik throws an exception of type _InvalidInputError_ and a message stating _"SQL tag cannot be bound an undefined value."_

StackTrace:
_at sql (../../node_modules/slonik/dist/factories
at ../../sample.routes.js
at processTicksAndRejections (internal/process/task_queues.js(97:5)_

**Comment by dmtomczyk** [comment]
Bug label was added automatically, but I'm not sure this is one. I'm either unclear on how to accomplish this with slonik, or it's not a feature in slonik.

Please advise, 
Thank you.

**Comment by gajus** [comment]
This topic is covered in detail throughout the documentation.

**Comment by dmtomczyk** [comment]
@gajus Would you mind pointing me to an example of this? I've not been able to notice anything in the documentation that I browsed before making this issue. Perhaps it's hiding somewhere I can't see 😞

**Comment by gajus** [comment]
The API has since changed, but this is a pretty easy walk-through.

https://dev.to/gajus/dynamically-generating-sql-queries-using-node-js-2c1g

Most of what you want to achieve can be done with a combination of [`sql.join`](https://github.com/gajus/slonik#slonik-query-building-sql-join) and [`sql.identifier`](https://github.com/gajus/slonik#sqlidentifier)

**Comment by dmtomczyk** [comment]
@gajus Thank you!

**Comment by dmtomczyk** [comment]
It took an 'aha' moment with slonik, but I eventually got what I needed.

For others like me who couldn't seem to read between the lines, or just for my own reference in the future, I've gone with something like the following:

```csharp
// Declare list of columns to include in SQL queries that will always be required.
var userColumnsList =
        [sql.identifier`id`,
        sql.identifier`username`,
        sql.identifier`user_id`];

// Conditionally add identifiers and values to respective lists.
if (req.body.email !== undefined)
{
    userColumnsList.push(sql.identifier`email`);
    userValuesList.push(`${req.body.email}`);
}

// Form the SQL Query for an UPDATE operation.
var updateUserQuery = 
    sql`UPDATE users 
        SET ${
            sql.join(userColumnsList.map(
                (colName) => 
                     sql`${colName} = ${userValuesList[userColumnsList.indexOf(colName)]}`
                 ), sql`,`
              )
         }
         WHERE id=${finalUUID}`;

// Execute query, handle response, etc.
```

Thanks for the library @gajus !

**Comment by gajus** [comment]
@dmtomczyk For update specifically, you can use https://github.com/gajus/slonik-utilities#slonik-utilities-usage-update

**Comment by dmtomczyk** [comment]
@gajus Oh neat, I'll have to look into that. I added a sample of an upsert operation for the heck of it. Thanks again
