### ISSUE TITLE
Better connection mocking

### ISSUE THREAD

**Issue by oguimbal** [gajus/slonik#220]
Hi,

I recently relased [pg-mem](https://www.npmjs.com/package/pg-mem)  which is an in-memory emulation of a postgres db (I wrote an article about it [here](https://dev.to/oguimbal/how-to-really-unit-test-code-that-uses-a-db-3gmg))

It can be really useful when writing unit tests, and it happens to be [quite easy to integrate](https://github.com/oguimbal/pg-mem/blob/3a447175008981e5bbeb05068a8e68c75c3f4eb4/src/adapters.ts#L147-L157) with `createMockQueryResult`.

As you can see, I added a helper in my lib to create a pool instance bound to an in-memory db: [you can see it in action here](https://codesandbox.io/s/gallant-hypatia-htx6q?file=/src/index.js:417-418)

This lib is quite new, and I was wondering if you might mention it somewhere in your documentation. If it can help some as much as it has helped us, it is worth spreading :)

nb: (very few) unit tests of this integration can be found [here](https://github.com/oguimbal/pg-mem/blob/master/src/tests/slonik.spec.ts)

**Comment by gajus** [comment]
Better mocking can now be implemented by overriding `pgClient` as needed

https://github.com/gajus/slonik/issues/240
