### ISSUE TITLE
Type issue: SerializableValueType is too restrictive when it comes to sql.json

### ISSUE THREAD

**Issue by adevine** [gajus/slonik#222]
Just upgraded to latest version of slonik, and many of my calls to sql.json are now reporting type errors of `Type 'MyCustomType' is not assignable to type '{ [key: string]: SerializableValueType; }'`. The issue is that if MyCustomType is an object type that contains any optional fields, then the TS type of those fields will include undefined, which SerializableValueType

## Expected Behavior

If I have a type defined as something like `type MyCustomType = { foo: string; bar?: string };` then a should be able to use an instance of that type in a call to sql.json

## Current Behavior

Error message as described above

## Possible Solution

Type definition for SerializableValueType should be the following I believe (see [key: string]: SerializableValueType **| undefined**):
```
export declare type SerializableValueType = string | number | boolean | null | {
    [key: string]: SerializableValueType | undefined;
} | ReadonlyArray<SerializableValueType>;
```

## Steps to Reproduce

1. See comments above

## Logs

```
error TS2345: Argument of type 'MyCustomType' is not assignable to parameter of type 'SerializableValueType'.
  Type 'MyCustomType' is not assignable to type '{ [key: string]: SerializableValueType; }'.
    Property 'm' is incompatible with index signature.
      Type 'string | undefined' is not assignable to type 'SerializableValueType'.
        Type 'undefined' is not assignable to type 'SerializableValueType'.
```

**Comment by gajus** [comment]
Sounds reasonable to me.

@mmkal Is this a good way to go?

**Comment by mmkal** [comment]
Yes, I think so. Happy to help review a PR if you'd be willing to make one @adevine ?

**Comment by adevine** [comment]
Thanks @mmkal , I'll do that, it's a simple one line change. I'm not entirely sure what the best way to run tests for this is, in any case I'll put the details in my PR. Thanks!

**Comment by mmkal** [comment]
@adevine there are existing `sql.json` type tests here: https://github.com/gajus/slonik/blob/7fe5c36e2e661a03df3695839359324070d15b1d/test/dts.ts#L284-L308

**Comment by albertreed** [comment]
@gajus This change was reverted in a commit with the comment "fix: update roarr", was this perhaps by accident?

https://github.com/gajus/slonik/commit/fcfa0fe97f2265c1df61c8578f22d77e8c393b0c

**Comment by gajus** [comment]
Possible

**Comment by gajus** [comment]
The problem with allowing `undefined` value is that it makes some scenarios ambiguous, e.g.

```ts
sql.fragment`SELECT ${sql.json(undefined)}`
```

What would you expect to be the result?

In JavaScript,

```ts
> JSON.stringify(undefined)
< undefined
```

but that does not make a ton of sense in the context of values passed to PostgreSQL.

**Comment by gajus** [comment]
One way to handle this would be to throw an error if `sql.json` result is `undefined`.

**Comment by gajus** [comment]
Allowing `undefined`. If this breaks something, will do be a better job documenting why it is not allowed, as we now have gone back and forth several times.
