### ISSUE TITLE
How to better describe the file with queries

### ISSUE THREAD

**Issue by makoven** [gajus/slonik#226]
Hello. I'm trying to describe queries in a separate file for later use (in the context of connections or transactions). It turns out a little weird. Maybe there is a better way?

```typescript
import {
  sql,
  DatabasePoolConnectionType as Conn,
  DatabaseTransactionConnectionType as Tran
} from "slonik";

async function selectNumbers(conn: Conn | Tran) {
  return conn.many<Record<string, number>>(sql`SELECT * FROM measurements`);
}
```

```typescript
import { createPool } from "слоник";
const pool = createPool('');

// Using query with pool connection
pool.connect(conn => {
  return selectNumbers(conn)
});

// Using query with transaction connection
pool.transaction(tran => {
  return selectNumbers(tran);
})
```

**Comment by gajus** [comment]
You may use `CommonQueryMethodsType` instead.

**Comment by makoven** [comment]
> You may use `CommonQueryMethodsType` instead.

It is defined in the types.ts, but not exported. It turns out that no one at all practices putting queries into a separate files? How do you generally reuse quesies?
