### ISSUE TITLE
Include message from originalError message in wrapped error

### ISSUE THREAD

**Issue by mmkal** [gajus/slonik#233]
Related: #50

## Expected Behavior
Postgres error messages are surfaced to slonik errors and easily readable.

## Current Behavior
When errors are thrown (unique constraints, non-null etc.), the top line of the error message consists only of the generic message

This makes problems harder to track down/debug. The information is there, but when using tools that show only error messages (rather than full call stacks with fully serialised error objects), all you see is something like `Query violates a unique integrity constraint`.

Tools that work this way:
- sentry - it can show extra details as tags, but the error message is usually bubbled up to an issue title. This affects grouping. Currently, errors of this type all get grouped together, even for different columns.
- some command line tools. To keep the UI clean, some of these show the error message only, so it's necessary to attach a debugger, or add additional log statements and re-run queries to get at the `originalError` value. It's sometimes not possible to do this, and can be a frustrating task for intermittent errors.
- lots of organisation-specific error loggers/reporters. Ideally they'd always capture all the relevant information, but when they don't, it'd still be very useful to be able to see what's wrong at a glance.

In general, it's super-valuable for slonik to be mapping from error codes to error "types". But the postgres team has presumably spent a lot of time designing the error messages so they're clear and human readable, so the messages like `Query violates a unique integrity constraint` aren't helping much. So it'd probably even be ok to use `originalError.message` directly too.

## Possible Solution
The `SlonikError` class could have something like a `getMessage` method, which `originalError` is passed into, as well as an additional string. Then `this.message = ....` could become `this.message = this.getMessage(originalError, 'Query violates a unique integrity constraint')`.

## Steps to Reproduce

```js
let slonik = createPool(...)
await slonik.query(sql`create table t1(id int unique, name text unique`)
await slonik.query(sql`insert into t1(1, 'a')`)
await slonik.query(sql`insert into t1(2, 'a')`).catch(e => console.log(e.message))
```

I'd be happy to take a stab at a small refactor if you'd be open to it?

**Comment by gajus** [comment]
Just adding `originalError` should be enough.

**Comment by mmkal** [comment]
@gajus not 100% sure what you mean, but I opened a PR (#234). Might be easier to comment there if you had something specific in mind.
