### ISSUE TITLE
Make `+` operator concatenate sql templates

### ISSUE THREAD

**Issue by NicolasCaous** [gajus/slonik#236]
Hi, I want to know if it is possible to add as an operator of SQL templates the following operation:

```javascript
joinSqlTemplates = (array, separator = sql``) => {
  return sql`${sql.join(array, separator)}`;
};
```

such that we can concatenate sql templates like so:

```javascript
sql`a` + sql`b` // -> sql`ab`
```
Or like this:

```javascript
[sql`a`, sql`b`].join(sql``) // -> sql`ab`
[sql`a`, sql`b`].join(sql`, `) // -> sql`a, b`
```
Do you think it is possible for this behavior to be the default behavior of the `+` operator?

**Comment by NicolasCaous** [comment]
I have just realized that 
```javascript
sql`${sql.join([sql`a`, sql`b`], sql`, `)}`
```
Does exacly what my helpfer function does. But still, can this be the `+` operator?

**Comment by adevine** [comment]
@NicolasCaous this is not possible as Javascript does not allow operator overloading (there are some pretty gross hacks I've seen using valueOf and toString but I would definitely recommend against that), nor do I really think this is desirable. Note that it is already possible to nest sql tagged templates, i.e.

``sql`${sql`a`},${sql`b`}` `` is the same as ``sql`a,b` ``
