### ISSUE TITLE
Expose client configuration on pool instance

### ISSUE THREAD

**Issue by mmkal** [gajus/slonik#242]
It'd be good to be able to get the configuration from an existing pool instance.

Example

```js
import {createPool} from 'slonik'

const myPool = createPool('...')

myPool.configuration.typeParsers // list of type parsers
```

I'm working on a new iteration of [@slonik/typegen](https://npmjs.com/package/@slonik/typegen), which generates typescript types from slonik queries. There's a need to understand what kind of `typeParsers` (and maybe even interceptors) have been provided to the pool, since they transform the type. For example, if there's a parser which transforms `timestamptz` fields to `Date`, the codegen tool needs to know about it so that they don't output the wrong type.

Right now users have to manually specify type mappings to match up with runtime type parsers, but that's error prone and awkward. If it were possible to look at the configuration for a given pool, users could just pass in a pool - which could then be used for both querying and to calculate type mappings.

I could ask users to pass in `typeParsers` directly, but since the pool instance will need to be passed in anyway, it seems bad to require specifying the same list of custom parsers twice:

```js
setupTypeGen({
  typeParsers: [...customParsers],
  pool: createPool('...', {
    typeParsers: [...customParsers],
  })
})
```

Plus, there are other fields on the configuration object that might be needed.

I'd be happy to open a PR exposing the configuration if it'd be welcome.

**Comment by gajus** [comment]
Sounds reasonable.

I would just limit the scope of what can be retrieved to only those things that are needed, i.e. `pool.getTypeParsers()`, etc.

**Comment by mmkal** [comment]
:+1: I'll open a PR. I'll see how it looks but I'd have thought it'd be useful to just expose the client configuration since it's hard to predict exactly what's needed.

One other use case I can think of where the whole config would be useful: creating a new pool from an existing one, something like:

```js
// db.test.ts

import {pool} from '../src'
import {sql} from 'slonik'

test('test pool', async () => {
  const testPool = createPool({
      ...pool.configuration,
          idleTimeout: 1,
            })
  const result = await testPool.query(sql`
      select 123
        `)
  expect(results).toMatchInlineSnapshot()
  })
```

**Comment by gajus** [comment]
The bigger the scope you expose, the bigger the surface for what can be a cause for a breaking change. Thus the approach of exposing only what is needed.
