### ISSUE TITLE
Refactor of TaggedTemplateTypeLiteral was a breaking change

### ISSUE THREAD

**Issue by rintaun** [gajus/slonik#246]
## Expected Behavior

I was previously able to pass a generic return type to `sql`, e.g.

```typescript
const query = sql<Users>`SELECT * FROM users`
```

In this case, `query` would be `TaggedTemplateLiteralInvocationType<Users>`, essentially promising that it would return a `Users` value.

This allowed other methods like the query methods to infer the type, so this:

```typescript
return await connection.one(query) // the query from above
```

would be typed to `Users` automatically

## Current Behavior

In v23.5.0 (3622da77588a0ee2179e37c8633e595beac1c242), the `TaggedTemplateLiteralInvocationType` and `SqlTaggedTemplateType` types were simplified which completely removes that ability and breaks type inference.

This is inconvenient because it breaks all generic querying methods and forces callers of the actual query method (`one` et al) to know the type of the expected result, so queries cannot be easily passed around.

## Possible Solution

Return the generic types :)

## Steps to Reproduce

```typescript
interface Row {
  col: number
}

pool = createPool(/* ... */)

function getRow(): Row {
  const query = sql<Row>`SELECT 1 as "col"`
  return await pool.one(query) // should be `Row`, but is `Record<string, PrimitiveValueExpressionType>`
}
```

## Logs

N/A

**Comment by rintaun** [comment]
This is the line that allowed the type inference to function:

https://github.com/gajus/slonik/blob/25468a27f578c3d926a0e1197437cf48dae1ab29/src/utilities/mapTaggedTemplateLiteralInvocation.ts#L11

**Comment by gajus** [comment]
I see. My bad. As nothing broke in the test cases / linting, I couldn't see how this was used.

It should be pretty simple to bring it back.

**Comment by gajus** [comment]
It looks like the problem was that the `npm run lint` was run in `after_success`. This allowed the release to go out, even though `test/types.ts` broke.

https://github.com/gajus/slonik/commit/c9f225303f1c1ce843747702dd86a937082f9bca

**Comment by rintaun** [comment]
Thanks for the quick response! ❤️
