### ISSUE TITLE
'Result cursors do not work with the native driver. Use JavaScript driver.' error when using streams

### ISSUE THREAD

**Issue by ShDDaniel** [gajus/slonik#247]
Node 15.0.1
Slonik 23.3.1

Hi
I've stumbled upon this error a couple of times while using streams. Switching to an earlier version of node, 14.12.0, (using nvm) seem to be fixing the issue.

**Comment by gajus** [comment]
This should not longer be an issue as of https://github.com/gajus/slonik#slonik-usage-using-native-libpq-bindings
