### ISSUE TITLE
Connection error handling inside transaction

### ISSUE THREAD

**Issue by skarbovskiy** [gajus/slonik#250]
Following code produce unhandled rejection 
```
const db = createPool(url, poolConfig);
db.transaction(async (trx) => {
	await Promise.all([Promise.reject(new Error('error'), trx.query(sql`SELECT * from products`))]);
}).catch(console.log)
```
Original "error" get catched and unhandled rejection "Client was closed and is not queryable" is fired. 
Is there any way to overcome this or all promises inside transaction must follow in series?

**Comment by gajus** [comment]
I am unable to replicate the issue that you are describing.

```js
test.only('ensure that there are no unhandled rejections', async (t) => {
  const pool = createPool(t.context.dsn);

  await t.throwsAsync(pool.transaction(async (transaction) => {
    await Promise.all([
      Promise.reject(new Error()),
      transaction.query(sql`SELECT * from person`),
    ]);
  }));
});

```

Please submit a failing integration test for this to be considered.

**Comment by skarbovskiy** [comment]
okey, case is a bit more tricky, didnt reproduce it correctly.
try
```
test.only('ensure that there are no unhandled rejections', async (t) => {
  const pool = createPool(t.context.dsn);

  await t.throwsAsync(pool.transaction(async (transaction) => {
    await Promise.all([
      transaction.query(sql`SELECT * from person`),
      (() => {
        throw new Error();
      })()
    ]);
  }));
});
```
throwing synchronous error inside promise leads to unhandled rejection. If this is done without transaction, with general connection, everything seems to work fine

**Comment by skarbovskiy** [comment]
@gajus any thoughts?

**Comment by gajus** [comment]
Slonik is behaving here as it should. Nothing to fix.
