### ISSUE TITLE
How to create dynamic enum types?

### ISSUE THREAD

**Issue by ademilsonfp** [gajus/slonik#251]
I want to create a custom enum type with values based on JS constants, something like:

```
sql`
CREATE TYPE MYENUM AS ENUM (
  ${CONST_VALUE_A},
  ${CONST_VALUE_B},
  ${CONST_VALUE_C}
)
`;
```

I'm using TypeScript and tried to achieve this with `sql.raw`, but notice that this type definition is missing.

What is the best approach to achieve this?

**Comment by gajus** [comment]
```js
await connection.query(sql`
  CREATE TYPE MYENUM AS ENUM ( ${sql.join([CONST_VALUE_A, CONST_VALUE_B, CONST_VALUE_C], sql`, `)} )
`);

```

**Comment by ademilsonfp** [comment]
Thank you for the answer, but it doesn't worked. It seems that PostgreSQL don't accept template values in this case, causing the following error:

```error: syntax error at or near "$1"```

I also tried `sql.identifier` too, but it throwed another syntax error because of the generated delimiting quotes.

**Comment by gajus** [comment]
Right. I forgot about that.

In that case you do need to use `raw`.

Now that it is a separate package: https://github.com/gajus/slonik-sql-tag-raw
