### ISSUE TITLE
sql`${sql.join(sql.binary(…))}` results in unexpected value expression.

### ISSUE THREAD

**Issue by issa-tseng** [gajus/slonik#253]
maybe this isn't a bug and i've misunderstood how something to be used. and either way i've worked around it so this is not pressing.

but while this works:
```
sql`${sql.binary(Buffer.from('test'))}`
```

and even this:
```
sql.join([sql.binary(Buffer.from('test'))], sql``)
```

this results in `Unexpected value expression`:
```
sql`${sql.join([sql.binary(Buffer.from('test'))], sql``)}`
```

**Comment by issa-tseng** [comment]
(curiously, i've finished getting everything to pass tests in slonik with my local patch, and for whatever reason the tests now take ~63s to run now under slonik; it was ~36s under knex. gonna take a look to see whyish, but i was wondering if this is sort of a known delta.)

**Comment by gajus** [comment]
Seems like may be a bug.
