### ISSUE TITLE
tuple to be locked was already moved to another partition due to concurrent update error handling

### ISSUE THREAD

**Issue by skarbovskiy** [gajus/slonik#258]
I want to handle https://github.com/postgres/postgres/commit/f16241bef7cc271bff60e23de2f827a10e50dde8 error in similar way to https://github.com/gajus/slonik/blob/6bafb002e2c7fff468b4baeeb7ae57d8c2dd86bd/src/routines/executeQuery.ts#L240-L250
Can I use existing `CheckIntegrityConstraintViolationError` or create a new one?
And as far as i see this error does not have specific code, so handling will be based on "message includes" logic. No problem with it?

**Comment by gajus** [comment]
I don't understand what is the question here – How to handle the error?

It seems like you will need to handle it using message includes logic.
