### ISSUE TITLE
Build failing in new ts projects after slonik dependency added

### ISSUE THREAD

**Issue by spruce-bruce** [gajus/slonik#259]
Build fails in a new ts project due to slonik dependency.

## Current Behavior
Here's the error output from the build:

```
$ yarn build
yarn run v1.22.4
$ rimraf dist
$ nest build
node_modules/slonik/dist/src/utilities/isPrimitiveValueExpression.d.ts:1:86 - error TS2307: Cannot find module 'roarr/dist/src/types' or its corresponding type declarations.

1 export declare const isPrimitiveValueExpression: (maybe: unknown) => maybe is import("roarr/dist/src/types").SprintfArgument;
                                                                                       ~~~~~~~~~~~~~~~~~~~~~~

Found 1 error(s).

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

## Steps to Reproduce
My coworker @chestercharles threw together a repo that you can check out that demonstrates this build failure: https://github.com/chestercharles/slonik-roarr-bug

I was able to track this down to slonik@23.5.5

If you do `yarn add slonik@23.5.4 && yarn build` then all is well, but the error shows back up with `yarn add slonik@23.5.5 && yarn build`

**Comment by gajus** [comment]
Not entirely sure what was the cause, but it is no longer an issue in the latest release.

**Comment by spruce-bruce** [comment]
Good news! Seems like a temporary regression caused by an upstream dependency then. I'm happy to update my version of slonik back up to the latest!
