### ISSUE TITLE
idleTimeout (option for createPool) doesn't accept  'DISABLE_TIMEOUT'

### ISSUE THREAD

**Issue by paulovieira** [gajus/slonik#269]
## Expected Behavior

According to the docs, we can use
```
createPool(pgUrl, { idleTimeout: 'DISABLE_TIMEOUT' })
```

## Current Behavior

In https://github.com/gajus/slonik/blob/master/src/factories/createPoolConfiguration.ts we see that the `'DISABLE_TIMEOUT'` string is not used anywhere for `idleTimeout` (it's used only for `connectionTimeout`).

## Possible Solution

Maybe do something similar to what is done in `connectionTimeout`?
```
poolConfiguration.idleTimeoutMillis = undefined
```

It's not clear if this is supported in `pg`: https://node-postgres.com/api/pool

**Comment by gajus** [comment]
Addressed in https://github.com/gajus/slonik/pull/340
