### ISSUE TITLE
Stop using Knex.js - Fragments sample no longer works

### ISSUE THREAD

**Issue by Matthijn** [gajus/slonik#271]
## Expected Behavior
Perhaps it's because after the blog post the API changed, but the sample to create fragments doesn't seem to work anymore. 

In that blog post there is the following sample.

```
const createWhereFragment = (firstName: string) => {
  if (firstName) {
    return sql.raw('WHERE first_name = $1', [firstName]);
  }
  return sql.raw('');
};
const createLimitFragment = (limit: number, offset?: number) => {
  if (offset) {
    return sql.raw('LIMIT $1 OFFSET $2', [limit, offset]);
  }
  return sql.raw('LIMIT $1', limit)
};
const query = sql`
  SELECT id
  FROM user
  ${createWhereFragment(userInputFirstName)}
  ${createLimitFragment(userInputLimit)}
`;
```

## Current Behavior
`sql.raw` does not exist. 

## Possible Solution
I'm not quite sure what the right approach is now. I'm trying to create dynamic queries like the above.

**Comment by gajus** [comment]
There is [`raw`](https://github.com/gajus/slonik-sql-tag-raw) if you want to use it. You don't need this in this case, though.

The specific example that you shared can be rewritten as:

```js
const createWhereFragment = (firstName: string) => {
  if (firstName) {
    return sql`WHERE first_name = ${firstName}'`;
  }
  return sql``;
};
const createLimitFragment = (limit: number, offset?: number) => {
  if (offset) {
    return sql`LIMIT ${limit} OFFSET ${offset}`;
  }
  return sql`LIMIT ${limit}`;
};
const query = sql`
  SELECT id
  FROM user
  ${createWhereFragment(userInputFirstName)}
  ${createLimitFragment(userInputLimit)}
`;

```

**Comment by gajus** [comment]
Wrote an article walking through query building using Slonik.

https://contra.com/p/AqZWWoUB-writing-composable-sql-using-java-script
