### ISSUE TITLE
Accept non array on sql.identifier

### ISSUE THREAD

**Issue by Matthijn** [gajus/slonik#272]
In `SQL.identifier` the library only accepts an array of identifiers. 

As in your example [here](https://stackoverflow.com/questions/60972112/slonik-dynamic-insert-query-via-sql-tag)

The following code was posted.

```
const identifiers = keys.map((key) => {
  return sql.identifier([key]);
});

sql`
  INSERT INTO api.emissions
  (${sql.join(identifiers, sql`, `)})
  VALUES
  (${sql.join(values, sql`, `)})
`
```

But if the identifiers array also accepts a single item, then you can rewrite it as.

```
sql`
  INSERT INTO api.emissions
  (${sql.join(identifiers.map(sql), sql`, `)})
  VALUES
  (${sql.join(values, sql`, `)})
`
```

Is there a specific reason that is not allowed?

**Comment by gajus** [comment]
Consistency.
