### ISSUE TITLE
Getting non auto-releasing connection from pool

### ISSUE THREAD

**Issue by Matthijn** [gajus/slonik#273]
In the documentation, getting a connection from a pool is like this:

```typescript
pool.connect(async (connection) => {
  await connection.query(sql`SELECT 1`);
  // When this returns, the connection is released
});
```

Is there also a way to get a non auto-releasing connection. Something like.

```typescript
const connection = await pool.connect()
// Do my thing
await connection.release()
```

I know I can run `query` the pool directly, but I need the same connection (per use case) since I will be using transactions on the connection. And directly gives me another connection each time.

**Comment by gajus** [comment]
There is not by design.

https://github.com/gajus/slonik#slonik-about-slonik-protecting-against-unsafe-connection-handling

**Comment by Matthijn** [comment]
I think this decision makes it impossible to use this library with [fp-ts](https://github.com/gcanti/fp-ts) (and potentially any functional way of programming). 

I'm trying to do something like this:

```
import { TaskEither } from 'fp-ts/TaskEither'
import * as TE from 'fp-ts/TaskEither'

function seed(): TaskEither<Error, Any> {
  return pipe(
      startTransaction(), // TaskEither<Error, DatabasePoolConnectionType> returns a non closing connection
      TE.chain((connection) => {
        return pipe(
            generateFakeData(),
            insertData(connection),
            TE.fold(rollback(connection), commit(connection)) // Internally these would release etc
        )
      })
  )
}
```

**Comment by gajus** [comment]
There are workarounds, that allow you to achieve this if you really want it, but there is no plan to add such API.

**Comment by Matthijn** [comment]
Do you have a suggestion for a workaround? BecauseI do really like Slonik. This is really the only thing at this point that makes me thinking about moving to something else.

**Comment by Matthijn** [comment]
Actually got a "workaround". Basically, I just gather all related queries I want to execute, and send them in one go. (Separated by ; ). This way I can use the pool query directly. 

```typescript
transaction(connection)([
    storeJobQuery(job),
    storeSlugQuery(slug),
    storeCompanyQuery(company),
])


export function transaction(connection: DatabaseConnection) {
  return function transactionConnection(queries: Query[]): TaskEither<Error, unknown> {
    const allQueries = [
        beginTransactionQuery(),
        ...queries,
        commitQuery()
    ]

    // Todo: Merge queries together
    return TE.tryCatch(() => connection.query(allQueries), toDbError)
  }
}

```

This works for me since I already generate the id's for the database entries in the backend, so I don't have to add a company first for example to get the id.

**Comment by gajus** [comment]
Thanks for sharing your workarond.
