### ISSUE TITLE
Basic example error - Unexpected SQL input. Query cannot be empty. Found only value binding

### ISSUE THREAD

**Issue by Portur** [gajus/slonik#274]
I'm trying to use a wrapper for querying but can't seem to use sql`${query}`, which returns the error 
Unexpected SQL input. Query cannot be empty. Found only value binding

## Expected Behavior
the `sql` module to accept any legit SQL inside `${query}`

## Current Behavior
`sql` sees the `query` var as `values`, from the params: (query :string, values :string[])

## Possible Solution
`sql` should accept both 
sql`SELECT 1` 
and 
let query = `SELECT 1`; 
sql`${query}`

## Steps to Reproduce
```javascript

// file 1 ------

export function init(credentials:PostgresConfig) {
    const connection_string = generateConnectionString(credentials)
    pool = createPool(connection_string);

    return doQuery
};

function generateConnectionString(config:PostgresConfig){
     return `postgresql://${config.user}:${config.password}@${config.host}:${config.port}/${config.database}?application_name=${config.application_name}`
}

async function doQuery (query:string) {
    return pool.connect(async (connection:any) => {
        return connection.any(sql`${query}`)
    })
};

// file 2 ------

let results:string[] = [];
try{
     results = await doQuery('SELECT * FROM public.table')
}
catch(e){
    console.error(e)
    // Unexpected SQL input. Query cannot be empty. Found only value binding.
}

```

## Logs
InvalidInputError: Unexpected SQL input. Query cannot be empty. Found only value binding.

**Comment by gajus** [comment]
This is by design to prevent doing exactly this.
