### ISSUE TITLE
Can't assert custom column type accurately

### ISSUE THREAD

**Issue by felamaslen** [gajus/slonik#275]
If I'm selecting from a JSON column which I expect to be in a certain shape, I should be able to assert the result type of my query.

## Steps to Reproduce

1. Set up database:

```sql
CREATE TABLE my_table (
  my_column json
);
INSERT INTO my_table (my_column) VALUES ('{"foo": "bar"}');
```

2. Run this code:

```ts
import { createPool, sql } from 'slonik';

const pool = createPool('postgres://localhost/my_database');

type MyRow = {
  my_column: {
    foo: string;
  };
};

async function test() {
  const result = await pool.query<MyRow>(sql`SELECT * FROM my_table`);
  assertDeepEqual(result.rows, [{ // use whatever assertion tool you like
    my_column: {
      foo: 'bar',
    },
  }]);
}

test();
```

## Expected Behavior

The code below builds with no Typescript errors and the assertion passes.

## Current Behavior

The assertion passes, but the following Typescript error is thrown:

```bash
error TS2344: Type 'MyRow' does not satisfy the constraint 'Record<string, PrimitiveValueExpressionType>'.
  Property 'my_column' is incompatible with index signature.
    Type '{ foo: string; }' is not assignable to type 'PrimitiveValueExpressionType'.
      Type '{ foo: string; }' is missing the following properties from type 'readonly PrimitiveValueExpressionType[]': length, concat, join, slice, and 16 more.

     const result = await pool.query<MyRow>(sql`SELECT * FROM my_table`);
```

## Possible Solution

The reason seems to be that the constraints on the generic query result type are overly restrictive. Despite `json` being automatically parsed with the default type parsers, only primitive value types like `string` and `number` are accepted.

Relevant line: https://github.com/gajus/slonik/blob/master/src/types.ts#L163

Related issue: #265 introduced type safety, specifically [this line](https://github.com/gajus/slonik/blob/master/src/types.ts#L373) which restricts the type on the query result. I can't reproduce the issue on earlier commits.

**Comment by felamaslen** [comment]
BTW this is also applicable to other columns where custom type parsers are used.

For example, if I implement a parser for dates:

```ts
import { createPool, createTypeParserPreset } from 'slonik';

const pool = createPool('postgres://localhost/my_database', {
  typeParsers: [
    ...createTypeParserPreset(),
    {
      name: 'date',
      parse: (value: string): Date => new Date(value),
    },
  ],
});
```

then I should be able to specify a `Date` return type in queries, as that is what the result will be after parsing.

**Comment by gajus** [comment]
No longer an issue after Runtime validation has been added

https://github.com/gajus/slonik#user-content-slonik-runtime-validation

e.g.

```ts
const main = async () => {
  const pool = await createPool('');

  await pool.connect(async (connection) => {
    const resultShape = z.object({
      my_column: z.object({
        foo: z.string(),
      }),
    });

    const foo = await connection.query(sql.type(resultShape)`SELECT * FROM my_table`);
  });

  console.log(foo);
};
```

`foo` has the expected type:

<img width="634" alt="Screen Shot 2022-08-19 at 9 29 34 AM" src="https://user-images.githubusercontent.com/973543/185641239-9cf74c4e-5d09-4ea2-bf41-37c0ce5a0569.png">
