### ISSUE TITLE
Support For "interval" Expressions

### ISSUE THREAD

**Issue by muratgozel** [gajus/slonik#279]
I'm executing a query that includes a date comparison. In pure PostgreSQL format:
```sql
select id
from table
where created_at + interval '60 seconds' > now();
```
works as expected. But with slonik:
```js
// threshold = '60 seconds'
return await pgconn.exists(sql`
  select id
  from eventlog
  where created_at + interval ${threshold} > now()
`)
```
It raises a **syntax error at or near...**

I'm not sure if this is a bug, missing feature or an implementation error. 

Note 1: [Related docs for reference.](https://www.postgresql.org/docs/13/functions-datetime.html)

Note 2: The output of the `sql` function inside the real codebase:
```
{
  sql: '\n' +
    '      select id\n' +
    '      from eventlog\n' +
    '      where\n' +
    '        code=$1 and\n' +
    '        payload=$2 and\n' +
    '        created_at + interval $3 > now()\n' +
    '    ',
  type: 'SLONIK_TOKEN_SQL',
  values: [
    'SIGNIN_REQUESTED',
    '{"credential":"asdasdasd"}',
    '60 seconds'
  ]
}
```

**Comment by gajus** [comment]
I cannot see a reason this would not work.

> It raises a syntax error at or near...

Whats the error?

**Comment by muratgozel** [comment]
Here is a test function that simulates the same error:
```js
async function test1() {
  const threshold = '60 seconds'
  const result1 = await app.context.pgpool.connect(async (pgconn) => {
    return await pgconn.exists(sql`
      select id
      from eventlog
      where
        created_at + interval ${threshold} > now()
    `)
  })
  console.log('result1:', result1)
}
try {
  await test1()
} catch (e) {
  console.log(e)
}
```
Terminal output which has been caught by try-catch block:
```
Error: syntax error at or near "$1"
    at module.exports.Client._emitResult (/project/node_modules/pg-native/index.js:173:26)
    at module.exports.Client._read (/project/node_modules/pg-native/index.js:215:31)
    at PQ.emit (events.js:315:20)
    at PQ.EventEmitter.emit (domain.js:467:12) {
  severity: 'ERROR',
  code: '42601',
  position: '94',
  file: 'scan.l',
  line: '1180',
  routine: 'scanner_yyerror',
  notices: []
}
```

If I remove the template literal:
```js
async function test2() {
  const result2 = await app.context.pgpool.connect(async (pgconn) => {
    return await pgconn.exists(sql`
      select id
      from eventlog
      where
        created_at + interval '60 seconds' > now()
    `)
  })
  console.log('result2:', result2)
}
try {
  await test2()
} catch (e) {
  console.log(e)
}
```
Then it prints `result2: false` which is what it should be.

Node version: v14.16.0
PostgreSQL version: PostgreSQL 13.2 on x86_64-apple-darwin20.3.0, compiled by Apple clang version 12.0.0 (clang-1200.0.32.29), 64-bit
Slonik version: 23.7.0

**Comment by gajus** [comment]
Sorry, misread what you are doing.

It should:

```js
sql`
interval '1 second' * ${seconds}
`
```

**Comment by muratgozel** [comment]
Okey, that works. thanks.

**Comment by muratgozel** [comment]
Hey again @gajus

This problem appeared again when using `interval` in the `SELECT` expression. When I try to execute the following query:
```js
const tokenLife = '4 hours'
const result = await pgconn.query(sql`
  SELECT to_timestamp(1632187619) + interval '1 second' * ${tokenLife} as date;
`)
```
It raises an error that says **InvalidInputError: error: invalid input syntax for type double precision: "4 hours"**.

On the other hand on postgresql console if I execute the same query:
```sql
SELECT to_timestamp(1632187619) + interval '4 hours' as date;
```
I get the expected response which is date:
```txt
2021-09-21 05:26:59+00
```

I have also tried the following but it didn't work:
```js
const tokenLife = '4 hours'
const result = await pgconn.query(sql`
  SELECT to_timestamp(1632187619) + interval ${tokenLife} as date;
`)
```
Raised **syntax error at or near "$1"**

**Comment by mmkal** [comment]
I've worked around this before by doing something like:

```ts
const tokenLife = '4 hours'
const result = await pgconn.query(sql`
  SELECT to_timestamp(1632187619) + ${tokenLife}::interval as date;
`)
```

But I agree, it'd be nice to have a helper that worked something like:

```ts
const result = await pgconn.query(sql`
  SELECT to_timestamp(1632187619) + ${sql.interval(4, 'hours')} as date;
`)
```

Where the second arg would be a literal type (`'seconds' | 'hours' | 'days' | ...`)

**Comment by muratgozel** [comment]
@mmkal Casting to interval resolved my problem. Thanks.
