### ISSUE TITLE
How to use slonik with express

### ISSUE THREAD

**Issue by himat** [gajus/slonik#285]
It would be nice if there was an example of how to get started with using slonik in a node/express backend.
Other ORMs and ORM related tools usually have a real example, but slonik doesn't.

I want to know what the best way is to create a db pool only once and be able to access it in various other files in my server.

**Comment by gajus** [comment]
This is express.js question.

**Comment by himat** [comment]
I already figured out a way myself, but this isn't as much for me.
It's actually a matter of you making slonik easier to get started with for new people so I recommend you add an example to your docs but okay.

**Comment by mmkal** [comment]
@gajus I think this is a valid docs request, it would help newcomers who are familiar with express but not slonik understand how to use it. Maybe worth enabling Discussions in settings for this kind of thing?

**Comment by gajus** [comment]
Discussions enabled.
