### ISSUE TITLE
TIMESTAMP and TIMESTAMPTZ get parsed incorrectly after upgrading to v24

### ISSUE THREAD

**Issue by michaelgrigoryan25** [gajus/slonik#292]
## Expected Behavior
TIMESTAMP and TIMESTAMPTZ should get parsed correctly.

## Current Behavior
After updating slonik to version 24.0.0, TIMESTAMP and TIMESTAMPTZ get parsed incorrectly and return a future date/time.

## Steps to Reproduce

Just create a simple table like this one:

```sql
create table sample (
     id bigserial not null primary key,
     created_at timestamp not null default now()
)
```

Insert a sample item

```js
sql` INSERT INTO sample (id) VALUES (1234) `
```

Afterward query the items

```
SELECT * FROM sample;
```

And the parsed `created_at` date is incorrect

**Comment by gajus** [comment]
That reproduction does not yield unexpected results.

The only related recent change is this:

https://github.com/gajus/slonik/commit/1e9a484d7e7ac11066ea387b31d0dc67f12e4bbc

Though it would not explain your example.

Please add more details or a test case that demonstrates unexpected behavior.

**Comment by michaelgrigoryan25** [comment]
Here's the full example. This is a serious issue

```js
const { createPool, sql } = require("slonik");
const slonik = createPool(
  "postgres://postgres:miki2005@localhost:5432/postgres"
);

slonik.connect(async (connection) => {
  await connection.query(sql`
		CREATE TABLE IF NOT EXISTS people (
			id BIGSERIAL NOT NULL PRIMARY KEY,
			name VARCHAR NOT NULL,
			created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
		);
	`);

  await connection.query(sql`
		INSERT INTO people (name) VALUES ('John')
	`);

  const { rows } = await connection.query(sql`
		SELECT * FROM people;
	`);

  console.log(rows);
});
```

After querying, I get this timestamp: `1629193916170`, which after I convert to date equals to this: `2/6/53597, 5:36:10 AM`. You can convert the timestamp to date either with raw JS or using this website https://timestamp.online/. The result is the same.

**Comment by michaelgrigoryan25** [comment]
Here's the full example. This is a serious issue

```js
const { createPool, sql } = require("slonik");
const slonik = createPool(
  "postgres://postgres:test@localhost:5432/postgres"
);

slonik.connect(async (connection) => {
  await connection.query(sql`
		CREATE TABLE IF NOT EXISTS people (
			id BIGSERIAL NOT NULL PRIMARY KEY,
			name VARCHAR NOT NULL,
			created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
		);
	`);

  await connection.query(sql`
		INSERT INTO people (name) VALUES ('John')
	`);

  const { rows } = await connection.query(sql`
		SELECT * FROM people;
	`);

  console.log(rows);
});
```

After querying, I get this timestamp: `1629193916170`, which after I convert to date equals to this: `2/6/53597, 5:36:10 AM`. You can convert the timestamp to date either with raw JS or using this website https://timestamp.online/. The result is the same.

**Comment by michaelgrigoryan25** [comment]
@gajus any updates on this?

**Comment by gajus** [comment]
I am pretty sure this has been addressed in https://github.com/gajus/slonik/commit/1e9a484d7e7ac11066ea387b31d0dc67f12e4bbc.

Is it still a problem?

**Comment by michaelgrigoryan25** [comment]
For some reason, no. Thank you!
