### ISSUE TITLE
copyFromBinary isn't working because pg-copy-streams-binary API has changed

### ISSUE THREAD

**Issue by ctusch** [gajus/slonik#293]
Calling `copyFromBinary` throws an error. I'm using slonik 24.0.0.

## Expected Behavior
The copy operation should execute.

## Current Behavior
I'm getting the following exception:
```
TypeError: pg_copy_streams_binary_1.deparser is not a function
    at ...\node_modules\slonik\src\utilities\encodeTupleList.ts:21:20
    at new Promise (<anonymous>)
    at Object.encodeTupleList (...\node_modules\slonik\src\utilities\encodeTupleList.ts:16:10)
    at Object.copyFromBinary (...\node_modules\slonik\src\connectionMethods\copyFromBinary.ts:42:31)
```

## Possible Solution
`pg-copy-streams-binary`'s API has changed starting with version 1.3.0. The export `deparser` no longer exists. I _think_ it has been replaced with `rowWriter`.

**Comment by gajus** [comment]
This will be removed if it does not get patched.
