### ISSUE TITLE
`stream` documentation severely lacking

### ISSUE THREAD

**Issue by shellscape** [gajus/slonik#297]
I chose the bug template because there's no issue template that otherwise addresses shortcomings in documentation.

## Expected Behavior

When reading the docs for [`stream`](https://github.com/gajus/slonik#slonik-query-methods-stream) I expected there to be comprehensive information about its behavior. 

## Current Behavior

A lack of documentation and the need for users to source-dive the library source to gain understanding that the docs should provide.

## Possible Solution

The following information is missing, and required for users to fully understand the method, since the API for the method diverges significantly from what `node-pg-query-stream` provided (before it was archived):

- Why the method is async, given that it's producing a stream
- What the result of the returned `Promise` is for the method
- Why a callback is needed, or why that choice for an API was used, given that `node-pg-query-stream` simply returns a `Stream` as is the expected and long-standing standard in the Node ecosystem.
- Are there actions/code required to let the program know that the stream has finished processing? (Is this related to the `Promise` return type?
- What else differs from use of `node-pg-query-stream` in the `stream` method?

## Steps to Reproduce

It's worth noting that a number of methods seem to be light on documentation and could benefit from more verbosity.

**Comment by gajus** [comment]
If you've already researched these topics, are you available to contribute changes to the documentation?

**Comment by shellscape** [comment]
I haven't researched these, and I'm not sure the timeline of our project will allow for it. As slonik is highly opinionated, I'm afraid you as the original author are going to have the burden of documenting motivation for decisions on the API as well.

**Comment by shellscape** [comment]
@albertreed saw your comment here: https://github.com/gajus/slonik/issues/300#issuecomment-932327357. This one was closed without explanation or resolution, and would be a great target for docs improvement.
