### ISSUE TITLE
Question: How to build a query with a dynamic where clause?

### ISSUE THREAD

**Issue by lamontadams** [gajus/slonik#300]
I'm trying to generate a dynamic where clause something like this: 
```
const field1 = 1
const field2Clause = someValue ? ` and field2=${someValue}` : ''
sql`select * from table where field1=${field1}${field2Clause}`
```
and I'm unable to work out how to do it. As written that results in a syntax error because parameter tokenization results in a query like `select * from table where $1$2`

Looking at the [query-building section of the docs](https://github.com/gajus/slonik#slonik-query-building) I don't see any support mentioned, but there's a suggestion to see the dev.to post [Dynamically generating SQL queries using Node.js](https://dev.to/gajus/dynamically-generating-sql-queries-using-node-js-2c1g) which shows the use of a whole bunch of helper functions (`sql.raw` in the "Injecting dynamic SQL fragments" section for one) that apparently have been removed.

So, is this possible? Do I need to install some other package to have `sql.raw` available?

Suggestion: I don't want to pile on, but the project docs here really do leave something to be desired. If the dev.to post the docs link to is outdated, then the suggestion to read it should be removed. Otherwise update the docs so it's clear how to make use of the information it contains. The current situation is just confusing and irritating.

**Comment by albertreed** [comment]
I believe you want `sql.identifier`.

**Comment by albertreed** [comment]
(sorry for the initial misread of your question).

To accomplish this, I'd just build a query that does the whole thing rather than putting the logic in JS. Not sure if that's best practice or not.

**Comment by lamontadams** [comment]
No worries, sorry for my kinda snarky reply.

Building SQL with elaborate boolean logic to only apply supplied values is a solution, but part of the reason we use query builders is to, you know, build dynamic queries. ;)

**Comment by mmkal** [comment]
I believe this would work:

```ts
const field1 = 1
const field2Clause = someValue ? sql` and field2=${someValue}` : sql``
sql`select * from table where field1=${field1}${field2Clause}`
```

But +1 on the docs update request, I think I discovered that by accident and now just remember it.

**Comment by gajus** [comment]
The original question has been answered my @mmkal .

Regarding the suggestions to improve documentation, please contribute to the documentation.

It is a lot simpler to see what's need to be added to the documentation for someone who is just figuring it out, than for someone who have been using the API for a long time.

I will gladly support anyone who wants to contribute to the docs.

**Comment by albertreed** [comment]
I'll put together a PR to capture this pattern in the docs. 

If you're aware of any other issues which were resolved in ways that documentation would have helped, just point me at them I'll do a bunch.

**Comment by gajus** [comment]
Wrote an article walking through query building using Slonik.

https://contra.com/p/AqZWWoUB-writing-composable-sql-using-java-script

**Comment by lamontadams** [comment]
I've since moved on and don't use slonik any more, but I think it's funny that you've written an article, yet you still haven't updated [the docs](https://github.com/gajus/slonik#slonik-query-building), which still link to the old obsolete [dev.to post](https://dev.to/gajus/dynamically-generating-sql-queries-using-node-js-2c1g).
