### ISSUE TITLE
sql TTL buggy behavior

### ISSUE THREAD

**Issue by Ericnr** [gajus/slonik#303]
This regex will match even when `$(\d+)` doesnt represent a parameter https://github.com/gajus/slonik/blob/91efde6dd5c9f9d482fdc3f289fbdd4222507aa2/src/sqlFragmentFactories/createSqlSqlFragment.ts#L15
Ex: 
```js
sql`SELECT * FROM users WHERE ${sql`name = 'whacky name $5' OR name = ${'some name'}`}`
// throws "UnexpectedStateError: The greatest parameter position is greater than the number of parameter values."
```
it counts `$5` as a param and throws the error. I have the impression that in some cases it will even cause incorrect behavior without throwing, but I failed to reproduce those cases again.

One possible fix is to only calculate all the param indices after flattening the nested sql tags, so you dont have to rely on brittle regex. Here's an example: [TS Playground Link](https://www.typescriptlang.org/play?#code/MYewdgzgLgBAygRwDYBUCGBzOBPAtgIxCRgF549CkAKAckVUxoEoBuAKDamwAcBTeZOgykYAbzYxJMaACcAlmAwQAXNKjzFAbQC67KTF4APbjN4QIc8Cphow2HXqmhc3OUl6qqTUgD4YAITQIXgBFAFdeGWwAYXAAMzkMR0lNeiEcAiJtVXUI9gBfdk4efkDg8MiY+MSRcX0ECKjVWQUkiSluNBk0XGtbe102Qo4uPhgKqNiwBOEyMtDGqumagB8BBja2UEhYOKQ0KCheMDTMESooTFVTjG8SPzqnK1gGyoAFLqgIER0bb5atIN9NtoDBOt1ej9tH8bHYHBx9JcMAA6AFKZFxEAyACiaGAAAsqFRgGEZAAaGByO4Pdr6SSvKIfGRfZHcMIQQkkmSsBF0yQg2BgIxQbHGERI5FGExmCxWTRyIF8ylxGBUIWGEXGbyPJVSOQqtXC0XcVKCTAZSjQkjWmC5Xja2m6ukAemdBmMpnMljAlO+N0dTqeOxgewOIlDh2ON0NGuNPMDfIZ2CZX00SZTEGR7kUUHxMAAtDAAIzQgDUJADCf0EeR6c+EE0AAZFVX6YsM6z2YTkT2a3XmZmIEg5MBeFQi0x463JOCepm2RyqD2MfsoKyunOp4H8gYkMExJXA673dKveBfTYwRvcIenbPep3F+rNdwt078reP-p8jzHaYoKSPqiDA-ZfBS97fMMwxsHEYRgMAUDetIyAXFASCqCgvAuKuvBwOorQQAAgjI3TYBSy5Sp6sqQKo-Q6Ew1xmsIOowAKagaEoPzLocSCDI6bFIrUt6mhsFpZDkMgRDCApkreaLWJoy7ydosm6pRMrehAqlKs4rjuJ4DEBEECyVFMMy+AeVZscBoFaVeEKQeGq5HCcTEXJgv5Wc8IGLCItkYm4RwyFQ-ggEQvC2EwyKmAAJmEo5EniwAUlyFJUhZLFVvqqpyKQNoQVmxwYLm3j-oBNjAMAMClqxpLJK22VULlNVFjAfgFdmxX4t4uYyCAADuMDYiRWK0AAciAsDHCAYQYHmEHMPVVZlTIPpJdVtUyBtAAGAAku2iM1xb5NtS1KvkFI0ItvKBitQE+ZU4HXpBZ2SBdjrQfod22pgBQcFs3mCWQEDINtcDYgAMti0QoDAABUMAAGIAEoAPIALIwOykTfAA6gAEtiyPYjAB0g0g21gD0-BkDQ-X4niADW2AwFTuD8LtACsNAwKjyOs9TIgHTQEAgOzAvszQJ0nQDkDhVmIAYO5KK6W4Y5RUmrBAA)

**Comment by gajus** [comment]
Would accept a PR that fixes this, however, otherwise this is a pretty low priority since it is a somewhat edge case.

**Comment by gajus** [comment]
Adding "wontfix" for this because there isn't a reliable fix for this sort of converting SQL to AST.
