### ISSUE TITLE
Question: creating tables from variables

### ISSUE THREAD

**Issue by lassizci** [gajus/slonik#306]
Hi,

I'm trying to figure out a way to create tables, partially from user input, but the closest I can find is https://github.com/gajus/slonik/issues/200, but doesn't quite fit. I'd like to be able to do something like:

```TypeScript
const tableName = 'mytable';
const colType = "decimal(10,2)";


sql`CREATE TABLE ${sql.identifier([tableName])} ( amount ${colType} );
```
which gives
```TypeScript
{
  sql: 'CREATE TABLE "mytable" ( amount $1 );',
  type: 'SLONIK_TOKEN_SQL',
  values: [ 'decimal(10,2)' ]
}
```
and that hits `error: syntax error at or near "$1"`

And if I try to use `identifier`:
```TypeScript
sql`CREATE TABLE ${sql.identifier([tableName])} ( amount ${sql.identifier([colType])} );`

{
  sql: 'CREATE TABLE "mytable" ( amount "numeric(10,2)" );',
  type: 'SLONIK_TOKEN_SQL',
  values: []
}
```
 it hits `error: type "decimal(10,2)" does not exist`, since I don't think types with parameters can be quoted. `"text"` would work though.

**Comment by gajus** [comment]
There is now [`sql.literalValue`](https://github.com/gajus/slonik#slonik-query-building-sql-literalvalue)
