### ISSUE TITLE
slonik-interceptor-query-normalisation no more usable?

### ISSUE THREAD

**Issue by skarbovskiy** [gajus/slonik#307]
As far as i see, after introducing commented bindings removal in https://github.com/gajus/slonik/commit/8c505b2991e6dbba290bb91a743fbe65d7736ee8 this interceptor should be marked as deprecated.

**Comment by gajus** [comment]
What's the reason `slonik-interceptor-query-normalisation` is no longer "usable"?

**Comment by skarbovskiy** [comment]
Because https://github.com/vitaly-t/pg-minify introduced in this commit already do all the job, slonik intercepter did before.

**Comment by gajus** [comment]
`pg-minify` has since been removed.
