### ISSUE TITLE
Making `sql` tag a standalone package

### ISSUE THREAD

**Issue by tdzienniak** [gajus/slonik#312]
## Desired Behavior
`sql` tag can be installed from NPM as a standalone package (without installing slonik).

## Motivation
I like the idea behind `sql` tag very much and I think it would be good to release it as standalone package. This way it could be used without using slonik. Slonik is great, but sometimes we need to build dynamic queries in projects where we can't use slonik (from various reasons).

**Comment by gajus** [comment]
There are already packages that do that, even if not as advanced. No interest to do it with Slonik since I've got no use case. We always use Slonik.

**Comment by akutruff** [comment]
Any chance to reconsider this?  I'm trying to do optimistic frontend SQL with SQLite that ultimately uses Slonik with postgress on the backend.  The sql tag in Slonik is the best out there as far as I can tell, and its a shame that I am either going to have to mix with another lib or bail on Slonik.  Splitting the packages would not have any impact other than requiring two dependencies like postgres-bridge.

**Comment by gajus** [comment]
Why can't you depend on Slonik?

**Comment by akutruff** [comment]
Correct me if I'm wrong, but some of the dependencies don't work in the browser, such as pg.
