### ISSUE TITLE
Is their any way to Insert array value without `memberType`?

### ISSUE THREAD

**Issue by cfengsequoia** [gajus/slonik#315]
Error thrown: `InvalidInputError: Invalid list member type. Must be a SQL token or a primitive value expression.` if insert data with array value directly.
Hope that `value` or `sql.array(value)` supported, to build SQL like this:
```
{
  sql: 'INSERT INTO "table" ("user_ids") VALUES ($1)',
  values: [
    [ 1, 2 ],
  ]
}
```
Instead of `$1::int[]`

**Comment by nponiros** [comment]
I use https://github.com/gajus/slonik#slonik-recipes-inserting-large-number-of-rows when I want to insert multiple rows

**Comment by cfengsequoia** [comment]
> I use https://github.com/gajus/slonik#slonik-recipes-inserting-large-number-of-rows when I want to insert multiple rows

Thanks, my question is not multiple rows. mark secondary params of `sql.array` optional, e.g. `sql.array([1, 2])`

**Comment by gajus** [comment]
@cfengsequoia Are you able to do that with https://npmjs.com/package/pg?

If yes, then it should be available. However, from what I know, all members of array have to be of the same type.

**Comment by cfengsequoia** [comment]
@gajus Yeah, package `pg` is avaliable. When I passed javascript array as value, the slonik will throw error `Invalid list member type. Must be a SQL token or a primitive value expression.`
