### ISSUE TITLE
SQL statements containing $1 cause errors

### ISSUE THREAD

**Issue by mmkal** [gajus/slonik#318]
## Expected Behavior

Running queries that happen to include `$1` somewhere in them should be possible. Examples:

```sql
select '$1'
```

Or:

```sql
prepare test_statement as
select * from foo where bar = $1
```

These are valid queries, so slonik as a SQL client should support them.

## Current Behavior

slonik tries to parse the query (?) and thinks that the `$1` that appears is a binding parameter, then throws when the wrong number of binding parameters are passed in. Error message/stack:

```
    error: bind message supplies 1 parameters, but prepared statement "" requires 0

      at Parser.parseErrorMessage (node_modules/pg-protocol/src/parser.ts:369:69)
      at Parser.handlePacket (node_modules/pg-protocol/src/parser.ts:188:21)
      at Parser.parse (node_modules/pg-protocol/src/parser.ts:103:30)
      at Socket.<anonymous> (node_modules/pg-protocol/src/index.ts:7:48)
```

## Possible Solution

I'm not sure. Some logs are below, but I haven't dug in enough yet to know which call is causing the problem.

## Steps to Reproduce

1. Create a pool with a valid connection
2. Run either of the queries above, and see that an error is thrown e.g.:

```typescript
await pool.query(sql`select '$1'`)
```

## Logs

Relevant line:

```
{
  "context": {
    "package": "slonik",
    "poolId": "HJVyCuzgQKa0n_BHCA3lAA-0",
    "connectionId": "HJVyCuzgQKa0n_BHCA3lAA-10",
    "queryId": "HJVyCuzgQKa0n_BHCA3lAA-12",
    "logLevel": 50,
    "error": {
      "length": 137,
      "name": "error",
      "severity": "ERROR",
      "code": "08P01",
      "file": "postgres.c",
      "line": "1668",
      "routine": "exec_bind_message",
      "message": "bind message supplies 1 parameters, but prepared statement \"\" requires 0",
      "stack": "error: bind message supplies 1 parameters, but prepared statement \"\" requires 0\n    at Parser.parseErrorMessage (/Users/mkal/src/slonik-tools/node_modules/pg-protocol/src/parser.ts:369:69)\n    at Parser.handlePacket (/Users/mkal/src/slonik-tools/node_modules/pg-protocol/src/parser.ts:188:21)\n    at Parser.parse (/Users/mkal/src/slonik-tools/node_modules/pg-protocol/src/parser.ts:103:30)\n    at Socket.<anonymous> (/Users/mkal/src/slonik-tools/node_modules/pg-protocol/src/index.ts:7:48)\n    at Socket.emit (events.js:376:20)\n    at addChunk (internal/streams/readable.js:309:12)\n    at readableAddChunk (internal/streams/readable.js:284:9)\n    at Socket.Readable.push (internal/streams/readable.js:223:10)\n    at TCP.onStreamRead (internal/stream_base_commons.js:188:23)"
    }
  },
  "message": "execution routine produced an error",
  "sequence": "6",
  "time": 1639398903760,
  "version": "2.0.0"
}
```

First discussed here: https://github.com/mmkal/slonik-tools/issues/357#issuecomment-992011843

**Comment by mmkal** [comment]
Ok, found the bug. It's in `removeCommentedOutBindings`. Testing with the query `select '$1'`, everything looks good before this line: https://github.com/gajus/slonik/blob/c2a92c60c33a5195e7830cbbdea00d86435d6209/src/routines/executeQuery.ts#L195

Before that line: `{ actualQuery: { sql: "\n    select '$1'\n  ", values: [] } }`
After that line: `{ actualQuery: { sql: "select '$1'", values: [ undefined ] } }`

I don't have context on what problem `removeCommentedOutBindings` is trying to solve, so not sure how exactly to fix, but the problem is very likely that it's trying to use regex to parse the SQL query: https://github.com/gajus/slonik/blob/c2a92c60c33a5195e7830cbbdea00d86435d6209/src/utilities/removeCommentedOutBindings.ts#L11. I think it should either do no parsing and trust the SQL, if that's possible, or use a full-blown SQL parser - regexes are all ways likely to run into problems like this.

**Comment by gajus** [comment]
Cannot think of many ways to fix something like this. Off-the-top of my head, these are the options:

1. Parse query into AST. However, there isn't really a capable parser that would support every PostgreSQL syntax. Not that I am aware of one anyway.
2. Add a new query method that does not support bound parameters.

To give you a context around why `removeCommentedOutBindings` exists:

Suppose you have a query:

```ts
sql`
  SELECT
    ${1},
    ${2},
    ${3}
`
```

This is interpreted as:

`SELECT $1, $2, $3` with values [1, 2, 3]

Now suppose you comment out part of the query, e.g.

```ts
sql`
  SELECT
    ${1},
    /* ${2}, */
    ${3}
`
```

Now this is interpreted as:

`SELECT $1, $3` with values [1, 2, 3]

This by itself would not be a major problem, but because SQL queries can be nested, i.e.

```ts
sql`
  SELECT ${1}, (${sql`SELECT ${2}`}) 
`
```

we need to keep track of unique parameter bindings, i.e.

```ts
sql`
  SELECT
    ${1},
    /* ${2}, */
    ${3}
`
```

has to become: `SELECT $1, $2` with values `[1, 3]`.

I am investigating what can be done about this.

**Comment by gajus** [comment]
@mmkal Found a way to make it work without introducing SQL parsing.

https://github.com/gajus/slonik/commit/e1bf584415ca4bddb052ae205cd994352af9e65e
