### ISSUE TITLE
Export the "sql" tag as a separate package

### ISSUE THREAD

**Issue by cazzer** [gajus/slonik#324]
## Desired Behavior
I love Slonik in general and the `sql` tag is without a doubt my favorite part. Exporting it as a separate package would let nutjobs like me write SQL in new places, such as client-side code if you're into that sort of thing. It would also let sensible people who are locked into using other clients, such as Knex for its migration API, get the benefit of syntax highlighting when writing queries as horrid strings because somehow that is considered just fine by most JS libraries, (except this one, 🙏🏼 )

## Motivation
I'd like to write SQL in my client-side code for...reasons...and your `sql` tag would bring syntax highlighting sanity to my otherwise insane world.

## Implementation
Just toss that magic in a new repo and update `slonik` to import it whenever you feel like it.

**Comment by gajus** [comment]
https://github.com/gajus/slonik/issues/312
