### ISSUE TITLE
import issue for StreamHandler and PoolContext Types.

### ISSUE THREAD

**Issue by reyesdiego** [gajus/slonik#325]
```ts
import {
  TaggedTemplateLiteralInvocation,
  StreamHandler,
  CommonQueryMethods,
  PoolContext,
} from 'slonik';
```

Trying to import StreamHandler and PoolContext among others but I get "Module slonik has not exported member ..." in both types.

We are working with:

```
"slonik": "^27.1.0",
"@types/slonik": "^22.1.5",
```

Node Version v16.13.0

**Comment by mmkal** [comment]
Slonik now bundles its own types. I forgot to deprecate the separate types package. Just uninstall it for now and you should be good.
