### ISSUE TITLE
interceptor for `beforeClientError`

### ISSUE THREAD

**Issue by mmkal** [gajus/slonik#331]
## Desired Behavior

An interceptor to allow hooking into the errors thrown by "connection methods" like `.many`, `.one`, `.oneFirst` etc. Quite often we end up debugging `Resource not found` or `Query returns an unexpected result`. 

## Motivation

This would allow adding contextual info to errors which may end up in error tracking systems like Sentry.

## Implementation

Maybe put it in the `createConnection` function in `src/factories/createConnection.ts`?

**Comment by gajus** [comment]
I don't fully comprehend the use case. Could you illustrate an example of how you would use `beforeClientError` if it existed?

**Comment by gajus** [comment]
https://github.com/gajus/slonik/issues/204
