### ISSUE TITLE
Use `bigint` within `sql` template string query

### ISSUE THREAD

**Issue by nicholaschiang** [gajus/slonik#338]
## Desired Behavior

I want to be able to include `bigint`s in my `sql` template string queries like this:

![image](https://user-images.githubusercontent.com/20798889/161466731-ecf7ab83-b857-42f4-993d-78085cbf57d4.png)

## Motivation

Right now, `bigint`s are a pain to manage when interacting with Postgres from a Node.js environment. This is why I switched from using Prisma's `db.$queryRaw` method (see prisma/prisma#8121 and prisma/prisma#12367) which doesn't support `bigint` serialization and de-serialization very well. It appeared from [this library's documentation](https://github.com/gajus/slonik#built-in-type-parsers) that `bigint` de-serialization is already handled, and thus I assumed that serialization (i.e. using a `bigint` in a `sql` template string query) would also be handled. But it wasn't (at least AFAIK). Which is why I'll probably be [switching to `pg-promise` for now](https://github.com/vitaly-t/pg-promise/issues/657).

## Implementation

Copy over the `pg-promise` implementation (see vitaly-t/pg-promise#657 that's been around since 2019).

**Comment by gajus** [comment]
Related to https://github.com/gajus/slonik/pull/299

**Comment by gajus** [comment]
The problem is that if we start allowing BigInt, as an input and as an output, then you need to use them consistently across your application anywhere where the value can be a BigInt, which is.. most of your code base likely.

I don't see a good design for the addition of bigint for that reason, but I am open to proposals.

**Comment by nicholaschiang** [comment]
@gajus that's exactly what I'm doing though. I use Prisma and define my ID columns there as `BigInts` and then use those Prisma Typescript types across my code base, ensuring that I'm treating every ID as a `BigInt` everywhere. 

The problem arises because Prisma's support for `BigInts` in raw queries is lacking (see prisma/prisma#12367) and thus I need to use another Node.js Postgres client library while they're still working on polishing that up. I came first to `slonik` because it seemed like an interesting alternative (that, like Prisma's `$queryRaw` features, also uses ES6 template strings), but was disappointed by this lack of support for `BigInts`.

I think it makes sense to represent a `BigInt` from your database as a `BigInt` in your application code (as long as the language your application code is written in supports it... and as of Node.js 10, it does).

**Comment by gajus** [comment]
Let's see how this survey goes https://twitter.com/kuizinas/status/1561734172938469378

**Comment by AndrewJo** [comment]
> The problem is that if we start allowing BigInt, as an input and as an output, then you need to use them consistently across your application anywhere where the value can be a BigInt, which is.. most of your code base likely.
>
> I don't see a good design for the addition of bigint for that reason, but I am open to proposals.

Considering this discussion happened before adoption of Zod and typed sql template strings, I'm wondering if introducing support for bigint makes sense now. [Zod considers bigint as a primitive](https://zod.dev/?id=primitives) so I'm wondering if the bigint here should be treated the same way. It's a confusing DX when one defines the Zod object schema with bigint and get wrist slapped by TypeScript compiler for trying to use it in a sql template string:

```typescript
// Developer defines the Zod object schema matching the table schema
const FooSchema = z.object({
  id: z.bigint(),
  description: z.string(),
});

type FooSchema = typeof FooSchema;

async function getById(id: bigint): Promise<FooSchema> {
  // TypeScript does not like this though.
  const query = sql.type(FooSchema)`SELECT * FROM foo WHERE id = ${id}`;
  
  // Even though developer expectation from type validation is that id is a bigint according to Zod schema
  return await connection.one(query);
}
```

**Comment by jmwongbw** [comment]
I have a use case for BigInts as well. All primary keys in our DB are BIGINTs

**Comment by gajus** [comment]
This is now implemented
