### ISSUE TITLE
Sopport socket:// URLs, needed for AppEngine+CloudSQL use

### ISSUE THREAD

**Issue by RP-3** [gajus/slonik#341]
## Desired Behavior
- When following the official App Engine Postgres CloudSQL connection instructions [here](https://cloud.google.com/sql/docs/postgres/connect-app-engine-standard#connect_to) to connect to a Postgres instance via a public IP in the App Engine Standard Environment, I expect a socket:// connection string passed to Slonik to work. 
- Currently, Slonik throws an the error `[ERR_INVALID_URL]: Invalid URL`, when given a connection string in any of the following forms:
  - `socket://PASSWORD@/cloudsql/INSTANCE_CONNECTION_NAME/.s.PGSQL.5432?db=DB_NAME`
  - `socket://PASSWORD@/cloudsql/INSTANCE_CONNECTION_NAME?db=DB_NAME`
  - `socket://PASSWORD@/cloudsql/INSTANCE_CONNECTION_NAME/DB_NAME`

## Motivation
- Google App Engine recommends this as the default way to connect to CloudSQL, and it is also the _only_  way to connect if the database has a public IP address or is in a different region to the client initiating a connection.
- Google/Firebase Cloud Functions _only_ allow socket:// connections
- A variety of other reasons have been proposed in [this issue](https://github.com/gajus/slonik/issues/115), however, they advocate passing a full-blown `connection` object which is not strictly necessary for this use case
- [Other issues](https://github.com/gajus/slonik/discussions/290) imply that this previously worked, but was broken in subsequent updates. 

## Implementation
- @gajus has previously recommended a solution [here](https://github.com/gajus/slonik/issues/115#issuecomment-976722751).

**Comment by dbousamra** [comment]
Any further updates on this? This feature is preventing me from upgrading slonik

**Comment by gajus** [comment]
@mgreenw This was addressed by your PR, wasn't it?

https://github.com/gajus/slonik/pull/409

**Comment by gajus** [comment]
Thank you
