### ISSUE TITLE
Provide logger instance

### ISSUE THREAD

**Issue by shousper** [gajus/slonik#342]
## Motivation

I've seen a few of your libraries & issues (effectively) promoting the use of your own logger, `roarr`, which I see no problem with and quite like personally. However, it creates an issue for adoption of your libraries, should someone looking to adopt already have established an entire platform or ecosystem of their own using another logger that isn't so easily transitioned or migrated to `roarr`.

In fact, you don't offer the choice -- and that's why I'm creating this issue.

The logger is created [here](https://github.com/gajus/slonik/blob/master/src/factories/createPool.ts#L41) for `slonik` as pointed out in [this issue](https://github.com/gajus/slonik/issues/277) that went quiet, probably after finding another solution to their issue like [this one](https://github.com/gajus/slonik/issues/169) and/or perhaps [this one too](https://github.com/gajus/slonik/issues/119).

To support users of `slonik` (or any of your libraries really?) that wish to use another logger, for whatever reason, it needs to support overriding the implementation. Ideally in a clean fashion.

## Desired Behavior

- Accept a logger interface when creating a pool to override the logger implementation used.

## Implementation

Looking at the `createPool` function, I think it shouldn't be too much to ask that it support a `logger` configuration property added to `ClientConfigurationInput`, purely to override `poolLog` if `logger` is supplied. As long as the accepted type is an interface, anyone can write adapters for the interface should they be locked into another logger.

**Comment by gajus** [comment]
All of my packages use Roarr and do not support overriding logger instance for reasons outlined in Roarr documentation. Not to mention that Roarr has logging concepts that simply do not exist in other loggers (such as `adopt`).

This isn't a feature I am planning to add to either of the packages that I maintain.
