### ISSUE TITLE
Closing cursor after destroying stream

### ISSUE THREAD

**Issue by matthew-white** [gajus/slonik#347]
Using v28.1.0, I'm observing that in some cases after I destroy a stream, I'm unable to use the connection to then run a different query. If `foo` is a large table, then the following script never completes:

```js
const { createPool, sql } = require('slonik');

// Specify your connection URI here.
const pool = createPool('postgres://');

const main = () => pool.connect(async (connection) => {
  await connection.stream(sql`SELECT * FROM foo`, (stream) => {
    stream.destroy();
    console.log('stream destroyed');
  });
  console.log('before query');
  await connection.query(sql`SELECT COUNT(*) FROM bar`);
  console.log('all done');
});

main();
```

I see that `stream destroyed` and `before query` are logged, but `all done` is not: it seems that the promise that `connection.query()` returns never settles.

Note that `foo` must be ~a large table~ a table of a certain size. If the `connection.stream()` query returns fewer rows, then I don't see this behavior. For example, if I make the following change, then I don't see this behavior:

```diff
-  connection.stream(sql`SELECT * FROM foo`, (s) => {
+  connection.stream(sql`SELECT COUNT(*) FROM foo`, (s) => {
```

After a little investigation, I'm thinking that the cause of the behavior is that calling `stream.destroy()` doesn't close the underlying `QueryStream`. If the `QueryStream` isn't closed, then I think the `pg-cursor` `Cursor` also won't be closed.

If I add logging to the `close()` method of `QueryStream`, then I don't see `close()` being called when I run the script above. But if I modify `stream()` to call `queryStream.close()` when `transformedStream` is closed below, then the script completes successfully:

https://github.com/gajus/slonik/blob/371f15257451ee5c918e817aba7879a4c04f20b8/src/connectionMethods/stream.ts#L68-L77

**Comment by lognaturel** [comment]
Thanks for building `slonik`, @gajus! 

What can we do to help move this forward? Would you be up for reviewing a PR if we sent one in? This is bringing some of our users' servers down so we are eager to see it addressed. Thanks!

**Comment by lognaturel** [comment]
@struan-murray I see you've given this issue a 👍. Have you also been experiencing it?

**Comment by jcwatson11** [comment]
Just bumping this issue to say this bug is having an affect for us. Connection leaks exceed the pool size causing the server to crash.

**Comment by gajus** [comment]
> Just bumping this issue to say this bug is having an affect for us. Connection leaks exceed the pool size causing the server to crash.

Will accept a PR. You are the best to fix since you are affected by it.

**Comment by alxndrsn** [comment]
> Note that foo must be a large table a table of a certain size.

I think the result set must be >= 100 rows.

**Comment by alxndrsn** [comment]
Here's a slightly simpler version of @matthew-white's repro:

```javascript
pool.connect(async connection => {
  await connection
      .stream(sql`SELECT * FROM GENERATE_SERIES(1, 100)`, stream => {
        stream.on('close', () => console.log('stream closed'));
        stream.destroy();
        console.log('destroy() called');
      }); 

  console.log('before query');
  await connection.query(sql`SELECT TRUE`);
  console.log('all done');
});
```

Output:
```
destroy() called
stream closed
before query
```

**Comment by alxndrsn** [comment]
Also behaves the same without the explicit connect:
```javascript
(async () => {
  await pool
      .stream(sql`SELECT * FROM GENERATE_SERIES(1, 100)`, stream => {
        stream.on('close', () => console.log('stream closed'));
        stream.destroy();
        console.log('destroy() called.');
      }); 

  console.log('before query');
  await pool.query(sql`SELECT TRUE`);
  console.log('all done');
})();
```
