### ISSUE TITLE
Module '"slonik"' has no exported member 'createMockQueryResult'

### ISSUE THREAD

**Issue by AlenDavid** [gajus/slonik#349]
There is no 'createMockQueryResult' being exported from slonik, although the README.md mention it (https://www.npmjs.com/package/slonik#user-content-mocking-slonik). 

## Expected Behavior

To have the exported function.

## Current Behavior

There is no function called 'createMockQueryResult' being exported.

## Possible Solution

It's probably a typescript problem. I think it's an easy fix.

## Steps to Reproduce

1. npm install slonik
2. copy/paste example code from README.

```javascript
import {
  createMockPool,
  createMockQueryResult,
  sql
} from 'slonik';

const pool = createMockPool({
  query: async () => {
    return createMockQueryResult([
      {
        foo: 'bar',
      },
    ]);
  },
});

await pool.connect(async (connection) => {
  const results = await connection.query(sql`
    SELECT ${'foo'}
  `);
});
```

3. run `ts-node index.js`; fail with `Module '"slonik"' has no exported member 'createMockQueryResult'.`.

## Logs
<img width="1200" alt="image" src="https://user-images.githubusercontent.com/26146736/170348569-f911e60e-3bbb-440b-bcc5-ce10a898e961.png">

**Comment by AlenDavid** [comment]
Oh, the problem was with `@types/slonik`. If possible, please push the declarations file there, too.

**Comment by mmkal** [comment]
`@types/slonik` is deprecated, slonik provides its own types now. You should remove it.

**Comment by AlenDavid** [comment]
I remove that folder and I forget to mention here. 🤣
