### ISSUE TITLE
Migrate to postgres.js? [latest benchmarks]

### ISSUE THREAD

**Issue by xerosanyam** [gajus/slonik#352]
## Desired Behavior

Wondering if it is possible to modify underlying layer from [pg](https://github.com/brianc/node-postgres) to [postgres](https://github.com/porsager/postgres); postgres.js  is **considerably** faster, benchmarks below.

## Motivation

Slonik is only marginally performant in select query. In rest checks it is significantly slower.

#### slonik@27.1.1, postgres@3.0.0
|**client**|**select**|**select_arg**|**select_args**|**select_where**|
|-|-|-|-|-|
|[`slonik`](https://github.com/gajus/slonik)|9,176 ⚡️|7,357 (-14.78%)|3,845 (-41.47%)|3,606 (-46.21%)|
|[`postgres`](https://github.com/porsager/postgres)|8,829 (-3.78%)|8,633 ⚡️|6,569 ⚡️|6,704 ⚡️|

#### slonik@28.1.1, postgres@3.2.4
|**client**|**select**|**select_arg**|**select_args**|**select_where**|
|-|-|-|-|-|
|[`slonik`](https://github.com/gajus/slonik)|12,634 ⚡️|9,296 (-22.42%)|5,294 (-43.11%)|4,692 (-47.74%)|
|[`postgres`](https://github.com/porsager/postgres)|12,401 (-1.84%)|11,982 ⚡️|9,305 ⚡️|8,978 ⚡️|

#### slonik@28.1.1, postgres@3.2.4
- default configuration (the configuration that people mostly use)
- removed `captureStackTrace:false` from slonik & `max:1` from postgres.js

|**client**|**select**|**select_arg**|**select_args**|**select_where**|
|-|-|-|-|-|
|[`slonik`](https://github.com/gajus/slonik)|4,367 (-67.21%)|3,972 (-68.45%)|2,946 (-66.5%)|2,938 (-69.29%)|
|[`postgres`](https://github.com/porsager/postgres)|13,318 ⚡️|12,589 ⚡️|8,794 ⚡️|9,567 ⚡️|

System:
  OS: macOS 12.4
  CPU: 2.6 GHz 6-Core Intel Core i7
  Memory: 16.00 GB
Binaries:
  Node: 16.3.1
  Postgres: 14.3

**Comment by gajus** [comment]
I would do this as a separate project that creates a compatibility layer for `postgres`.

Then Slonik would simply need to accept Pool override.

**Comment by gajus** [comment]
You can now achieve that with https://github.com/gajus/postgres-bridge
