### ISSUE TITLE
Is it possible to use nested arrays in queries?

### ISSUE THREAD

**Issue by MadsKK** [gajus/slonik#354]
My goal is to use a nested arrays in a query. Something along the lines of the following: 

```
[
  [ '2022-04-06 17:05:47.917+00', '2022-04-06 17:35:47.917+00' ],
  [ '2022-04-06 19:05:47.917+00', '2022-04-06 20:35:47.917+00' ]
]
```

I know it's possible, since you can use do the same with typecasting in the interactive terminal (PSQL).

You would think that it would be possible to just use nested `sql.array()`, but in this case it doesn't work.

I have tried to come up with many different solutions, where most of them were just a guessing game. Now I have reached the point, where I want to know if Slonik even supports nested arrays.

From what I can gather it doesn't. If you try and do the following:

```
sql.array([sql.array([ '2022-04-06 17:05:47.917+00', '2022-04-06 17:35:47.917+00' ],'timestamptz'), sql.array([ '2022-04-06 19:05:47.917+00', '2022-04-06 20:35:47.917+00' ],'timestamptz')], 'timestamptz')
```

it gives the following type error `Type 'ArraySqlToken' is not assignable to type 'PrimitiveValueExpression'.`. I therefore, tried to use `sql.join()` instead, which didn't give me a type error, but still didn't work as intended.

So from my point of view I guess it's not possible to use nested arrays in queries?

**Comment by gajus** [comment]
For what it is worth, you can just pass JSON.

**Comment by gajus** [comment]
This is the way to go https://contra.com/p/P7kB2RPO-bulk-inserting-nested-data-into-the-database-part-ii
