### ISSUE TITLE
Export PoolContext and StreamHandler types

### ISSUE THREAD

**Issue by gonzavz** [gajus/slonik#355]
## Desired Behavior

I would like to use the following types
```
PoolContext and StreamReader
```
## Motivation

Im upgrading a current project using slonik v21 to slonik v28 and I have to say is really good. But on the project we were using the following types `PoolContext` and `StreamReader` to implement some mocks I notice that the types are not exported from slonik any more, why is that?

## Implementation

the change would be updating the index.ts exporting those types

**Comment by gajus** [comment]
There is no `StreamReader` type in Slonik codebase. The other one was added to the exports.
