### ISSUE TITLE
Documentation: Promise.all incompatible with transactions

### ISSUE THREAD

**Issue by andrewbihl** [gajus/slonik#357]
With Slonik, it is possible to break out of transactions with the use of Promise.all inside a transaction callback, where one of the promises can make changes after another has thrown and triggered a rollback, causing those changes to be persisted. 

This is an easy mistake to make, and could lead to dramatic consequences if misused. I’d recommend updating the documentation to warn others. I do not know if the behavior of the library can or will be changed, but even so documentation would be a helpful stopgap. 

Thoughts? I am happy to take a pass on it if desired.

**Comment by gajus** [comment]
Can you provide an example code to illustrate?

I don't see how you can "break out" of transaction.

**Comment by raphael-verdier** [comment]
@gajus There is an article that explains this behavior here: https://medium.com/@alkor_shikyaro/transactions-and-promises-in-node-js-ca5a3aeb6b74
I don't know if this belongs in the Slonik documentation. There could be other ways of messing with promises that would cause this. However it is a very sneaky trap and the documentation calls the function "safe transaction handling" which makes it even harder to debug when you encounter this case.

One solution for Slonik to have a very strong safety net for this would be to associate each transaction with a dynamic list of promises corresponding to all the queries sent using this specific transaction connection. When an error is thrown, it could then wait the end of all the registered queries before reverting the transaction. This is not perfect and I don't realize all the implications for slonik. 

In any case, this is an issue easy to miss when you use Slonik with transactions a lot.

**Comment by gajus** [comment]
I think there are two separate issues being discussed here _or_ some invalid assumptions.

Slonik transactions are safe to use, i.e. doesn't matter if you use `Promise.all` or not, if one query fails, nothing is committed (before or after). I just added a sanity-check test case for this. That's the issue that Medium post talks about, but it does not affect Slonik.

If there is a different issue, please provide a test case.
