### ISSUE TITLE
Contribute to postgresql-client

### ISSUE THREAD

**Issue by erayhanoglu** [gajus/slonik#380]
[postgresql-client](https://github.com/panates/postgresql-client) is a pure JavaScript PostgreSQL client completely written in TypeScript. It has been created for high load enterprise applications. It appears that your approach is similar – [postgresql-client](https://github.com/panates/postgresql-client) has many features that enterprise projects needs. 

Would love to see you contribute to [postgresql-client](https://github.com/panates/postgresql-client).

**Comment by gajus** [comment]
Have you seen https://github.com/gajus/slonik#user-content-slonik-how-are-they-different-postgres-vs-slonik ?

There is an existing bridge for `postgres` to integration with Slonik, and you could write one for `postgresql-client`.

`postgresql-client` and Slonik have different goals – Slonik wants to be a universal client for any driver.
