### ISSUE TITLE
Function createPool does not honor the connection timeout setting during initialization

### ISSUE THREAD

**Issue by kkorenius** [gajus/slonik#391]
Function createPool does not honor the connection timeout as specified in the client configuration when the pool is being initialized.

## Expected Behavior
The createPool function should not wait more than a specified connection timeout in the client configuration (default 5000 ms) for the initial (set-up time) connection to be established.

## Current Behavior
During the execution of the createPool function the library opens an initial connection to the database for retrieving some data type information. This connection does not inherit or allow specifying any timeout values thus reverting to node-postgres library default behavior of waiting indefinitely for the connection to be opened.

## Possible Solution
Additional client configuration properties should be passed to the client setup connection:
https://github.com/gajus/slonik/blob/3bd59e0483f45c45140809f0805ba538da653612/src/factories/createPool.ts#L61-L68

**Comment by gajus** [comment]
Thanks, fixed!
