### ISSUE TITLE
How to Insert Records with timestamp field using unnest

### ISSUE THREAD

**Issue by odm275** [gajus/slonik#395]
Hello,
I am trying to do the following, but it is not working.
``` js
  const valueTypes = ["text", "text", "int4", "text", "timestamp"];

  await db.query(sql`
  INSERT INTO "Item" ("id", "name", "par", "restaurantId", "updatedAt")
  SELECT *
  FROM ${sql.unnest(
    [
      [cuid(), "test1", 3, restaurantId, sql.timestamp(new Date())],
      [cuid(), "test2", 3, restaurantId, sql.timestamp(new Date())],
    ],
    valueTypes
  )}
`);
```
I keep the getting the following error: 
`Invalid unnest tuple member type. Must be a primitive value expression.`

If I remove the "updatedAt" column, I can insert the records just fine. How do I work with dates here when inserting time/date data? I looked at the documentation and I can't figure it out. An example would greatly help.  Help is appreciated!

**Comment by gajus** [comment]
Don't use `sql.timestamp` in this context: Just provide iso date. Not intended use case.

```ts
const valueTypes = ["text", "text", "int4", "text", "timestamp"];

await db.query(sql`
INSERT INTO "Item" ("id", "name", "par", "restaurantId", "updatedAt")
SELECT *
FROM ${sql.unnest(
  [
    [cuid(), "test1", 3, restaurantId, new Date().toISOString()],
    [cuid(), "test2", 3, restaurantId, new Date().toISOString()],
  ],
  valueTypes
)}
`);
```

I will add better error reporting for these cases.
