### ISSUE TITLE
Integrate TypeBox validator

### ISSUE THREAD

**Issue by Ivan-Baranov** [gajus/slonik#427]
Add [TypeBox](https://github.com/sinclairzx81/typebox) validator/type provider used in [Fastify](https://github.com/fastify/fastify) framework.

Fastify support several type providers:
- [Zod type provider](https://github.com/turkerdev/fastify-type-provider-zod)
- [TypeBox type provider](https://github.com/fastify/fastify-type-provider-typebox)

## Desired Behavior
This will allow us to use a single type description in the validation of routes and query results from the database.

**Comment by Toshonka** [comment]
It would be nice👍

**Comment by gajus** [comment]
We are committed to using Zod API, but the actual validation is not built into Slonik.

Theoretically you can use TypeBox here (as long there is a way to remap those type definitions).

https://github.com/gajus/slonik#user-content-result-parser-interceptor
