### ISSUE TITLE
PrimitiveValueExpression preventing valid return type for `jsonb_build_object`

### ISSUE THREAD

**Issue by janpaepke** [gajus/slonik#428]
A Query can also return an object as part of the result. Current type definitions do not allow that.

## Expected Behavior
If I return an object from a query using `json_build_object`, i expect the returned col to be of the appropriate type.

Example:
```ts
sql<{test: { property: string } }>`select jsonb_build_object('property', 'value') as test`
```

## Current Behavior
Due to the definitions in https://github.com/gajus/slonik/blob/main/src/types.ts#L351 it does not expect any property of the returned result to be an object.

## Possible Solution
A solution is to add an object literal type to the `PrimitiveValueExpression`, although I am not certain about the implications of this.
```ts
export type PrimitiveValueExpression =
  Buffer |
  boolean |
  number |
  string |
  readonly PrimitiveValueExpression[] |
  { readonly [key: string]: PrimitiveValueExpression} |
  null;
```

## Steps to Reproduce

1. test the query above in slonik 29 vs slonik 32.
It works as expected in 29.

**Comment by gajus** [comment]
This is no longer a problem as of the latest major version.

**Comment by opichon** [comment]
Sorry, but howis this "no longer a problem in the latest major version"?

`QueryResultRow = Record<string, PrimitiveValueExpression>;`

```
export type PrimitiveValueExpression =
  Buffer |
  boolean |
  number |
  string |
  readonly PrimitiveValueExpression[] |
  null;
```

In `Interceptor`, the `transformRow` method requires a `QueryResultRow`, and therefore does not accept an object as part of the row.
