### ISSUE TITLE
When is sql.identifier required? - sql function composition clarification

### ISSUE THREAD

**Issue by mrbrannan** [gajus/slonik#431]
With this simple `SELECT` statement I am having an issue where the library throws an error `syntax error at or near \"$1\"\n`
```
sql`SELECT *
                FROM abc.${this._tableName}
                WHERE user_id = ${sql.literalValue(userId)}`
```

Where if I compose `sql.identifier` it has no issues.

```
sql`SELECT *
                FROM abc.${sql.identifier([this._tableName])}
                WHERE user_id = ${sql.literalValue(userId)}`
```

I am trying to understand why the latter works (so I can understand composition better). Because I have another query, an `INSERT` that does not require me to wrap the table name in `sql.identifier`. See that below.

```
sql`INSERT INTO abc.${tableName} (${sql.join(
    Object.keys(data).map((key) => sql.identifier([key])),
    sql`, `
  )})
   VALUES (${sql.join(objectValues(data), sql`, `)})
   RETURNING *`
```

Thank you in advance for any insights here.

**Comment by aust1nz** [comment]
You may be able to see some insight if you console.log the result of the sql tagged template. It will show you the SQL and values that Slonik creates from your input. (I'm guessing there are double quotes added erroneously around the $1 in the first example, but not the second.)

**Comment by mrbrannan** [comment]
> You may be able to see some insight if you console.log the result of the sql tagged template. It will show you the SQL and values that Slonik creates from your input. (I'm guessing there are double quotes added erroneously around the $1 in the first example, but not the second.)

Thanks for the reply. I am not seeing any quotes around the placeholder, but there is a new line. However, even without that it returns the same error. The table name is being passed in the values array, so it looks like slonik is not compiling the query correctly? You can see the `WHERE` clause is formatted with the value in-line.

```
{
  "context": {
    "package": "slonik",
    "poolId": "Icg1wE5oS_qVYWN8ooFOLg-0",
    "connectionId": "Icg1wE5oS_qVYWN8ooFOLg-1",
    "transactionId": "Icg1wE5oS_qVYWN8ooFOLg-2",
    "queryId": "Icg1wE5oS_qVYWN8ooFOLg-3",
    "logLevel": 20,
    "sql": "SELECT *\n                FROM abc.$1\n                WHERE user_id = 'fZAQV8Hkl0S1g4wme7lcXmo3eZ62'",
    "stackTrace": [
      "/Users/mrb/source/abc/api/src/lib/data/repository/UserEvents.ts:39:43",
      "node:internal/process/task_queues:96:5",
      "/Users/mrb/source/abc/api/src/lib/data/repository/UserEvents.ts:38:13",
      "/Users/mrb/source/abc/api/src/lib/data/repository/UserEvents.ts:37:32",
      "/Users/mrb/source/abc/api/src/lib/data/repository/UserEvents.ts:10:11",
      "/Users/mrb/source/abc/api/src/resources/users/userEvents/v1.ts:12:23"
    ],
    "values": [
      "user_events"
    ]
  },
  "message": "executing query",
  "sequence": "2",
  "time": 1668269498482,
  "version": "2.0.0"
}
```

**Comment by mrbrannan** [comment]
Well according to the docs, I should probably be doing this for everything anyways 👍 

https://github.com/gajus/slonik#sqlidentifier

```
sql.typeAlias('id')`
  SELECT 1 AS id
  FROM ${sql.identifier(['bar', 'baz'])}
`;
```

```
sql.typeAlias('id')`
  SELECT 1 AS id
  FROM ${sql.identifier(['bar', 'baz'])}
`;
```
