### ISSUE TITLE
Slonik not compiling because of Record key typing error

### ISSUE THREAD

**Issue by MiK546** [gajus/slonik#432]
I'm having trouble with the latest versions of Slonik not compiling at all even in an empty project I created just to test this out. The TypeScript compilation error I receive is:

```
> npx tsc
node_modules/slonik/dist/src/index.d.ts:25:24 - error TS2344: Type 'unknown' does not satisfy the constraint 'string | number | symbol'.

25         parser: Record<unknown, import("zod").ZodTypeAny>[Y];
                          ~~~~~~~


Found 1 error in node_modules/slonik/dist/src/index.d.ts:25
```

## Expected Behavior
The project compiles without errors.

## Current Behavior
The project does not compile because of TypeScript errors.

## Possible Solution
This error seems to be caused because `unknown` is used as the key of the record. If for example the `PropertyKey` type was used instead there would be no problem.
```ts
typeAlias: <Y extends PropertyKey>(parserAlias: Y) => (parts: readonly string[], ...args: readonly import("./types").ValueExpression[]) => Readonly<{
        parser: Record<PropertyKey, import("zod").ZodTypeAny>[Y];
```

I don't know if that would make sense otherwise though.

## Steps to Reproduce
Link to a code sandbox, hope it works (or more like doesn't in this case) https://codesandbox.io/s/festive-cray-exw74t. The error should come up once you run `npm build` / `npx tsc`.

## Logs
n/a I think.

**Comment by nathanchapman** [comment]
Confirmed that v33.0.4 resolves this compilation error. I think we can close this issue now @gajus @MiK546

**Comment by gajus** [comment]
Thank you
