### ISSUE TITLE
TypeError: sql is not a function

### ISSUE THREAD

**Issue by TusharJoy** [gajus/slonik#434]
## TypeError: sql is not a function in Typescript
```
const { sql } = require("slonik");
const slonikPool = require("../poolService"); //DB Pool connection


await (await slonikPool()).maybeOne(
        sql`select * from table where key = 'KEY'`
      );
```

this code result in TypeError: sql is not a function error on nodemon watcher 
I am using (package.json)
```
"slonik": "^33.0.3",
"typescript": "^4.9.3"
"nodemon": "^2.0.20",


```

**Comment by leosuncin** [comment]
Since [v33.0.0](https://github.com/gajus/slonik/releases/tag/v33.0.0) you need to use `sql.fragment`, `sql.type` or `sql.unsafe` and since [v32.0.0](https://github.com/gajus/slonik/releases/tag/v32.0.0) the query results aren't validated anymore

**Comment by TusharJoy** [comment]
After downgrading to v30.0.0 now getting this 
` TypeError: Cannot read properties of undefined (reading 'maybeOne')`

**Comment by markcellus** [comment]
Same here. I was surprised that `sql` can no longer be used. I've opened https://github.com/gajus/slonik/discussions/438 to inquire about the decision.

**Comment by gajus** [comment]
Answered in #438
