### ISSUE TITLE
Drop ZodType constraints on sql.type, QeurySqlToken, type aliases, etc

### ISSUE THREAD

**Issue by pgrocholski** [gajus/slonik#435]
Remove the `ZodType` type constraints on `sql.type` (and the `QuerySqlToken` that it generates, etc) as well as the type alias configuration to `createSqlTag` to enable users to use whatever runtime validation implementation that they chose without the need for excessive casting. The library could still promote the use of Zod, and use Zod internally for things such as the interval tag validation, but allow other libraries to be used for result validation without needing to jump through hoops. 

## Motivation

The rollout of runtime schema validation has been somewhat contentious and in the end the in the end the implementation of the validation interceptor has been left to the user to fit their needs. Thus the QuerySqlToken does not necessarily need to be be a Zod schema. There have been requests to support other validation providers and it has been pointed out that a user can implement that with their own interceptor. However, to do so the user needs to work around the current Zod type constraints, casting the input to `sql.type` and generally the result type as well. 

## Desired Behavior

The ability to input validation schemas for validators other than Zod without needing to cast.

For example a developer wishing to use class-transformer/class-validator as is common in the NestJS community should be able to define an interceptor like:
```typescript
{ transformRow: (queryContext: QueryContext, query: Query, row: QueryResultRow ): QueryResultRow => {
    const { resultParser } = queryContext;
    if (resultParser) {
        const result = plainToInstance(resultParser, row);
        const errors = validateSync(result);
        if (errors.length) {
            throw new SchemaValidationError(query, row, errors);
        }
        return result as QueryResultRow;
    }
    return row;
}}
```
To be used with
```typescript
class Test {
    @IsNumber()
    id!: number;

    @IsOptional()
    @IsString()
    name?: string;

    @IsDate()
    @Expose({ name: 'create_time'})
    @Type(() => Date)
    createdAt!: Date;
}

const res = await db.any(sql.type(Test)`SELECT id, name, create_time FROM test`);
```
without having to cast the validation annotated type and the result as is currently the case:
```typescript
const res = (await db.any(sql.type(Test as any)`SELECT id, name, create_time FROM test`)) as Test[];
```

**Comment by ericmbarnard** [comment]
Perhaps related to #437 https://github.com/gajus/slonik/issues/437 ?

**Comment by pgrocholski** [comment]
> Perhaps related to #437 ?

Not exactly, at a glance, it seems like #437 might be accomplished by a `createLegacySqlTag` of sort which aliases the raw `sql` tag to `sql.unsafe` which should handle most of the legacy use cases (conversely, it would be nice if `sql` was shorthand for `sql.fragment` in the default case, and perhaps `sql.unsafe` would be better named `sql.unTyped` to alleviate some confusion)

The idea here is not really legacy compatibility, but rather generalizing the new parser/type information being sent down to interceptors to allow uses beyond zod validation. That said, a version of `createSqlTag` that did not have the zod constraint/narrowing might be sufficient for most use cases, though its likely to cause issues if the constraint is still enforced on the query utility functions (`one`, `any`, etc..)

**Comment by antonversal** [comment]
I agree with @pgrocholski. The slonik library should be agnostic to any validation library. The idea of having validation is good in itself. And `Zod` might be the best validation library today, and it has insufficient support tomorrow. Would you change the validation library each time?

In our stack, we prefer to use a `class-validator`. Supporting two validation libraries is a headache.

**Comment by gajus** [comment]
I've put a lot of thought into trying to implement this, but I don't see a reasonable way to do it.

If someone wants to give this a try, I will help to get it across the line.
