### ISSUE TITLE
The inferred type of 'sql' cannot be named without a reference to '.pnpm/zod@3.19.1/node_modules/zod'. This is likely not portable. A type annotation is necessary.

### ISSUE THREAD

**Issue by sheiy** [gajus/slonik#436]
<img width="1524" alt="image" src="https://user-images.githubusercontent.com/12210038/204248511-5a0e0b50-55d7-4c1c-ad3e-fb81b930ea2c.png">

**Comment by markcellus** [comment]
May be related to this as well: https://github.com/gajus/slonik/discussions/438
