### ISSUE TITLE
inserting large number of rows using unnest with an array column

### ISSUE THREAD

**Issue by retorquere** [gajus/slonik#44]
If I try to insert an array column, I get `error: type "varchar[][]" does not exist`

```
await connection.query(sql`
      INSERT INTO xx (id, txt)
      SELECT *
      FROM ${sql.unnest(
        [
          [1, ['"', "'"]],
          [2, ["'", '"']],
        ],
        [
          'int4',
          'varchar[]'
        ]
      )}
    `)
```

**Comment by gajus** [comment]
There is currently no way to add an array of arrays using unnest. I thought of it when designing the API and considered it to be a fairly edge case.

It should be easy to solve though.

I could recognise the `[]` suffix, strip it from the type identifier, and append it to the quantifier.

What do you think about this API, does it solve your problem, or do you want to propose an alternative solution?

**Comment by retorquere** [comment]
That sounds pretty clean to me.

**Comment by retorquere** [comment]
I must be getting something wrong in the syntax; when I run this:

```
import { sql, createPool } from 'slonik'
const config = require('./config.json').aws

const connectString = `postgresql://${encodeURIComponent(config.user)}:${encodeURIComponent(config.password)}@${config.host}:${config.port}/${config.database}?`
console.log(connectString
  .replace(config.password, '<password>')
  .replace(config.host, '<hostname>')
)

const pool = createPool(connectString)

function main(asyncMain) {
  asyncMain()
    .then(exitCode => {
      process.exit(exitCode || 0)
    })
    .catch(err => {
      console.log(err)
      process.exit(1)
    })
}

main(async () => {
  console.log(sql`SELECT 1`)
  await pool.connect(async (connection) => {
    console.log('starting')
    await connection.query(sql`
      CREATE TEMPORARY TABLE xx (id INT, txt varchar[])
    `)
    await connection.query(sql`
      INSERT INTO xx (id, txt)
      SELECT *
      FROM ${sql.unnest(
        [
          [1, ['"', "'"]],
          [2, ["'", '"']],
        ],
        [
          'int4',
          'varchar[]'
        ]
      )}
    `)
    console.log(await connection.query(sql`SELECT * FROM xx`))
    console.log('done')
  });
})
```

I get `error: column "txt" is of type character varying[] but expression is of type character varying`

**Comment by retorquere** [comment]
The query expands to

```
{
  "sql": "\n      INSERT INTO xx (id, txt)\n      SELECT *\n      FROM unnest($1::\"int4\"[], $2::\"varchar\"[][])\n    ",
  "values": [
    [
      1,
      2
    ],
    [
      [
        "\"",
        "'"
      ],
      [
        "'",
        "\""
      ]
    ]
  ]
}
```

**Comment by gajus** [comment]
The query and value binding look correct to me, though.

At least, this is what I would expect should work.

Have you tried asking node-postgres?

**Comment by retorquere** [comment]
Ah wait, this is passed into node-postgres? slonik is a wrapper around that? I'll go ask.

**Comment by retorquere** [comment]
Looks like `varchar[][]` isn't supported? https://github.com/brianc/node-postgres/issues/1644

**Comment by gajus** [comment]
Bummer. Then it is indeed unsupported.

There could be some workarounds client side.

Perhaps nesting unnest.

**Comment by retorquere** [comment]
What about a helper that automates something like
https://github.com/brianc/node-postgres/issues/957#issuecomment-226725964 ?

**Comment by vitaly-t** [comment]
Native multi-row insert is always the best, as it is the only one that's properly scalable, and flexible as to the value formatting. That's why I did it with [helpers.insert](http://vitaly-t.github.io/pg-promise/helpers.html#.insert).

**Comment by gajus** [comment]
> Native multi-row insert is always the best, as it is the only one that's properly scalable, and flexible as to the value formatting. That's why I did it with helpers.insert.

Unnest approach has quite a few benefits over using tuple list. See:

https://github.com/gajus/slonik#inserting-large-number-of-rows

**Comment by gajus** [comment]
> Looks like varchar[][] isn't supported? brianc/node-postgres#1644

This could be implemented as a helper function. It is too much of an edge case at the moment to add this to Slonik.

Let's see first if there is more demand.

**Comment by vitaly-t** [comment]
Major issue with `unnest` - you cannot apply any custom-type formatting, based on values. When you have special values that need specific formatting, `unnest` becomes unusable. And that happens way too often. 

i.e. `unnest` works only with default query formatting, which is very limited.

**Comment by gajus** [comment]
> Major issue with unnest - you cannot apply any custom-type formatting, based on values. When you have special values that need specific formatting, unnest becomes unusable. And that happens way too often.

Thats not true. You can apply any value formatting, e.g.

```js
sql`
INSERT INTO ...
SELECT
  payload::jsonb payload,
  decode(hash, 'hex') hash_binary,
  hash
FROM (
  SELECT *
  FROM ${sql.unnest(foreignAttributePayloadValues, ['text', 'text'])}
) input (payload, hash)
`

```

**Comment by vitaly-t** [comment]
Not sure how this is going to help when custom-type formatting is needed on the value level...

Here's an example:

```js
INSERT INTO table(id, name, active) VALUES(
  (1, 'first', true),
  (2, null, false),
  (3, 'last', DEFAULT)
)
```

And in case you have input data like this:

```js
const data = [
  {id: 1, name: 'first', active: true},
  {id: 2, name: '', active: false},
  {id: 3, name: 'last'}
];
```

In this example you can see how for the second record empty string for `name` is replaced with `null`, while missing `active` in the last record is replaced with reserved word `DEFAULT`.

To my knowledge, such formatting requires dynamic templates.

**Comment by gajus** [comment]
`null` is not a problem.

As for `DEFAULT`, where do you get this from in the first place? Something had to construct that query and know where to place DEFAULT token instead of a literal value.

If it is a known constant to the program, then you can treat it that way.

```js
sql`
INSERT INTO ...
SELECT
  CASE
    WHEN foo = ${DEFAULT_SYMBOL}
    THEN ${DEFAULT_VALUE}
    ELSE
  END
FROM (
  SELECT *
  FROM ${sql.unnest(foreignAttributePayloadValues, ['text'])}
) input (hash)
`

```

where `DEFAULT_SYMBOL` is whatever your program uses to represent that `DEFAULT` to create that query and `DEFAULT_VALUE` either hard-coded value or value obtained from information_schema.

**Comment by vitaly-t** [comment]
`DEFAULT` is PostgreSQL reserved word, to insert the value automatically, from the default value provided by the table. Here's the table example:

```sql
CREATE TABLE test(
    id SERIAL,
    name TEXT,
    active BOOLEAN DEFAULT true
)
```

**Comment by gajus** [comment]
> DEFAULT is PostgreSQL reserved word, to insert the value automatically, from the default value provided by the table. Here's the table example:

I know what the `DEFAULT` is.

What I am saying, your example query, e.g.

```sql
INSERT INTO table(id, name, active) VALUES(
  (1, 'first', true),
  (2, null, false),
  (3, 'last', DEFAULT)
)
```

needs to be generated by something.

If you have a literal query, then we wouldn't be having this conversation.

If it is generated by something, then that something has a constant of its own to represent DEFAULT constant, which it can use to create the above comparison.

It is a fictional issue. You can do what you've asked.

**Comment by nonara** [comment]
Just a quick comment regarding demand.

We're using slonik in a production setting and are very happy with it! Great to have a light-weight client which is both safe and 'close to the metal', so to speak.

That said, we're working with large data sets in a nightly cron capacity. Speed is important, so I'd love being able to use a binary COPY, but it seemed that the feature may not be supported (type isn't exported and comments in issues made it seem that it isn't stable?) For those reasons, I went with a single transaction with multiple upserts using unnest (2000 rows per query).

The problem is, some of our fields are arrays.

To me, this doesn't seem as too much of an edge case, as it will affect anyone working with inserting large data sets whose tables also include arrays. I appreciate the link from https://github.com/brianc/node-postgres/issues/1644#issuecomment-595231696 - Seems this method should help as a workaround.

I just wanted to add my two cents as to why the scenario may be less of an edge-case.

As an aside, if I'm mistaken on anything, particularly not being able to use COPY, I'd appreciate any added clarity!

**Comment by nonara** [comment]
I ended up changing unnest to `jsonb_to_recordset`, which works well! However, I had to use `slonik-sql-tag-raw` for the column definition list.

IE:

```ts
const obj = { key1: 'hello', key2: 3 };
const keys = Object.keys(obj).map(k => sql.identifier([ k ]));
colDefinitionList = [ 'key1 text', 'key2 int' ].map(def => raw(def));
query = sql`
  INSERT INTO "myTable" (${sql.join(keys, sql`, `))
  SELECT * FROM jsonb_to_recordset(${sql.json(obj)}) AS t (${sql.join(colDefinitionList, sql`, `)})
`;
```

Is there another way to do this without using raw? If not, perhaps a helper for `jsonb_to_recordset` could prove a simple solution as an alternate to unnest for large data inserts.

**Comment by qpwo** [comment]
Here's another example of above with manual column definitions:

```ts
const swords = [
    { id: 1, parts: ['a', 'b', 'c', 'd'], tints: [false, false, false, false] },
    { id: 2, parts: ['d', 'e', 'f', 'g'], tints: [false, true, false, true] },
]
const query = sql`
  INSERT INTO swords (sword_id, parts, tints)
  SELECT *
    FROM
  jsonb_to_recordset(${sql.jsonb(swords)})
    AS t (sword_id integer, parts text[4], tints boolean[4])`
```
