### ISSUE TITLE
sql.Identifier on jsonb columns wraps in quotes

### ISSUE THREAD

**Issue by stevehaneytrailblazer** [gajus/slonik#448]
Here is an example of a simple table that has a jsonb column that I would like to fetch some data from.

```
create table testtable (id uuid,jdata jsonb)
```

If I write a simple query using slonik...
```
const query = sql.unsafe`SELECT ${sql.identifier(["jdata['status']"])} from ${sql.identifier(['testtable'])}`;
console.log('testQuery', query.sql, query.values);
```
## Current Behavior
The query produced is `SELECT "jdata['status']" from "testtable"` which fails because of the wrapping quotes on the jdata column.

## Expected Behavior
The jsonb column should not wrap when using identifier.  Since there's not a perfect way to identify a json column (other than maybe brackets or ->>) perhaps a jsonIdentifier might be a good expansion of the jsonb support?  Maybe that could allow for segmenting the column and property into the identifier array?

Great lib btw!

**Comment by gajus** [comment]
I can think of a few ways this can be solved, but can you elaborate on why it needs to be a dynamic field?

i.e. Why you didn't simply write:

```ts
sql.unsafe`
  SELECT jdata['status']
  FROM ...
`
```

If the column is dynamic, you could also write:

```ts
sql.unsafe`
  SELECT ${sql.identifier(['jdata'])}['status']
  FROM ...
`
```

which will produce:

```sql
SELECT "jdata"['status']
FROM ...
```

which is valid

If property is dynamic, you can do:

```
sql.unsafe`
  SELECT jdata[${sql.literalValue('bar')}]
  FROM ...
`
```

which will produce the same result.

You can combine them too, but if you need the entire expression to by dynamic, then your best bet is: https://github.com/gajus/slonik-sql-tag-raw
