### ISSUE TITLE
Add a helper function to construct connection URI

### ISSUE THREAD

**Issue by gajus** [gajus/slonik#45]
Connection URI is the most convenient way to store database configuration. However, as witnessed by submitted examples, others use object-configuration. The latter requires to manually construct connection URI, e.g.

```js
const connectString = `postgresql://${encodeURIComponent(config.user)}:${encodeURIComponent(config.password)}@${config.host}:${config.port}/${config.database}`

```

https://github.com/gajus/slonik/issues/43#issuecomment-472763884

This would obscure problems such as missing part of configuration until late in execution.

A solution would be a simple utility to construct the connection string and warn about missing fragments of the configuration.

**Comment by vitaly-t** [comment]
There is [connection-string](https://github.com/vitaly-t/connection-string) for that :wink:

But there are a few reasons why this should be supported properly by the low-level driver. Too bad it is going nowhere with this. For example, [see this issue](https://github.com/brianc/node-postgres/issues/1470).

**Comment by gajus** [comment]
`connection-string` looks great.

Though this issue describes the inverse:

Take:

```js
{ protocol: 'protocol', user: 'user', password: 'password', hosts: [ {name: 'host1', port: 123, isIPv6: false}, {name: 'abcd::', port: 456, isIPv6: true} ], path: ['one', 'two'], params: { p1: 'val1', msg: 'hello world!' } }

```

input and convert it to:

```js
protocol://user:password@host1:123,[abcd::]:456/one/two?p1=val1&msg=hello+world!

```

I want Slonik to accept only one format for defining the connection settings and connection URI makes the most sense (easy to port configuration). But given the popular use of the object configuration, library should provide a way to at least create a connection URI using an object.

Your library does this here:
https://github.com/vitaly-t/connection-string/blob/d2d69897fc16f4d2ab081f1c749fafbbad6e1086/src/index.js#L149-L190

**Comment by vitaly-t** [comment]
You can convert that object back into string, using `toString()` on the object, and you can create a new object via defaults, using [setDefaults](https://github.com/vitaly-t/connection-string#setdefaultsdefaults--connectionstring).

**Comment by gajus** [comment]
Added utilities `parseDsn` and `stringifyDsn`

https://github.com/gajus/slonik/commit/6c3b178c9b52418b348fb0d8a7a8e75fb31047f1

**Comment by dbousamra** [comment]
Hi @gajus. How do I connect to socket urls? parseDsn seems to throw an error

`socket://username:password@/cloudsql/project-id:australia-southeast1:some-database?db=dbName`

**Comment by gajus** [comment]
@dbousamra Currently not supported, but would be a simple contribution.
