### ISSUE TITLE
Make columnTypes in sql.unnest optional

### ISSUE THREAD

**Issue by sadiqkhoja** [gajus/slonik#455]
can you please make `columnTypes` in `sql.unnest` optional argument?

Postgresql doesn't require casting every column in unnest, I can write query like:

```
INSERT INTO test_table (test_column_1, test_column_2)
    SELECT * FROM UNNEST ($1, $2) AS t
```

**Comment by gajus** [comment]
Being explicit is good. Who would this benefit?

**Comment by sadiqkhoja** [comment]
I don't want to maintain the type of each column in Javascript. Current what is the way to compose mentioned query?

**Comment by gajus** [comment]
`sql.unnest` is the correct way of doing it. If types do not matter, you can always cast to `text` and pass through values as string. If they matter, than provide the types.
