### ISSUE TITLE
Allow more parameter types for `sql.date` and `sql.timestamp`

### ISSUE THREAD

**Issue by janpaepke** [gajus/slonik#458]
## Desired Behavior

Both `sql.date` and `sql.timestamp` should allow `null` as their input, which resolves to `null` in both cases.
Additionally `sql.date` should allow (ISO) strings and `sql.timestamp` should allow numbers.

#### The case for `null`
If I have a nullable date/time field the respective function should 'pass it through'.  
This is consistent with PSQL behaviour, as both `select null::date` as well as `select to_timestamp(null)` resolve to null.

Example:
```typescript
type DateField: Date | null;
let field: DateField = null;
await connection.query(sql.unsafe`
    update my_table set datefield=${sql.date(field)}
`);
```
Expected Token:
```typescript
{
  sql: 'update my_table set datefield=$1::date',
  values: [
    null
  ]
}
```

#### The case for `string` / `number`
It makes sense to allow the data in the types psql expects them in, which to my knowledge is `string` for `date` and `number` for timestamp.

This makes particular sense as the [default type parser for timestamp and date fields](https://github.com/gajus/slonik#default-configuration) produce `number` and `string` types respectively. This would sync input to output behaviour.

It is a little bit unfortunate that the parser produces Milliseconds, while `to_timestamp` expects seconds, but I think this is okay, if documented accordingly.
`to_timestamp` would have to implicitly divide by 1000, which I think it is already doing for `Date`.

Example:
```typescript
const time = connection.oneFirst(sql.type(z.number())`
    select '2022-08-19T03:27:24.951Z'::timestamp
`)
// time is now a number (milliseconds)
await connection.query(sql.unsafe(`
    update my_table set timefield = ${sql.timestamp(time)}
`))
```
Expected Token:
```typescript
{
  sql: 'update my_table set timefield = to_timestamp($1)',
  values: [
    '1660879644.951' // could also be a number. I chose string, as that's what it is in the example
  ]
}
```

## Implementation

The param types for `sql.timestamp` and `sql.date` would have to be adapted and the implementation updated accordingly.
Additionally this should be added to the respective docs.

If you agree with the change in principle, I would be open to creating a PR.

**Comment by gajus** [comment]
> The case for null

Just do:

```
await connection.query(sql.unsafe`
    update my_table set datefield=${field === null ? null : sql.date(field)}
`);
```

The more flexible these functions are, the more space for accidental misuse they allow. Being explicit is good.

**Comment by janpaepke** [comment]
Yes, that is a valid argument.
I figured this would be okay since there's a lot of implicit handling like this already happening when supplying values.

Consider this:
```typescript
await connection.query(sql.unsafe`
    select ${field /* ← null | string */}::text
`);
```

I agree that in the case of functions it might be better to be explicit.

What about the case for consistent input/output types?

**Comment by gajus** [comment]
This did not receive enough interest to proceed. Please re-open if you feel strongly about it.
