### ISSUE TITLE
Canonical way of partially updating a table

### ISSUE THREAD

**Issue by steliyan** [gajus/slonik#46]
Hey,
I was thinking about what should be the canonical way to partially update a table.

## Setup
For example, we have the following table:
```
books
- id
- name
- description
- author
```

## What I want to do?
I want to partially update a row from the `books` table, e.g. update `name` and `description`, but not the `author`.

Maybe it goes against the principle of the lib, namely: 

> Discourages ad-hoc dynamic generation of SQL.

but I think it's really a common problem that users need to solve.

## How can you do it if you update all columns?
```javascript
const bookId = 1;
const newName = "New Book Name";
const newDescription = "New Book Description";
const newAuthor = "New Book Author";
const updateNameStatement = sql`name = ${newName}`;
const updateStatusStatement = sql`status = ${newDescription}`;
const updateAuthorStatement = sql`status = ${newAuthor}`;

const updateBookSql = sql`UPDATE books
SET
  ${updateNameStatement},
  ${updateStatusStatement},
  ${updateAuthorStatement}
WHERE id = ${bookId};`;
```

## How can you do it if you update a subset of columns?
The most obvious way is to use the `sql.raw`, but you need to take care of the placeholder index by yourself when generating the query.
A better solution is to construct it using `sql` tag literal, for example:
```javascript
const bookId = 1;
const newName = "New Book Name";
const newDescription = "New Book Description";
const updateNameStatement = sql`name = ${newName}`;
const updateStatusStatement = sql`status = ${newDescription}`;
const updateStatements = [updateNameStatement, updateStatusStatement];

const updateBookSqlWithoutWhere = updateStatements.reduce(
  (updateQuery, currentUpdateStatement, index) => {
    if (index === updateStatements.length - 1) {
      return sql`${updateQuery} ${currentUpdateStatement}`;
    }

    return sql`${updateQuery} ${currentUpdateStatement},`;
  },
  sql`UPDATE books SET`
);

const updateBookSql = sql`${updateBookSqlWithoutWhere} WHERE id = ${bookId};`;
```

I think it's better than using `sql.raw` approach defined in the docs. Do you see anything grossly wrong with this approach?

Note: Currently, I am not using the library, I'm using `sequelize` with mostly raw SQL queries, but am considering to migrate to your library. :)

**Comment by gajus** [comment]
Ah, I variation of this, I would find definitely useful.

I am currently using a query builder myself for these scenarios, e.g.

```js
const updateUserRecord = async (
  connection: DatabaseConnectionType,
  userRecordId: number,
  email: string | void,
  givenName: string | void,
  familyName: string | void,
  passwordHash: string | void
) => {
  const query = qb
    .from('"user"')
    .set(omitUndefined({
      email,
      familyName,
      givenName,
      passwordHash
    }))
    .where({
      id: userRecordId
    })
    .query;

  await connection.query(sql`${sql.raw(query.text, query.args)}`);
};

```

where `qb` is an instance of Sqorn.

What would be handy is:

```js
await connection.query(sql`
  UPDATE "user"
  SET ${sql.assignmentList({
    email,
    familyName,
    givenName,
    passwordHash
  })}
  WHERE id = ${userRecordId}
`);

```

where `assignmentList` picks defined properties and generates:

```sql
UPDATE "user"
SET
  email = $1,
  given_name $2
WHERE id = $3

```

Can definitely have a look at this.

Equally, something like this for INSERT queries would be handy.

**Comment by Sharaal** [comment]
I suggest to have some helpers in addition to the sql tag queries like:

```javascript
const rowCount = await client.update(
  'users',
  { email: 'new email', passwordhash: 'new passwordhash' },
  { email: 'old email', passwordhash: 'old passwordhash' }
)

// text: UPDATE "users" SET "email" = $1, "passwordhash" = $2 WHERE "email" = $3 AND "passwordhash" = $4
// parameters: ['new email', 'new passwordhash', 'old email', 'old passwordhash']
```

Very convenient to have these kind of helpers for standard insert/update/delete/select operations and need using the sql tags only for complex queries.

Thx for the sql tags these helpers are very easy to define.

Hopefully I don't nerve you @gajus , but feel free to have a look at https://www.npmjs.com/package/sql-pg-helper for this kind of helper :)

**Comment by gajus** [comment]
@Sharaal Let me sit on this for a while and think about the potential upside/downsides. Will come back with comments in a week or so. Best to pick this up in a separate issue, though.

**Comment by vitaly-t** [comment]
In order to provide a proper solution, one need a way to define rules, such as updating logic, and thus the structure for representing those. That's why I wrote [helpers], as a means of generating both single-row and multi-row inserts and updates.

At the time, I gave it a lot of thinking, but couldn't find anything better than that, so here it is, as an example for you guys :wink:

Examples of using such a structure:

* [Conditional Update](https://stackoverflow.com/questions/45253866/skip-null-values-on-upsert)
* [Multi-row Insert](https://stackoverflow.com/questions/37300997/multi-row-insert-with-pg-promise)
* [Multi-row update](https://stackoverflow.com/questions/39119922/postgresql-multi-row-updates-in-node-js)

[helpers]:http://vitaly-t.github.io/pg-promise/helpers.html

**Comment by gajus** [comment]
A slight step in the direction of implementing this.

https://github.com/gajus/slonik/commit/405ac65e1bfb9acb05d9fad822afeaff10b24953

Will share more next week. Currently testing Slonik helper utilities as I am developing https://gitspo.com/analytics.

**Comment by gajus** [comment]
We now have two new methods:

* [`sql.booleanExpression`](https://github.com/gajus/slonik#sqlbooleanexpression)
* [`sql.comparisonPredicate`](https://github.com/gajus/slonik#sqlcomparisonpredicate)

These are sufficient to describe any boolean expression (e.g. `WHERE` search block) in a safe way.

With this in place, designing `update` and similar methods becomes a lot easier.

**Comment by Sharaal** [comment]
Does I just missread something or does the new tag helper possible/easier, but still complex to define very simple operations?

Something like: 
```sql
UPDATE users SET password = $1 WHERE id = $2
```
are often the mostly needed type of queries in an app.

In the now proposed solution it would be:
```javascript
sql`UPDATE users SET password = ${newPasswordhash} WHERE ${sql.comparisonPredicate('id', '=', $id)}`
```

Or is there something more simple available?

I think it shouldn't be more complex than a:
```javascript
update('users', { password: newPasswordhash }, { id: $id })
```
to be really convenient.

**Comment by gajus** [comment]
@Sharaal This is discussing only dynamically generated queries, which are pretty rare.

For static queries just write:

```js
client.query(sql`
  UPDATE users SET 
    password = ${newPasswordhash} 
  WHERE
    id = ${id}
`)

```

As for the helper, the current API that I am playing around with is:

```js
client.update(
  'user',
  {
    password: newPasswordhash
  },
  sql.booleanExpression([3, 4], 'AND')
);

```

where value bindings can also be SQL tokens, e.g.

```js
client.update(
  'user',
  {
    time: sql.raw('to_timestamp($1)', Date.now())
  },
  sql.booleanExpression([3, 4], 'AND')
);

```

Currently working on 3 abstractions.

Will publish once stable in my own projects.

**Comment by Sharaal** [comment]
That looks very nice and flexible. :)

I suggest to have also for the expression part possible to give an object, all key/value pairs of the object transformed to `sql.comparisonPredicate(key, '=', value)` and joined by `AND`.

So:
```javascript
client.update(
  'user',
  { password: newPasswordhash },
  { id, active: true }
)
```

Is transformed to:
```javascript
client.update(
  'user',
  {
    password: newPasswordhash
  },
  sql.booleanExpression(
    [
      sql.comparisonPredicate('id', '=', id),
      sql.comparisonPredicate('active', '=', true)
    ], 
    'AND'
  )
)
```

**Comment by gajus** [comment]
Decided to release this as a separate library, `slonik-utilities`.

https://github.com/gajus/slonik-utilities

Currently implements two methods:

* `update`; and
* `upsert`

Further discussion should be had there.

Decided against releasing this as part of Slonik because implementation of methods such as `update` and `upsert` are subjective (there are multiple ways to achieve the same result).

Please contribute utility suggestions/ implementations for your requirements.

**Comment by baerrach** [comment]
`sql.booleanExpression` was removed in favour of `sql.join` but the article has not been updated.

See [feat: remove multiple methods in favor of sql.join ](https://github.com/gajus/slonik/commit/910177db4e8bdb8f2d2b4a9e82bd017044a6801d)

The doc link is now https://github.com/gajus/slonik#slonik-query-building-sql-join

**Comment by acro5piano** [comment]
Is there any way to convert object to `update` statement?

like

```sql
const params = { name: 'foo', email: 'foo@example.com',  /* ... */ }

pool.query(sql`
  update users set ${sql.xxxxx(params)} where id = 1
`)
```

Sorry I'm missing something.

**Comment by cskeogh** [comment]
> Is there any way to convert object to `update` statement?

I think this is the right & safe way:

```typescript
pool.query(sql`
      UPDATE users
      SET ${sql.join(Object.entries(obj).map(([key, value]) =>
        sql`${sql.identifier([key])} = ${value}`), sql`,`)}
      WHERE id = 1
    `);
```

**Comment by gajus** [comment]
See https://github.com/gajus/slonik/issues/411 for my latest thoughts on the subject.
