### ISSUE TITLE
error: syntax error at or near "$1" when trying to drop db

### ISSUE THREAD

**Issue by darkbasic** [gajus/slonik#464]
I'm trying to setup Jest globalSetup with Postgres Template Databases to run each worker on its own database, according to https://dev.to/walrusai/testing-database-interactions-with-jest-519n

That means running something like:

```
for (let i = 1; i <= workers; i++) {
  const workerDbName = `${dbName}_${i}`;
  await pool.query(sql.unsafe`DROP DATABASE IF EXISTS ${workerDbName};`);
  await pool.query(
    sql.unsafe`CREATE DATABASE ${workerDbName} TEMPLATE ${dbName};`
  );
}
```

That fails with the following error:

```
error: syntax error at or near "$1"
    at Parser.parseErrorMessage (/home/niko/devel/beach-server/node_modules/pg-protocol/dist/parser.js:287:98)
    at Parser.handlePacket (/home/niko/devel/beach-server/node_modules/pg-protocol/dist/parser.js:126:29)
    at Parser.parse (/home/niko/devel/beach-server/node_modules/pg-protocol/dist/parser.js:39:38)
    at Socket.<anonymous> (/home/niko/devel/beach-server/node_modules/pg-protocol/dist/index.js:11:42)
    at Socket.emit (node:events:513:28)
    at addChunk (node:internal/streams/readable:324:12)
    at readableAddChunk (node:internal/streams/readable:297:9)
    at Readable.push (node:internal/streams/readable:234:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
    at TCP.callbackTrampoline (node:internal/async_hooks:130:17) {
  length: 91,
  severity: 'ERROR',
  code: '42601',
  detail: undefined,
  hint: undefined,
  position: '25',
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'scan.l',
  line: '1188',
  routine: 'scanner_yyerror',
  notices: []
}
```

I expected it might have failed so I've tried with `slonik-sql-tag-raw`:

```
for (let i = 1; i <= workers; i++) {
  const workerDbName = `${dbName}_${i}`;
  await pool.query(sql.unsafe`DROP DATABASE IF EXISTS ${raw("$1", [workerDbName])};`);
  await pool.query(
    sql.unsafe`CREATE DATABASE ${workerDbName} TEMPLATE ${dbName};`
  );
}
```

But even with `raw` it fails with the same error.

The same query without the variable works flawlessly:
```
sql.unsafe`DROP DATABASE IF EXISTS "jest_1";`
```

## Expected Behavior
It should be possible to use variables with DROP, at least using `slonik-sql-tag-raw`.

## Current Behavior

```
error: syntax error at or near "$1"
```

## Steps to Reproduce

```
const workerDbName = "jest_1";
await pool.query(sql.unsafe`DROP DATABASE IF EXISTS ${workerDbName};`);
```

or

```
const workerDbName = "jest_1";
await pool.query(sql.unsafe`DROP DATABASE IF EXISTS ${raw("$1", [workerDbName])};`);
```

**Comment by gajus** [comment]
https://github.com/gajus/slonik#user-content-slonik-query-building-sql-identifier

**Comment by darkbasic** [comment]
Thanks, that worked. I've read the whole documentation twice but somehow I missed that one. Is it expected that you won't be able to achieve the same with `slonik-sql-tag-raw`? I've just upgraded a 2 years old codebase and there has been a lot of breakage, mostly on `slonik-sql-tag-raw` (which the project made a HUGE use of in its helper libraries). Now that it should be possible to achieve everything without it I'm planning to get rid of it, but it will be a slow process. I like the new typing system and I'm currently working on automatically generating the zod types from the ORM entities (I do use both Slonik and an ORM, with custom libraries to convert Slonik queries into ORM objects so that I can use the ORM all over the app while leveraging Slonik for the most complex queries). There are just a couple of things which drive me mad about the new typing system, but I'll open a separate bug.
