### ISSUE TITLE
Allows you to work with stored procedure

### ISSUE THREAD

**Issue by ArthurQR98** [gajus/slonik#469]
I am currently working with a database already managed by another team and it has given me some stored procs to run and I need to know if you can make use of that with the current tool.

## Desired Behavior
This is how sequelize does it
Created procedure

```
sequelize.query(`
  CREATE PROCEDURE insert_data(a integer, b integer)
  LANGUAGE SQL
  BEGIN ATOMIC
    INSERT INTO tbl VALUES (a);
    INSERT INTO tbl VALUES (b);
  END;
`);
Call procedure
sequelize.query(`CALL insert_data(:a, :b);`, {
  replacements: {
    a: 1,
    b: 2,
  },
});
```

## Motivation
I haven't tried it with your tool yet, but I don't see it described in the documentation, which is why I'm making this query.

**Comment by gajus** [comment]
This already works as expected using Slonik. You most likely just want to use `connection.query`
