### ISSUE TITLE
Configurable `pg.Pool`

### ISSUE THREAD

**Issue by yenbekbay** [gajus/slonik#47]
Hi! Great work on the library 👍 

Are you open to allowing [`pg.Pool`](https://github.com/gajus/slonik/blob/master/src/factories/createPool.js#L52) to be passed in as an argument to `createPool`? In my case, that would allow me to share the same connection pool between [TypeORM](https://github.com/typeorm) and Slonik.

**Comment by gajus** [comment]
This sounds like a reasonable use case, but I am reluctant to expose any internals. (I am considering to move pg-pool logic to Slonik.)

Assuming that TypeORM is compatible with node-postgres, perhaps it would be simpler to create a node-postgres compatible Slonik abstraction?

I would imagine it would be simply:

```js
const createTypeOrmConnectionPool = (slonikPool) => {
  return {
    query: (query, values) => {
      return slonikPool.query(sql`sql.raw(query, values)`);
    };
  };
};

```

**Comment by gajus** [comment]
Closing this as there is a workaround (suggested in the previous comment).

Please use :+1: on the main issue to express your interest to re-open the issue.

**Comment by mikeroelens** [comment]
@yenbekbay Did you end up doing something like @gajus suggestion? I'm looking to try something like `createTypeOrmConnectionPool` and was just wondering if you had a full snippet handy that implements all of `pg.Pool`'s functions 😃

**Comment by gajus** [comment]
> @yenbekbay Did you end up doing something like @gajus suggestion? I'm looking to try something like createTypeOrmConnectionPool and was just wondering if you had a full snippet handy that implements all of pg.Pool's functions 😃

What methods are you missing, though?

**Comment by mikeroelens** [comment]
I haven't really looked too deeply into this, but I was just referencing the Typescript definition and figured I'd have to implement all methods:

```typescript
export class Pool extends events.EventEmitter {
    // `new Pool('pg://user@localhost/mydb')` is not allowed.
    // But it passes type check because of issue:
    // https://github.com/Microsoft/TypeScript/issues/7485
    constructor(config?: PoolConfig);

    readonly totalCount: number;
    readonly idleCount: number;
    readonly waitingCount: number;

    connect(): Promise<PoolClient>;
    connect(callback: (err: Error, client: PoolClient, done: (release?: any) => void) => void): void;

    end(): Promise<void>;
    end(callback: () => void): void;

    query<T extends Submittable>(queryStream: T): T;
    query(queryConfig: QueryArrayConfig, values?: any[]): Promise<QueryArrayResult>;
    query(queryConfig: QueryConfig): Promise<QueryResult>;
    query(queryTextOrConfig: string | QueryConfig, values?: any[]): Promise<QueryResult>;
    query(queryConfig: QueryArrayConfig, callback: (err: Error, result: QueryArrayResult) => void): Query;
    query(queryTextOrConfig: string | QueryConfig, callback: (err: Error, result: QueryResult) => void): Query;
    query(queryText: string, values: any[], callback: (err: Error, result: QueryResult) => void): Query;

    on(event: "error", listener: (err: Error, client: PoolClient) => void): this;
    on(event: "connect" | "acquire" | "remove", listener: (client: PoolClient) => void): this;
}
```

I guess technically you would just have to implement the methods that are necessary to your application. In my case I was exploring using slonik within Postgraphile. So I'd have to see which methods it used. Just figured it'd be safest to implement all.

**Comment by audionerd** [comment]
I’d like to use the `slonik` pool from another library (`connect-pg-simple`). I think a simple adapter using `slonik-sql-tag-raw` will work:

```
import { raw } from 'slonik-sql-tag-raw'
import util from 'util'

const slonikPoolToConnectPgSimplePool = pool => ({
  query: util.callbackify(
    async (query, params) =>
      await pool.query(raw(query, params))
  )
})
```

Is there a better/simpler way?
