### ISSUE TITLE
Initial connection to setup the pool is missing retries

### ISSUE THREAD

**Issue by valeneiko** [gajus/slonik#472]
When creating the initial connection with `setupClient` ([here](https://github.com/gajus/slonik/blob/main/src/factories/createPool.ts#L61-L69)), if any error occurs (e.g. timeout) connection is not retried and pool creation fails.

## Expected Behavior
Initial connection is retied the same way pool connection are:
https://github.com/gajus/slonik/blob/main/src/factories/createConnection.ts#L105-L138

## Current Behavior
If PG client fails to connect, error from `pg` is thrown.

## Possible Solution
Wrap creating `setupClient` and `setupClient.connect()` in a retry loop.

## Steps to Reproduce
1. Create a pool, in a way that is unlikely to succeed
   ```ts
   await createPool(..., {connectionTimeout: 1});
   ```
2. Observe connection timeout error thrown

**Comment by gajus** [comment]
Thank you
