### ISSUE TITLE
connectionRetryLimit is off-by-one

### ISSUE THREAD

**Issue by valeneiko** [gajus/slonik#473]
When `connectionRetryLimit` is provided the number of connection attempts is lower than expected.

## Expected Behavior
When trying to establish a connection, the process is attempted `connectionRetryLimit+1` times.
Initial attempt + `connectionRetryLimit` retries.

## Current Behavior
When trying to establish a connection, the process is attempted `connectionRetryLimit-1` times.
Initial attempt + `connectionRetryLimit - 2` retries.

## Possible Solution
- Initialize `remainingConnectionRetryLimit` to `connectionRetryLimit` to account for inital attempt.
  ```diff
  // https://github.com/gajus/slonik/blob/main/src/factories/createConnection.ts#L105
  --- let remainingConnectionRetryLimit = clientConfiguration.connectionRetryLimit;
  +++ let remainingConnectionRetryLimit = clientConfiguration.connectionRetryLimit + 1;
  ```
- Fix the retry condition:
  ```diff
  // https://github.com/gajus/slonik/blob/main/src/factories/createConnection.ts#L130
  --- if (remainingConnectionRetryLimit > 1) {
  +++ if (remainingConnectionRetryLimit > 0) {
  ```

## Steps to Reproduce
```ts
// https://github.com/gajus/slonik/blob/main/src/factories/createConnection.ts#L105-L138
let attempt = 0;
let remainingConnectionRetryLimit = clientConfiguration.connectionRetryLimit;

// eslint-disable-next-line no-constant-condition
while (true) {
  remainingConnectionRetryLimit--;
  attempt++;

  if (remainingConnectionRetryLimit > 1) {
    console.log('retrying connection');
    continue;
  } else {
    break;
  }
}

console.log(`attempt = ${attempt}`);
```

**Comment by gajus** [comment]
Thanks!
