### ISSUE TITLE
PgClient may leak database connections if `createTypeOverrides` raises an error

### ISSUE THREAD

**Issue by wokkaflokka** [gajus/slonik#475]
`createPool` initiates a `PgClient` and opens a connection before calling `createTypeOverrides`. If `createTypeOverrides` raises an error, `setupClient.end()` is never called on the `PgClient` instance (`setupClient`). We have observed database connection leaks that originate from this behavior.

https://github.com/gajus/slonik/blob/f73d66050ec1b8fbc22e9b832ff92928bb6da377/src/factories/createPool.ts#L61-L78

## Expected Behavior

Always release the connection acquired by the `setupClient` instance by attempting to call `.end()` in a `try/finally`.

Continue to allow underlying exception to raise.

## Current Behavior
Exception from `createTypeOverrides` raises and `setupClient` is left in an indeterminate state.

## Possible Solution

Guard `createTypeOverrides` with a `try/finally`.

## Steps to Reproduce

```
await createPool('postgresql://...', {
    typeParsers: [{
        name: 'foo_bar_baz',
        parse: (value) => value,
    }],
});
```

## Logs

```
INFO Connecting to database...
Error: Database type "foo_bar_baz" not found.
    at createTypeOverrides (/home/runner/work/node_modules/slonik/dist/src/routines/createTypeOverrides.js:19:19)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at createPool (/home/runner/work/node_modules/slonik/dist/src/factories/createPool.js:40:27)
```

**Comment by gajus** [comment]
Thank you for submitting the fix.
