### ISSUE TITLE
No error is thrown even though unknown key is returned

### ISSUE THREAD

**Issue by lorentzlasson** [gajus/slonik#478]
## Expected Behavior
An error to be thrown according to [this documentation](https://github.com/gajus/slonik#unknown-keys)

## Current Behavior
No error is thrown and object is returned without the unknown key.

## Steps to Reproduce
1. Install
    - slonik: 33.1.4
    - zod: 3.21.4 (tried 3.0.0 as well)

2. Run this code (put together from docs, mostly [this](https://github.com/gajus/slonik#result-parser-interceptor))

```ts
import { z } from "zod";
import { createPool, Interceptor, QueryResultRow, sql } from "slonik";

const createResultParserInterceptor = (): Interceptor => ({
  transformRow: (executionContext, _actualQuery, row) => {
    const { resultParser } = executionContext;

    if (!resultParser) {
      return row;
    }

    const validationResult = resultParser.safeParse(row);

    if (!validationResult.success) {
      throw new Error("fail");
    }

    return validationResult.data as QueryResultRow;
  },
});

const interceptors = [createResultParserInterceptor()];

const main = async () => {
  const pool = await createPool(
    "postgresql://postgres:foo@localhost:5432/game",
    {
      interceptors,
    }
  );
  try {
    const x = await pool.one(sql.type(z.object({ foo: z.string() }))`
      select 'bar' as foo, 'baz' as qux
    `);
    console.log(x);
  } catch (e) {
    console.error(e);
  }

  await pool.end();
};

main();
```

## Logs
> { foo: 'bar' }

(no time to add ROARR_LOG now, but can do later if needed)

**Comment by gajus** [comment]
Relavant documentation:

* https://github.com/colinhacks/zod#passthrough
* https://github.com/colinhacks/zod#strict

You are not setting either, which simply emits the unknown property.

**Comment by lorentzlasson** [comment]
Yes strict was missing, thanks. Thinking that detail would be helpful to add to this readme section: https://github.com/gajus/slonik#unknown-keys
