### ISSUE TITLE
Support for sqlcommenter: Option to Not Strip SQL Comments

### ISSUE THREAD

**Issue by mgreenw** [gajus/slonik#480]
I am trying to setup [`sqlcommenter`](https://google.github.io/sqlcommenter/) in my project for use in a GCP project so that I can see queries annotated by tag. In order to dynamically add comments I ended up needing `slonik-sql-tag-raw` (a valid use case!) but eventually realized that all comments are being stripped from the final sql (commit: https://github.com/gajus/slonik/commit/8c505b2991e6dbba290bb91a743fbe65d7736ee8).

## Desired Behavior
Ideally, there would be a way to opt out of this comment-stripping behavior, either globally or per-query. Perhaps this could be done with a new `sql` method? Or, it would be neat if `sqlcommenter` format was supported directly, but I understand that its pretty specific requirement.

## Motivation
Currently, all comments are stripped from the final sql using `pg-minify`, but in some cases its necessary to include comments in the final sql so that database engines can tag queries. This is very useful when trying to monitor query performance.

**Comment by gajus** [comment]
Non-issue.
