### ISSUE TITLE
Bulk inserts using unnest won't allow jsonb columns

### ISSUE THREAD

**Issue by opsb** [gajus/slonik#481]
## Expected Behavior

Multiple rows are inserted using unnest into a table that has a jsonb column.

## Current Behavior

The following code
```javascript
const result = pool.connect(async (connection) => {
  const query = sql.unsafe`
        insert into issues (id, data)
        select * from ${sql.unnest([[1, sql.jsonb({a: 1})]], ['id', 'jsonb'])}
    `;
  return await connection.any(query);
});
```

fails to compile with the type error
```
Type 'JsonBinarySqlToken' is not assignable to type 'PrimitiveValueExpression'.ts
```

## Possible Solution

Postgres does allow jsonb to be inserted using unnest so it seems the type constraint is too narrow here. 

## Steps to Reproduce
As mentioned above the following code will produce a type error
```javascript
const result = pool.connect(async (connection) => {
  const query = sql.unsafe`
        insert into issues (id, data)
        select * from ${sql.unnest([[1, sql.jsonb({a: 1})]], ['id', 'jsonb'])}
    `;
  return await connection.any(query);
});
```

**Comment by gajus** [comment]
Off-topic, but I generally don't recommend using `unnest` anymore.

`jsonb_to_recordset` is my go-to way these days.

https://contra.com/p/P7kB2RPO-bulk-inserting-nested-data-into-the-database-part-ii

**Comment by opsb** [comment]
Hey @gajus, thanks for the speedy response. That's a really nice approach for bulk inserts, just tried it out for my case and it works great!

**Comment by gajus** [comment]
I will close this issue and instead work on updating documentation. Realistically, there are no good use cases (that I am aware of) where `unnest` should be preferred over the recordset approach.
