### ISSUE TITLE
v33.0.10 introduces breaking change

### ISSUE THREAD

**Issue by nathanchapman** [gajus/slonik#483]
The switch to using `strict: true` with `safe-stable-stringify` introduces a breaking change on a patch version

Breaking changes:
https://github.com/gajus/slonik/pull/461
https://github.com/gajus/slonik/compare/v33.0.9...v33.0.10

While I agree with throwing on circular references and unrepresentable JSON values, this change breaks usages of class instances like [Decimal.js](https://github.com/MikeMcl/decimal.js/), which worked prior to this version. We prefer to pass instances of Decimals around, rather than having to convert to/from specific string/number representations

This is just one example of many possible failures (e.g. `moment` would be another one that comes to mind)

**Comment by gajus** [comment]
Not going to revert it, but I agree that it should have been a breaking change.

**Comment by nathanchapman** [comment]
so.. we're just stuck with this patch forever? no path forward?

```
diff --git a/node_modules/slonik/dist/utilities/safeStringify.js b/node_modules/slonik/dist/utilities/safeStringify.js
index 018910c..31816e2 100644
--- a/node_modules/slonik/dist/utilities/safeStringify.js
+++ b/node_modules/slonik/dist/utilities/safeStringify.js
@@ -5,7 +5,7 @@ const safe_stable_stringify_1 = require("safe-stable-stringify");
 const stringify = (0, safe_stable_stringify_1.configure)({
     bigint: true,
     circularValue: '[Circular]',
-    strict: true,
+    strict: false,
 });
 const safeStringify = (subject, replacer, space) => {
     const result = stringify(subject, replacer, space);
```
