### ISSUE TITLE
Improve Syntax Error Logging Output

### ISSUE THREAD

**Issue by pablosproject** [gajus/slonik#489]
## Desired Behavior
Not sure if this is on the shoulder of this library or on `node-postgres`, but I wanted to check if there's a better way to log errors, especially syntax errors.
In case of some errors, here is what I got from the logs:

```
    error: syntax error at or near "WHERE"

      at Parser.parseErrorMessage (node_modules/pg-protocol/src/parser.ts:369:69)
      at Parser.handlePacket (node_modules/pg-protocol/src/parser.ts:188:21)
      at Parser.parse (node_modules/pg-protocol/src/parser.ts:103:30)
      at Socket.<anonymous> (node_modules/pg-protocol/src/index.ts:7:48)
```

It's not very useful to identify the query that caused the issue as we don't know from which file it actually comes.

## Motivation
Better logging and developer experience

## Implementation
Maybe provide options to configure underlying parser behavior to output at least the file name that has issues?

**Comment by pablosproject** [comment]
Hi @gajus, thanks for your reply. In fact, that is part of a long set of queries that get executed during a transaction, and there are multiple where clauses, it's hard to identify which one is failing.

I can work around that by copy-pasting it in something like DBEaver and executing it and signaling the place where it has issues, but I just wanted to check if there's something we can get out of `pg-node` parser.

**Comment by gajus** [comment]
The error log includes `queryId` which tells you exactly which query produced the error.

https://github.com/gajus/slonik#logging

That being said.. I agree that this should be added to error itself.
