### ISSUE TITLE
Insert not available on pool?

### ISSUE THREAD

**Issue by mikl** [gajus/slonik#49]
I noticed that while most of the query methods are available directly on the pool object, is this intentional?

If just doing a single insert, and thus not needing transactions or anything, it would be practical to just be able to call 
```
      await pool.insert(sql`
        INSERT INTO example
          (name, created)
          VALUES (${name}, CURRENT_TIMESTAMP)
      `)
```

instead of what's currently required:

```
      pool.connect(async (connection) => {
        await connection.insert(sql`
          INSERT INTO example
            (name, created)
            VALUES (${name}, CURRENT_TIMESTAMP)
        `)
      })
```

I may have missed something, is there a reason that getting a connection is required for insert, but not the other query methods?

**Comment by gajus** [comment]
There is no such method as `insert`. You probably want `query`.

**Comment by gajus** [comment]
Where did you find `insert` method documented?

**Comment by mikl** [comment]
@gajus it's here: https://github.com/gajus/slonik#slonik-query-methods-insert (and the method does exist on the connection object, the second example is working).

**Comment by gajus** [comment]
Huh, how did that slip through countless of documentation reviews is beyond me.

There is definitely no method "insert" on connection.

* https://github.com/gajus/slonik/blob/master/src/binders/bindPool.js
* https://github.com/gajus/slonik/blob/master/src/binders/bindTransactionConnection.js

I would check if you perhaps have some really old version of Slonik.

"insert" was removed long time ago.

There is simply no need for it.

Just use:

```js
await connection.oneFirst(sql`
  INSERT INTO example (name, created)
  VALUES (${name}, CURRENT_TIMESTAMP)
  RETURNING id
`)

```
