### ISSUE TITLE
Improve documentation on when and why should we use `pool.connect(connection => { ... })`

### ISSUE THREAD

**Issue by latobibor** [gajus/slonik#503]
When we were updating `slonik` version we were checking for breaking changes and we got confused over this part of the documentation:

https://github.com/gajus/slonik#protecting-against-unsafe-connection-handling

```typescript
// This is not valid Slonik API

const main = async () => {
  const connection = await pool.connect();

  await connection.query(sql.typeAlias('foo')`SELECT foo()`);

  await connection.release();
};
```

In this case it is unclear that using `query` directly is not a valid way to use Slonik and/or the fact that if `query` fails then `connection.release()` is never called.

Why do I need to release the connection after a query anyways when in an average scenario I run an always-on backend service?

The other unclear part of the documentation is this:

> If you do not require having a persistent connection to the same backend, then you can directly use pool to run queries, e.g. `pool.query(sql.typeAlias('id')`SELECT 1 AS id`);`

> Beware that in the latter example, the connection picked to execute the query is a random connection from the connection pool, i.e. using the latter method (without explicit `connect()`) does not guarantee that multiple queries will refer to the same backend.

In this case the terminology confuses me: what do we mean by `backend` then if not the `backend service` that runs and executes queries on the connected database?

I think it is implied by "persistent connection to the same backend" that the _other_ method, the one with `pool.connect(connection => { ... })` should be used for this, but there the documentation says that the connection is closed after the query was run, therefore that connection is also not `persistent`.

As a mostly frontend developer occasionally working on backend these parts of the documentation do not give me any clarity.

## Desired Behavior
The documentation should be clear about what is the preferred way of creating connections and executing queries with `slonik` explained through examples of typical scenarios for instance an average backend service that queries and updates data constantly in 1 connected database.

## Motivation
People use `slonik` with varying knowledge of best practices (security/safety/etc.). The before mentioned parts of the documentation is unclear to many of us, and leaves you wondering what should you use if you don't have special requirements. Should we use the wrapped `pool.connect(connection => {...})`, or stick to the simple `pool.query`/`pool.many`, etc. functions.

Therefore a bit of context and clarification could benefit folks who are not so DB-savvy.

**Comment by gajus** [comment]
I read and re-read your comment and I still cannot wrap my head around what you are asking of which part is not clear.

How to create a connection?

```ts
await pool.connect(async (connection) => {
  // This is your connection object:
  // connection;
});
```

**Comment by firxworx** [comment]
I too have read and re-read too and I think I understand where @latobibor is coming from. 

The note about being primarily a front-end dev helped me understand the perspective (or at least I think so, please let me know!).

@latobibor my friend I think you are thinking of back-end vs. front-end in the classic web development HR resume keyword sense i.e. backend is like Express app and client aka front-end is like React.

From that angle, yeah, wtf!.

To adjust your angle, forget that web browsers even exist and put yourself in a database library's shoes. Also I think it is helpful to consider why the variable and type names are "pool", "DatabasePool", etc. 

A _client_ connection is between a database client and either the database / database cluster _or_ the database cluster’s connection pool (such as pgbouncer). Whenever anything connects to postgres the server will fork a new process (aka a _backend_ to postgres DBA's) to handle it.

Its common to use postgres with connection pool managers like pgbouncer or pgpool-II. You can read a bit about those here (Neon is a postgres provider and at this link they explain how they use pgbouncer): https://neon.tech/docs/connect/connection-pooling

Now imagine you are the mighty @gajus who created slonik for serious CTO level IT problems at scale and you think in terms of database clusters, connection pools, multiple backend database servers (master / slave etc.), replication, etc., etc. The big guns!

In this light it is a very good warning in the docs that you might _require a persistent connection to the same backend_ depending on what setup you have.

I think realistically you will always want to use this syntax so the connection is automatically released:

```
pool.connect(async (connection) => {
  await connection.query(sql.typeAlias('id')`SELECT 1 AS id`);
});
```

However... now imagine your Node/Express backend (i.e. backend in the context I think you originally had in mind) and imagine you have split up your code to have different repositories, services, etc. 

Now imagine the lifecycle of _servicing a single request_ where many of those different repositories / services are tapped to service the request (e.g. maybe the request has something to do with auth, users, etc).

If each of those repositories, services, etc in play independently had their own `pool.connect(...)` then each might end up using a different backend (in the context of postgres) and that _could_ be a problem for you. There could be implications with transactions and there could also be extra overhead to grabbing and releasing connections many times.

This is really what the docs are warning you about here. 

Some of the setups I've seen for integrating with Fastify, Express, etc, effectively do a `pool.connect()` at the start of the request and then make the `connection` available throughout the rest of the lifecycle of the request (so then any repositories/services/etc. that follow would use _that same_ connection to avoid potential problems).

I hope I nailed where your point of confusion was and that this answers your question.

--- 

All said, I think your question does raise an important point about the clarity in the docs.

After writing this all I feel I can see how both you and gajus are totally right in your respective understanding of "backend" :)

**Comment by gajus** [comment]
Hope this helps @latobibor https://dev.to/gajus/integrating-slonik-with-expressjs-33kn
