### ISSUE TITLE
Type aliases not validating with Zod?

### ISSUE THREAD

**Issue by Nezteb** [gajus/slonik#505]
## Expected Behavior

Following the docs, I was trying to verify that the Slonik/Zod integration will throw errors when the underlying DB schema doesn't match the defined Zod objects. https://github.com/gajus/slonik#runtime-validation

However, even if I pass a Zod schema that is completely different from the underlying data, I can't get Slonik/Zod to validate the schema and throw an error.

## Current Behavior

The existing database/query schema is not being validated against the Zod objects I have defined and passed.

## Possible Solution

Nothing obvious comes to mind, unless I'm doing something wrong (which is quite possible).

## Steps to Reproduce

I have a `Users` table with an `id` and `name` field. `id` is a UUID, and `name` is a varchar/string.

Given this script:
```typescript
import {
  createPool,
  createSqlTag,
  type DatabaseConnection,
} from "slonik";
import { z } from "zod";

const sql = createSqlTag({
  typeAliases: {
    guid: z.object({
      name: z.number(),
      nonExistent: z.string(),
    }),
  },
});

async function run() {
  const connectionString = process.env.DB_URL ?? "";

  const pool = await createPool(connectionString);

  return pool.connect(async (connection: DatabaseConnection) => {
    const query = sql.typeAlias("guid")`SELECT name AS asdf FROM Users`;
    const result = await connection.many(query);
    console.log(result);
    return result;
  });
}

run();
```

I've also tried things like:
```typescript
const userObject = z.object({
  name: z.number(),
  nonExistent: z.string(),
});

const query = sql.type(userObject)`SELECT name AS asdf FROM Users`;
```

In both cases, I'd expect there to be some sort of validation error because of a missing property and/or an incorrect Zod type specification (name being a string/GUID instead of a number). Instead, I get the following logged data:

```typescript
[
  { asdf: "Noah" },
  { asdf: "Bob" },
  { asdf: "Jennifer" },
  { asdf: "Bender" }
]
```

**Comment by treddy73** [comment]
I had to add this interceptor to make Zod validation work again.

https://github.com/gajus/slonik#result-parser-interceptor

Except, this example is slightly broke because `row` isn't a parameter type that `SchemaValidationError` is expecting ... so I just use `null` for now.

**Comment by firxworx** [comment]
Per the current docs a result parser interceptor is required:

https://github.com/gajus/slonik#runtime-validation
https://github.com/gajus/slonik#result-parser-interceptor

@Nezteb in addition also take note of zod's default behaviour and the option for `strict()` which may better suit your needs if you require more strict validation which is definitely a good practice :)

> By default Zod object schemas strip out unrecognized keys during parsing. You can disallow unknown keys with .strict() . If there are any unknown keys in the input, Zod will throw an error.

https://github.com/colinhacks/zod#strict

**Comment by Nezteb** [comment]
@firxworx Ohhhhhhhh.

> when Zod parsing was first introduced to Slonik, it was enabled for all queries by default

Last time I had used Zod, I think this was the case. My bad for not reading the docs more closely. Thank you!

**Comment by firxworx** [comment]
@treddy73 the type issue you experienced was tracked as #499 and has been resolved:

https://github.com/gajus/slonik/issues/499#issuecomment-1735840688
