### ISSUE TITLE
Potential memory leak when using with the Jest's `--detectLeaks` flag

### ISSUE THREAD

**Issue by ferrata** [gajus/slonik#509]
Hey there!

I stumbled upon this issue while investigating memory leaks in a project using the `Jest`'s `--detectLeaks` flag. While this may be a false positive on the Jest side, I still wanted to report it.

Sample code:

```ts
import { sql } from "slonik";

describe("Dummy test", () => {
  test("should pass", () => {
    // the line below leads to a memory leak error
    // when running `jest` with the `--detectLeaks` flag
    console.log(sql.fragment`SELECT 1`);

    expect(true).toBe(true);
  });
});
```

## Expected Behavior

No memory leaks are detected.

## Current Behavior

Memory leaks are detected.

## Possible Solution

N/A

## Steps to Reproduce

I created [a repository](https://github.com/ferrata/slonik-jest-memory-leak-demo) to reproduce the issue.

1. Clone the repository
2. Run `npm i`
3. Run `npm test`

## Logs

There seem to be no logs generated.

**Comment by gajus** [comment]
I honestly have no clue.

```ts
import { sql } from "slonik";

sql;

describe("Dummy test", () => {
  test("should pass", () => {
    expect(true).toBe(true);
  });
});

```

This test produces the same error.

Investigating.

**Comment by gajus** [comment]
Okay, I narrowed down the issue. It is coming from Roarr.

```ts
import { Roarr } from 'roarr';

describe("Dummy test", () => {
  test("should pass", () => {
    const Logger = Roarr.child({
      package: 'slonik',
    });

    expect(true).toBe(true);
  });
});
```

This is going to be related to https://github.com/gajus/roarr/issues/79

Will continue investigating in that issue thread.

**Comment by gajus** [comment]
Opened an issue with Jest. I am not sure what is causing the memory leak warning or how to mitigate it.

https://github.com/jestjs/jest/issues/14580
