### ISSUE TITLE
BigInt break Jest (`JSON.stringify()`)

### ISSUE THREAD

**Issue by pablosproject** [gajus/slonik#513]
First of all, thanks for the latest bunch of updates on this library.

## Current Behavior
I am experiencing some issues when the recent introduction of `BigInt` types break Jest. (https://github.com/gajus/slonik/commit/690470579a25d7f840ce2ce816da9ec3be90b8dc)

Below you can see the log, which contains the piece of code having issues. I also think that it's common to use `JSON` methods in our Node app, so this can be a breaking change.

I have tried of rolling back to `35.2.1` (the version before the introduction of BigInt issue) and everything is working correctly.

## Logs
```
Node.js v18.15.0
node:internal/child_process/serialization:159
    const string = JSONStringify(message) + '\n';
                   ^

TypeError: Do not know how to serialize a BigInt
    at stringify (<anonymous>)
    at writeChannelMessage (node:internal/child_process/serialization:159:20)
    at process.target._send (node:internal/child_process:838:17)
    at process.target.send (node:internal/child_process:738:19)
    at reportSuccess (/home/runner/work/eba/eba/node_modules/jest-worker/build/workers/processChild.js:82:11)
```

**Comment by gajus** [comment]
The commit that you've linked is marked explicitly as a breaking change.

I am still trying to wrap my head around the code that produce this.

Can you share what query/methods were used to produce this error?

p.s. You can also revert the old behavior by simply overriding `bigintParser`.

**Comment by pablosproject** [comment]
Oh, sorry I missed the breaking change. It's hard to indicate where it happen since that line is the only one coming out of any test case output.

I have some setup scripts, but those run directly on `pg`, so no idea. I may override `bigintParser` if I am the only one having this issue.

**Comment by gajus** [comment]
I could not replicate this issue.

Regardless, closing in favor of https://github.com/gajus/slonik/issues/515
