### ISSUE TITLE
Document `originalError` rename to `cause`

### ISSUE THREAD

**Issue by flevi29** [gajus/slonik#516]
I can see that at some point [`originalError`](https://github.com/gajus/slonik#original-node-postgres-error) was included, however I can no longer find a property named as such in `errors.ts`, and can find [`cause`](https://github.com/tc39/proposal-error-cause). I am all for this change, however the documentation wasn't updated to reflect the change, if I'm not wrong.

**Comment by gajus** [comment]
That's odd. It was introduced in the commit 63443313230cf22aebf9fdbf6834cf2fa1edf8c8

The commit itself describes the necessary information to mark this as a breaking change to `semantic-release`. I am not clear why it is not listed in the release log.
