### ISSUE TITLE
Transform example is not working

### ISSUE THREAD

**Issue by gjuchault** [gajus/slonik#523]
## Expected Behavior
Copy-pasting the example from the `Transforming` section in the README, I expect my zod transforms to be called

## Current Behavior

I'm getting no `"transform"` call and the result looks like this: `{ foo: '1,2' }`

## Steps to Reproduce

Using: `zod@3.22.4`, `slonik@37.2.0`, `pg@8.11.3` (slonik dependency only), `PostgreSQL 14.9 (Debian 14.9-1.pgdg120+1) on aarch64-unknown-linux-gnu, compiled by gcc (Debian 12.2.0-14) 12.2.0, 64-bit` (docker) 

```ts
const coordinatesType = z.string().transform((subject) => {
  console.log("transform");
  const [
    x,
    y,
  ] = subject.split(',');

  return {
    x: Number(x),
    y: Number(y),
  };
});

const zodObject = z.object({
  foo: coordinatesType,
});

const query = sql.type(zodObject)`SELECT '1,2' as foo`;

const result = await pool.one(query);
console.log(result);
```

## Logs

```
{ foo: '1,2' }
[10:04:12.692]:
    context: {
      "package": "slonik",
      "poolId": "2f7bd847",
      "logLevel": 20,
      "stats": {
        "idleConnectionCount": 0,
        "totalConnectionCount": 1,
        "waitingRequestCount": 0
      }
    }
    message: "client is checked out from the pool"
    sequence: "15"
    version: "2.0.0"
```

**Comment by gajus** [comment]
I am guessing you did not add `transformRow` interceptor.

https://github.com/gajus/slonik?tab=readme-ov-file#result-parser-interceptor
