### ISSUE TITLE
Backwards compatibility with old sql tag

### ISSUE THREAD

**Issue by timlesallen** [gajus/slonik#527]
We are stuck on version `30.x` and might be unlikely to put the effort in to migrating.  But ideally we'd like to utilise `sql.unsafe`, `sql.fragment` in new code and have access to other fixes/enhancements.  

## Desired Behavior
It would be good if `sql` could just be an alias to `sql.unsafe`.

## Motivation
To enable us to upgrade to the latest version without having to touch a lot of our codebase.

## Implementation
Make `sql` mean `sql.unsafe`.

**Comment by gajus** [comment]
Just replace all `` sql` `` with `` sql.unsafe` ``

**Comment by mmkal** [comment]
@gajus sql.unsafe is not a replacement unless you merge https://github.com/gajus/slonik/pull/512
