### ISSUE TITLE
Allow to override sql.assignmentList snake-case normalisation

### ISSUE THREAD

**Issue by gajus** [gajus/slonik#53]
`sql.assignmentList` converts object keys to snake-case, e.g.

```js
await connection.query(sql`
  UPDATE foo
  SET ${sql.assignmentList({
    barBaz: sql.raw('to_timestamp($1)', ['qux']),
    quuxQuuz: sql.raw('to_timestamp($1)', ['corge'])
  })}
`);

```

Produces:

```js
{
  sql: 'UPDATE foo SET bar_baz = to_timestamp($1), quux_quuz = to_timestamp($2)',
  values: [
    'qux',
    'corge'
  ]
}

```

This behaviour might be sometimes undesirable.

Add a way override this behaviour.

**Comment by Sharaal** [comment]
I suggest using the keys like they are given in the object and add always `"` around all identifiers (and of course replace all `"` with `""` first to secure them against SQL injection if it's not already done). :)

**Comment by n1ru4l** [comment]
I agree with @Sharaal  that the table names should not be snake-case'd

I know that using snake-case keys for table and column names is the best practise.

On the other hand, it is also tedious to alias every column name to a camelCase key when selecting data. That's the reason why I personally use camelCase for my table and column names.

Would you accept a pull request for this (breaking) change?

**Comment by gajus** [comment]
What change are you proposing?

**Comment by n1ru4l** [comment]
Disable applying snake-case here:

https://github.com/gajus/slonik/blob/dbe40d4354ba99b0ed76245d11c4326848110959/src/utilities/normalizeIdentifier.js#L8

AND/OR

Allow overwriting `normalizeIdentifier` to a passthrough function

e.g.

```js
const slonik = createPool(connectionUri, {
  normalizeIdentifier: identifier => identifier // or identifier => snakeCase(identifier) depending on the default
});
```

**Comment by gajus** [comment]
> Allow overwriting normalizeIdentifier to a passthrough function

That is more or less the current plan. Except, instead of `createPool` it should be `createSqlTag`. It is on my TODO list. Give it a day and I will push it out.

**Comment by gajus** [comment]
@n1ru4l Now PRs are welcome if you have further improvements to `createSqlTag`.
