### ISSUE TITLE
Partial<>'s Not Valid for SerializableValue

### ISSUE THREAD

**Issue by albertreed** [gajus/slonik#535]
`Partial` types are not valid `SerializableValue`'s

## Expected Behavior
Objects of type `Partial<{foo: number}>;` should be a valid parameter to `sql.json`

## Current Behavior
Typescript reports an error.

## Possible Solution
```
export type SerializableValue =
  | SerializableValue[]
  | boolean
  | number
  | string
  | readonly SerializableValue[]
  | Partial<{
      [key: string]: SerializableValue;
    }>
  | null;
```

Note, this used to read
```
export type SerializableValue =
  | SerializableValue[]
  | boolean
  | number
  | string
  | readonly SerializableValue[]
  | {
      [key: string]: SerializableValue | undefined;
    }
  | null;
```

but that was removed in https://github.com/gajus/slonik/commit/fcfa0fe97f2265c1df61c8578f22d77e8c393b0c, though that might have been for a good reason.

**Comment by gajus** [comment]
https://github.com/gajus/slonik/issues/222

**Comment by albertreed** [comment]
I'm not sure - that feels like it shouldn't compile but I think that's different from what we're actually talking about here.

I'm out of my depth here for sure but I'd say:

sql.fragment`SELECT ${sql.json({x: undefined})}`

should do the same thing as 

sql.fragment`SELECT ${sql.json({})}`

(sorry for the poorly-escaped code. couldn't for the life of me figure out how to get markdown to behave)
