### ISSUE TITLE
Improving Runtime Validation Performance through Async Parsing

### ISSUE THREAD

**Issue by janpaepke** [gajus/slonik#539]
Hi @gajus,
as [you noticed yourself](https://github.com/colinhacks/zod/issues/205#issuecomment-1285659801), type validation using zod is fairly CPU hungry.  
I also noticed this, particularly with nested shapes and combined with transforms.

Without optimizing zod, I don't think there's much we can do about this.

There is however another optimisation that can be done with little effort inside of slonik:
**Allowing row transformations to be async**.
This may not decrease CPU load, but will likely make services more responsive, as outlined below.

## Motivation

Recently I noticed large spikes in the Eventloop lag in our production environment (upwards of 4 seconds).
This is obviously bad, since it blocks any other requests to the service from being processed.

I was able to track the origin down to a sync operation which had both: A complex result shape (nested jsonb) as well as a relatively large dataset. 
At 0.2 -  1ms parsing time per row, the numbers quickly grew.

As a solution I used `.stream()`, rather than `many()`.

This had two effects: The operation was spread over a longer period (which was fine), but more importantly the parsing was done asynchronously, in batches, which meant it didn't freeze up the service.

## Implementation

After looking into this some more, I noticed that all row transformations are processed synchronously in `executeQuery`.  
From what I can tell, there is really no reason for this, as `executeQuery` is obviously async already.

So here's my Proposal:
1. Change the result type of `transformRow` to `MaybePromise<QueryResultRow>`.
2. in `executeQuery` map over rows and use `Promise.all` **(see below)**
3. in `stream` update the `transform` function passed into `Transform` to do the same and make it async: `async transform(datum, enc, callback)`. As far as I can tell this will not change the behaviour and will call `callback();` once all rows have been asynchronously transformed.
4. add tests for promise results of `transformRow`.
5. update docs to recommend `z.safeParseAsync` over `z.safeParse`: `const validationResult = await resultParser.safeParseAsync(row);`

This is how I'd process the transformations in `executeQuery`:
```ts
for (const interceptor of interceptors) {
  if (interceptor.transformRow) {
    const { transformRow } = interceptor;
    const { fields } = result;

    const rows: QueryResultRow[] = await Promise.all(
      result.rows.map(
        row => transformRow(executionContext, actualQuery, row, fields)
      )
    );

    result = {
      ...result,
      rows,
    };
  }
}
```

This change would be fully backwards compatible.

A different possibility to implement this would be to add a `transformRowAsync` interceptor rather than returning MaybePromise from the existing method.

If you agree this is a good idea, I could give this a shot and make a PR.

**Comment by gajus** [comment]
Thank you!

**Comment by janpaepke** [comment]
I noticed that the changes are not part of the [release notes](https://github.com/gajus/slonik/releases/tag/v37.3.0).

This might be relevant to people, when updating.

**Comment by gajus** [comment]
Added manually.

**Comment by gajus** [comment]
Flagging that async version appears to have performance/memory management issues:

https://github.com/colinhacks/zod/issues/3446

**Comment by janpaepke** [comment]
very interesting. But as far as I understand this should self-resolve with the release of zod 4?
From the perspective of slonik it still feels "correct" to use async here?

**Comment by gajus** [comment]
For what it is worth, we removed async handling and saw a notable (~15%) decrease in response times.

So, I would not recommend it if response time is what you are optimizing for.

Do note that we might be an outlier as we are processing very large number of queries for every request.

**Comment by janpaepke** [comment]
I vaguely remember that we had issues with very slow parsing (4s+) for a query returning a large amount (15k records) of nested json data.

We solved this by chunking the result using `.stream()`.
