### ISSUE TITLE
How to force SSL Mode?

### ISSUE THREAD

**Issue by OllieJennings** [gajus/slonik#55]
`Slonik` is great BTW.

Only issue is when am trying to use it to connect to an `Heroku` database from AWS `Lambda`.

Every attempt results in SSL off, meaning the connection failed (I have tried added `?sslmode=require` to the connectionString with no luck).

If l use `PG` with the `ssl: true` config then l can successfully connect to the DB, is there any way to have this in `Slonik`?

**Comment by gajus** [comment]
`?ssl=1`

**Comment by kayvaninvemo** [comment]
Now we should use  `sslmode=no-verify` or `sslmode=require`  according to [Documentation](https://github.com/gajus/slonik#connection-uri)
