### ISSUE TITLE
Cannot use $1 or $\d+ in nested SQL fragments

### ISSUE THREAD

**Issue by alxndrsn** [gajus/slonik#553]
More general version of https://github.com/gajus/slonik/issues/548.

Test cases at https://github.com/gajus/slonik/pull/552.

I appreciate per https://github.com/gajus/slonik/issues/548 that this is a design decision, so feel free to close immediately.  I think it's helpful to have here as documentation in case others run into this issue in future.  Also I may be mis-using the API?

## Observed

Cannot use $-number combinations (e.g. `$1`) anywhere in nested SQL fragments.

## Expected

Valid postgres-flavoured SQL would be fine; template strings wouldn't be parsing the string parts of a template.

## Repro

* https://github.com/gajus/slonik/pull/552

**Comment by gajus** [comment]
Don't have any practical solutions to this.

Slonik fragment merging relies on identifying value placeholders, e.g.

https://github.com/gajus/slonik/blob/9cc97c38b4163e4117dc45c3f17667598611be16/src/sqlFragmentFactories/createArraySqlFragment.ts#L34

One way to do it would be to come up with a custom syntax for Slonik that's used a placeholder inside of fragments.

**Comment by alxndrsn** [comment]
:+1: thanks for the superfast fix - definitely less likely to trip users.

If looking to avoid the placeholders altogether, delaying converting fragments to strings until final use would be an alternative approach.
