### ISSUE TITLE
Node 8: process.hrtime.bigint is not a function

### ISSUE THREAD

**Issue by mjm** [gajus/slonik#56]
It looks like Slonik is using `process.hrtime.bigint` to track query execution time. Unfortunately, this function is not available until Node.js 10.7.0, since V8 didn't have bigints for a while.

I did a fair chunk of work converting my code use Slonik (which is great), but I'm running on AWS Lambda which only supports Node 8 at the latest. Currently that means I can't use Slonik.

Would it be possible to switch to using the non-bigint version `process.hrtime` that uses a tuple instead? That may not work, I suppose, as it would change the interface for interceptors, I think.

**Comment by mjm** [comment]
If you have any interest in supporting Node 8, I've investigated what changes would be needed and have found one more: `EventEmitter.prototype.off` doesn't exist in Node 8, but `EventEmitter.prototype.removeListener` does.

I've been able to get [a fork](https://github.com/mjm/slonik) working by using `process.hrtime()` and switching the EventEmitter method. I do have to avoid any interceptors that use the query execution time, though, which is not great, but at least I can use it!

I'd open a PR, but I recognize that this is a breaking change in API, so I figure that's probably jumping the gun.

**Comment by mjm** [comment]
Ha! I have some real good timing, since [AWS just announced a Node 10 runtime](https://aws.amazon.com/about-aws/whats-new/2019/05/aws_lambda_adds_support_for_node_js_v10/). I'm actually going through ZEIT Now, so I can't adopt until they also support it, but it looks like this may not be as important to me as I thought it would be last night.

**Comment by ledniy** [comment]
@gajus seems like the ticket was closed without the resolution and package.json still contains `"node": ">=8.0"`
I was kinda upset when got the same error on node 8

**Comment by gajus** [comment]
I mean, you can always polyfill `process.hrtime.bigint`, even if the implementation is not spec compliant.

There is no action here other than bumping the Node.js version to `>=10.7`.
