### ISSUE TITLE
Running multiple SQL commands at once throws an exception

### ISSUE THREAD

**Issue by kkorenius** [gajus/slonik#562]
We are trying to minimize round trips to our database by combining certain commands together. This no longer works in Slonik version 40.x.x. 

## Expected Behavior

Trying to run a query with two SQL commands, in this example setting two run-time parameters at once:

``await client.query(sql.type(z.void())`set local role A;set local search_path=B);``

We are expecting this to succeed.

## Current Behavior
Error `Cannot read properties of undefined (reading 'map')` is thrown.

## Possible Solution
This is probably due new Postgres driver factory trying to map result fields in https://github.com/gajus/slonik/blob/32266d7a5f830abe7c62b07bf05c7b0c19ad325a/src/factories/createPgDriverFactory.ts#L314

Property fields is undefined in top level because two results are returned in this case:
![image](https://github.com/gajus/slonik/assets/5311084/5b3511ba-0606-4560-b50b-7518938c000d)

At least in version 37.3.1 this was still working (by accident?), because of check
https://github.com/gajus/slonik/blob/7f987590e86ce230ac08814a6cd592a367effbca/src/connectionMethods/query.ts#L24

The problem would be fixed by putting this check back in code, If the query would really return something useful, things would get a bit messier (as before).

**Comment by gajus** [comment]
You could in theory implement `pg-native` driver, which would be virtually a copy paste of:

https://github.com/gajus/slonik/blob/main/src/factories/createPgDriverFactory.ts

That would allow you to continue to use the above pattern, but I strongly discourage this as everything else in the Slonik library assumes that you are running a single command.

The correct approach for what you are trying to do would be to wrap that logic into a function and then invoke the function (if the goal is to reduce roundtrips)

**Comment by kkorenius** [comment]
Thank you for the comments and even more importantly your hard work on this great library.

Actually it did work and we did not use `pg-native` :smiley: The thing was that we only used this in our platform level code in couple of places that _did not return any data_, e.g. 

``await client.query(sql.type(z.void())`set local role A;set local search_path=B);``

But I do understand, that this is something sort of an anti-pattern and not something you want to support or promote in your library. We will work around it.

**Comment by gajus** [comment]
I stand corrected. The underlying `pg` driver does support multi statements.

https://github.com/brianc/node-postgres/blob/master/CHANGELOG.md#700

I was not aware of this.

I am not quite sure what's the best way to handle this though. Re-opening to at the very least keep it on my radar. At the very least, we should throw an error that multi-statements are not supported.

**Comment by coreyward** [comment]
Just got bit by this when upgrading Slonik as it broke a bunch of our migrations. 😬 Is there a reason this behavior changed?
