### ISSUE TITLE
Because many throws when there's no rows it would be nice to have maybeMany 

### ISSUE THREAD

**Issue by romandvoskin** [gajus/slonik#563]
When using `many` the idea is to get all the records that are there. It is a little odd that `many` throws when there's no records. However, it is what it is, so I think the next best thing is to have a many-like function that doesn't throw when there is no rows and still returns an array (an empty array when there's no rows). Perhaps we can call it `maybeMany`?

## Desired Behavior
To have a function that always returns an array, even when there's no rows

## Motivation
There's cases when we want to get all  the records and an empty collection is not an exceptional case.

## Implementation
Create a thin wrapper around `many` and `catch` the `Not Found` exception
or 
Create a thin wrapper around `query` and return the `rows` field value

**Comment by mmkal** [comment]
This is `.any`.
