### ISSUE TITLE
Cannot disable default type parsers

### ISSUE THREAD

**Issue by mjm** [gajus/slonik#57]
I'm adapting code that was using node-postgres directly, so I'm already used to getting `Date` objects for my `timestamp` fields. I wanted to keep this behavior, so I tried to provide an empty array for `typeParsers` as the README suggests.

But it looks like passing an empty array still causes the default preset of type parsers to be used.

I was able to workaround this for now by choosing a type I don't plan to use (`xml` in my case) and configuring a dummy type parser for it.

**Comment by gajus** [comment]
Seems like a good first PR.
