### ISSUE TITLE
Access logger output

### ISSUE THREAD

**Issue by vroudge** [gajus/slonik#6]
Hi!

First of all, brilliant package. 

I was wondering if it'd be possible to access the log output?
My usecase: I want to log *all* queries done through slonik.

**Comment by gajus** [comment]
Yes you can.
Slonik is using Roarr (https://medium.com/@gajus/roarr-the-perfect-json-logger-node-js-and-browser-935180bda529, https://github.com/gajus/roarr).

Simply start the program with `ROARR_LOG=true` env variable.
