### ISSUE TITLE
Unable to specify SSL cert and key

### ISSUE THREAD

**Issue by hjr3** [gajus/slonik#60]
Given the following connection URL:

`postgres://user:pass@127.0.0.1?ssl=true&sslcert=/path/to/db.cert&sslkey=/path/to/db.key`

I get the following error:

`ConnectionError: connection requires a valid client certificate`

It appears Slonik does not recognize the `sslcert` and `sslkey` parameters. After some investigation, I believe this is related to https://github.com/iceddev/pg-connection-string/issues/8

I see a few options:

* Add support for these in https://github.com/iceddev/pg-connection-string
* Support [libpq environment variables](https://www.postgresql.org/docs/9.3/libpq-envars.html)
* Allow a config object. However, it appears that may not be preferred https://github.com/gajus/slonik/issues/45

**Comment by vitaly-t** [comment]
> Add support for these in https://github.com/iceddev/pg-connection-string

Won't it be easier and more productive to throws it away and use the generic [connection-string] instead?

[connection-string]:https://github.com/vitaly-t/connection-string

**Comment by hjr3** [comment]
> Won't it be easier and more productive to replace with the generic connection-string?

I confess that I am not sure what that library does that [URI](https://developer.mozilla.org/en-US/docs/Glossary/URI) does not. The issue, as I see it, is that the connection string needs to be parsed into a `node-postgres` compatible format.

No matter what library is used, this involves more than parsing the URL in order to support SSL/TLS connections. The node-postgres library expects the _contents_ of the cert and key. See this [example](https://node-postgres.com/features/ssl) from the docs to see what I mean.

**Comment by hjr3** [comment]
@gajus I am happy to provide a PR that fits with your vision of the library. Let me know how I can help.

**Comment by gajus** [comment]
> @gajus I am happy to provide a PR that fits with your vision of the library. Let me know how I can help.

Please go ahead. I think using URI is good. The only request that I have is that any parts of URI that are not recognized should throw an error, e.g. if URI includes query parameter "foobar" that does nothing.

**Comment by vitaly-t** [comment]
> I confess that I am not sure what that library does that URI does not

It tells you right on the [main page](https://github.com/vitaly-t/connection-string):

> Unlike the default URL parser, this one supports the following:

> * Multiple hosts - for connecting to multiple servers
> * Fully optional syntax for every element in the connection string
> * Automatic defaults configuration for missing parameters
> * Re-construction of a connection string from object
> * Friendlier access to all of the URL's details
> * TypeScript declarations are deployed with the library

**Comment by hjr3** [comment]
@gajus URI is used within https://github.com/iceddev/pg-connection-string. I plan to fork that with support for this feature. That project is not actively maintained, but if I can get it merged in then all teh better.

**Comment by hjr3** [comment]
@gajus https://github.com/iceddev/pg-connection-string/releases/tag/v2.1.0 has been released this includes support for specifying the SSL cert and key.

**Comment by gajus** [comment]
This is already available.

**Comment by hjr3** [comment]
> This is already available.

Does this mean you did a release?

**Comment by gajus** [comment]
https://github.com/gajus/slonik/releases

Yes
