### ISSUE TITLE
"[unable to serialize, circular reference is too complex to analyze]" inserted into jsonb column

### ISSUE THREAD

**Issue by Lewenhaupt** [gajus/slonik#616]
## Expected Behavior

I would have expected that a failure to convert the obejct into json would cause it to crash. I also would expect postgres to complain and not be able to create the row, but it seems to be ok with it.
## Current Behavior

We get entries in our database where we expect valid JSON but instead they contain `[unable to serialize, circular reference is too complex to analyze]`
## Steps to Reproduce

No clue how to reproduce unfortunately, it happens only on occasion.

## Logs
{
    "context": {
        "package": "slonik",
        "poolId": "tSQ81X2wTZSkF7KO1hpZQg-0",
        "connectionId": "tSQ81X2wTZSkF7KO1hpZQg-7",
        "transactionId": "tSQ81X2wTZSkF7KO1hpZQg-8",
        "queryId": "tSQ81X2wTZSkF7KO1hpZQg-12",
        "logLevel": 20,
        "sql": "\n      INSERT INTO internal_events (id, detail, event_type, asset_id)\n      VALUES ($1,$2::jsonb,$3,$4)\n      RETURNING seq\n  ",
        "values": [
            "e3a0a9cb-fd84-5cc8-a8ce-3c2c52f8d1f2",
            "\"[unable to serialize, circular reference is too complex to analyze]\"",
            "PROCESS_RESOURCE",
            "067325f1-58c3-4ce9-878f-e6d606cbec85"
        ]
    },
    "message": "executing query",
    "sequence": "16",
    "time": 1717068154749,
    "version": "2.0.0"
}

**Comment by Lewenhaupt** [comment]
After digging in to the code I suspect this was because of previous use of fast-safe-stringify, but I still don't understand how postgres accepted it.
I'll upgrade to the version that uses stable-safe-stringify

**Comment by gajus** [comment]
Please create a test case if you suspect there to be a bug.

If you are passing an object that's not safe to serialize, then the current error is appropriate/expected.
