### ISSUE TITLE
Backend has been terminated unexpectedly

### ISSUE THREAD

**Issue by Yawmus** [gajus/slonik#626]
Upon upgrading our codebase from Slonik version 30.4.4 => to now 40.2.1 we have started to receive intermittent errors of type `Backend has been terminated unexpectedly`

This hadn't been occurring prior to the upgrade.
In our APIs we make something in the realm of 250k requests per-day to our Aurora DB and only receive this maybe once every other day. So it's not frequent, but is problematic when the error is issued during large paginated data pulls and the customer has to retry.

Do you have any insight as to how to trouble shoot this class of error or how it can occur in the first place?

## Expected Behavior
No `Backend has been terminated unexpectedly` error

## Current Behavior
Receive this new class of error once every other day as of the newer version upgrade.

## Steps to Reproduce
Unknown. The error appears to occur on non-specific queries and the execution time doesn't suggest long-running.

Thanks!

**Comment by gajus** [comment]
Possibly related https://github.com/brianc/node-postgres/issues/3083
