### ISSUE TITLE
Parameter connectionTimeout is not applied

### ISSUE THREAD

**Issue by apoberejnyi** [gajus/slonik#627]
## Expected Behavior

When a `connectionTimeout` parameter is passed to `createPool`, pool is expected to propagate this parameter down to the database driver.

## Current Behavior

It seems that the parameter is ignored. 

## Steps to Reproduce

Please see this repository for a minimal example: https://github.com/apoberejnyi/slonik-connection-timeout

**Comment by jorkkisummeri** [comment]
We have noticed that we can make our app hang indefinitely by restarting the db server while a connection is open (query running). It seems the connection pool is never recovering from a stale connection and whatever `connectionTimeout` we pass does not seem to have any effect. Using slonik 45.6.0 .

**Comment by jorkkisummeri** [comment]
I'm wondering if we're experiencing this issue with the underlying pg after all: https://github.com/brianc/node-postgres/issues/3197

I just created my own db driver factory to make sure pg gets the connection timeout config, and the issue we see still persists.

**Comment by jorkkisummeri** [comment]
We upgraded and the issue seems to be resolved for us with 46.0.1 . So it does not seem to depend on the underlying pg after all. My best guess is that this commit in slonik fixed it: https://github.com/gajus/slonik/commit/48263cd4845aa89539bd7004ae195d1a968bbeb1

**Comment by gajus** [comment]
Amazing
