### ISSUE TITLE
How to do a graceful shutdown (close open connection)

### ISSUE THREAD

**Issue by n1ru4l** [gajus/slonik#63]
is there any method for closing any active database connections?

When using jest with the following test:

```js
it("test", async () => {
  const slonik = createPool(
    `postgres://postgres:password@127.0.0.1:7002/postgres`
  );
  await slonik.connect(async conn => {
    await conn.many(sql`SELECT * FROM "users"`);
  });
});
```

I get the following console output:

```
Test Suites: 1 passed, 1 total
Tests:       1 passed, 1 total
Snapshots:   0 total
Time:        5.968s, estimated 6s
Ran all test suites.
Jest did not exit one second after the test run has completed.
```

It seems like it is currently not possible to close connection of a `pg.Pool` instance. If there is not would you accept a pull request that implements this functionality?

**Comment by gajus** [comment]
Connections are automatically returned to the connection pool.

This is described in: https://github.com/gajus/slonik#protecting-against-unsafe-connection-handling

When connections are terminated is configured using:

https://github.com/gajus/slonik#api (see `idleTimeout`)

**Comment by n1ru4l** [comment]
@gajus  Could you please provide a working example?

Both these tests result in the node process not shutting down gracefully.

```js

it("test", async () => {
  const slonik = createPool(
    `postgres://postgres:password@127.0.0.1:7002/postgres`,
    {
      maximumPoolSize: 1,
      minimumPoolSize: 1,
      idleTimeout: 0
    }
  );
  await slonik.connect(async conn => {
    await conn.many(
      sql`SELECT table_name FROM information_schema.tables WHERE table_schema='public';`
    );
  });
});
```
```js
it("test", async () => {
  const slonik = createPool(
    `postgres://postgres:password@127.0.0.1:7002/postgres`,
    {
      maximumPoolSize: 1,
      minimumPoolSize: 1,
      idleTimeout: 0
    }
  );
  await slonik.many(
    sql`SELECT table_name FROM information_schema.tables WHERE table_schema='public';`
  );
});
```

**Comment by gajus** [comment]
This should work. Will need to debug it to understand why it doesn't work. Note, that the pool is handled by pg-pool, so it is most likely an issue with that (unless `0` configuration is not being passed correctly). Your help debugging the issue is welcome too.

**Comment by n1ru4l** [comment]
I have one project where I am using pg.Pool in another project, will try to investigate a bit further the next days!

**Comment by hjr3** [comment]
@n1ru4l Per https://node-postgres.com/api/pool the `idleTimeout` is in milliseconds and setting the value to `0` disables auto-disconnection of idle clients.

This works for me:

```js
it("test", async () => {
  const slonik = createPool(
    `postgres://postgres:password@127.0.0.1:7002/postgres`,
    {
      maximumPoolSize: 1,
      minimumPoolSize: 1,
      idleTimeout: 1 // milliseconds!
    }
  );
  await slonik.many(
    sql`SELECT table_name FROM information_schema.tables WHERE table_schema='public';`
  );
});
```

**Comment by gajus** [comment]
Disabling idle timeout sounds like an incredibly bad idea, though, and based on this example, the `0 = disabled` is easy to do by accident.

Will address in the next major version. https://github.com/gajus/slonik/issues/64

**Comment by n1ru4l** [comment]
@hjr3 For me this example is not working...

```ts
import { createPool, sql } from "slonik";

test("foo", async () => {
  const slonik = createPool(
    `postgres://postgres:password@127.0.0.1:7002/postgres`,
    {
      maximumPoolSize: 1,
      minimumPoolSize: 1,
      idleTimeout: 1 // milliseconds!
    }
  );
  await slonik.many(
    sql`SELECT table_name FROM information_schema.tables WHERE table_schema='public';`
  );
});
```


```
 PASS  src/__tests__/integration/foo.spec.ts
  ✓ foo (107ms)

Test Suites: 1 passed, 1 total
Tests:       1 passed, 1 total
Snapshots:   0 total
Time:        1.85s
Ran all test suites.
Jest did not exit one second after the test run has completed.

This usually means that there are asynchronous operations that weren't stopped in your tests. Consider running Jest with `--detectOpenHandles` to troubleshoot this issue.
```

**Comment by gajus** [comment]
Does it not work if you add an additional event cycle?, e.g.

```js
import { createPool, sql } from "slonik";

test("foo", async () => {
  const slonik = createPool(
    `postgres://postgres:password@127.0.0.1:7002/postgres`,
    {
      maximumPoolSize: 1,
      minimumPoolSize: 1,
      idleTimeout: 1 // milliseconds!
    }
  );
  await slonik.many(
    sql`SELECT table_name FROM information_schema.tables WHERE table_schema='public';`
  );

  await new Promise((resolve) => { resolve(); });
});

```

**Comment by n1ru4l** [comment]
@gajus Sorry for the late response, no adding an additional event cycle does not resolve this issue.

**Comment by gajus** [comment]
Happy to re-open the issue, but since this seems specific to Jest, Jest is a better place to ask for help debugging issue. Off top of my head, I cannot think of a reason/ or even how Jest could prevent Slonik from releasing connections back to pool.

**Comment by mmkal** [comment]
@gajus @n1ru4l adding `afterAll(() => new Promise(r => setTimeout(r, 0)))` fixes this for me, so it likely is a jest thing. Will add that to [this jest ticket](https://github.com/facebook/jest/issues/6937) too.

**Comment by n1ru4l** [comment]
@mmkal will try this tomorrow!

**Comment by n1ru4l** [comment]
Finally tested it and now I can confirm that the solution @mmkal posted solves the problem! Thank you!

**Comment by nonara** [comment]
Same problem here. Unfortunately, afterAll await isn't working. idleTimeout set to 1, but it hangs forever. 

Will keep an eye on the jest issue
