### ISSUE TITLE
Unsafe foreign connection false positive?

### ISSUE THREAD

**Issue by hfhchan-plb** [gajus/slonik#637]
I am using `createPool()` with transactions on aws lambda with the nestjs framework.

For every write request, I create a new object with a `query()` method which starts a transaction, runs a query to set the application name for the transaction, and then runs the original query.

Simplified form of the code which exhibits this problem:

```ts
export class SlonikService {
  private pool = createPool(/* ... */);

  public setTrxApplicationName(userId: number) {
    const schema = z.object({ set_config: z.string() });
    await trx.query(sql.type(schema)`SELECT set_config('application_name', `web-application<${userId}>`, true)`);
  }

  public readonly() {
    return this.pool;
  }

  public readwrite(user: { id: number }) {
    const pool = this.pool;

    return {
      query: (query, values) => {
        return pool.transaction(trx => this.setTrxApplicationName(trx, user.id).then(() => trx.query(query, values)));
      },
    } as {
      query: DatabasePool['query'];
    };
  }
}
```

I'm receiving a `Cannot run a query inside a transaction using a foreign connection.` error in some requests.

Looking at logs on CloudWatch, the first request which calls readwrite() once completes just fine. The next request calls readonly() 5 times to issue 5 queries also completes just fine. It's the second request calling readonly() which throws the error. This is on a single lambda instance.

It appears as if when the connection gets recycled, the transaction state was not cleared properly.

## Expected Behavior
No error is thrown

## Current Behavior
An error is thrown for the sixth read query but not for the first five read queries.

## Logs
I'm using AWS lambda and not exactly sure how to integrate roarr with CloudWatch.

## Addendum

I initially used a different implementation as follows:

```ts
export class SlonikService {
  private pool = createPool(/* ... */);

  public setTrxApplicationName(userId: number) {
    const schema = z.object({ set_config: z.string() });
    await trx.query(sql.type(schema)`SELECT set_config('application_name', `web-application<${userId}>`, true)`);
  }

  public readonly() {
    return this.pool;
  }

  public readwrite(user: { id: number }) {
    return {
      query: async (query, values) => {
        return await this.pool.transaction(async trx => {
          await this.setTrxApplicationName(trx, user.id);
          return await trx.query(query, values);
        });
      },
    } as {
      query: DatabasePool['query'];
    };
  }
}
```

This threw the same error, but I did not check if it threw on the next readonly request, or only after a couple of successful readonly requests. I suspected it was due to some stack detection / asyncLocalContext issue, so I tried removing all the async/awaits and converting it to plain old promises, but that did not solve the issue.

**Comment by gajus** [comment]
I cannot figure out what this code is even supposed to do (there are clear errors in the code).

Please create a test case that replicates the issue.

**Comment by hfhchan-plb** [comment]
> There are clear errors in the code.

I've just corrected the code. I accidentally introduced them while trying to remove unrelated code.

> I cannot figure out what this code is even supposed to do

I'm trying to run wrap every `.query()` / `.one()` / `.oneFirst()` etc call in a transaction, and run the following query in a transaction:

```sql
SELECT set_config('application_name', 'web-application<${userId}>'}, true)
```

so every write query that runs has the application_name set to the requesting user.

> Please create a test case that replicates the issue.

After a bit more testing I cannot reproduce this issue locally while running with `serverless-offline`. But it still keeps happening when running on AWS. I suspect that AsyncLocalStorage might be behaving differently on AWS.

**Comment by hfhchan-plb** [comment]
What makes this even more strange is that on a certain env, we have readonly() and readwrite() having different pools, we only ever call .transaction() on the readwrite pool, but it's the readonly pool which is throwing the Unsafe Foreign Connection exception.

**Comment by hfhchan-plb** [comment]
I fixed this by manually `end()`ing all pools and recreating them just before the lambda invocation finishes.

(I was never calling `connect()` though -- it looks like on AWS Lambda, somehow slonik ends up recycling connections which do not have the state cleared properly)
