### ISSUE TITLE
Regression: cannot use @slonik/migrator anymore due to multiple queries prevented

### ISSUE THREAD

**Issue by oguimbal** [gajus/slonik#643]
We're using @slonik/migrator  (which is listed in readme as a valid solution).

A release this year seems to have broken it, since executing multiple statements in a single query is not supported anymore. When running its migrations, @slonik/migrator triggers a `Must not use multiple statements in a single query.`  error.

Related issues:  #601  #562

Regression introduced [in this commit](https://github.com/gajus/slonik/commit/71746d67e912389e340b1a2e1528be0babf1d52d)

**Comment by mmkal** [comment]
I'm the maintainer of `@slonik/migrator` and unfortunately I haven't been able to keep up with slonik's breaking changes in general. I'm working on a new solution at https://pgkit.dev - it has a bunch of new migrator features and should be backwards compatible. Feel free to try it out, but there may still be some rough edges. Any feedback would be greatly appreciated.

**Comment by oguimbal** [comment]
I knew your handle sounded familiar: you've contributed to [pg-mem](https://github.com/oguimbal/pg-mem) :)

I'll have a look, thanks

**Comment by oguimbal** [comment]
dirty workaround: below code as postinstall script, which monkey patches the driver to accept multiple statements

```typescript
import fs from 'fs';

// see https://github.com/gajus/slonik/issues/643
{
    const target = './node_modules/@slonik/pg-driver/dist/factories/createPgDriverFactory.js';
    const content = fs.readFileSync(target, 'utf8');

    const tr = `throw new errors_1.InvalidInputError('Must not use multiple statements in a single query.');`;
    if (!content.includes(tr)) {
        console.log('👍 @slonik/pg-driver already patched');
    } else {
        const newContent = content.replace(
            tr,
            `// was throwing new errors_1.InvalidInputError('Must not use multiple statements in a single query.');
            result = result[result.length - 1];`,
        );
        fs.writeFileSync(target, newContent);
        console.log('👍 Patched @slonik/pg-driver');
    }
}
```

**Comment by gajus** [comment]
Sounds resolved.
