### ISSUE TITLE
Missing Error for exclusion constraints

### ISSUE THREAD

**Issue by janpaepke** [gajus/slonik#650]
Aside from intregrity constraints, psql also supports [exclusion constraints](https://www.postgresql.org/docs/current/ddl-constraints.html#DDL-CONSTRAINTS-EXCLUSION).

Currently those get rethrown as `DatabaseErrror` from pg:
```
    err: {
      "type": "DatabaseError",
      "message": "conflicting key value violates exclusion constraint \"constraint_name\"",
      "stack":
          error: conflicting key value violates exclusion constraint "constraint_name"
              [🙈]
      "length": 312,
      "name": "error",
      "severity": "ERROR",
      "code": "23P01",
      "detail": [🙈],
      "schema": "public",
      "table": "table_name",
      "constraint": "constraint_name",
      "file": "execIndexing.c",
      "line": "888",
      "routine": "check_exclusion_or_unique_constraint",
      "notices": []
    }
```

## Desired Behavior

I guess similar to `CheckIntegrityConstraintViolationError`, slonik should add `CheckExclusionConstraintViolationError`.

## Motivation

The above error actually turned up during error management in our app.

## Implementation

maybe like this?
```
  if (error.code === '23P01') {
    return new CheckExclusionConstraintViolationError(error);
  }
```

**Comment by gajus** [comment]
Would accept a PR for this.
