### ISSUE TITLE
Inserting json values

### ISSUE THREAD

**Issue by Wenzil** [gajus/slonik#69]
I'd like to be able to insert json data in `json` and `jsonb` typed columns like this:

```js
const myObject = { a: "aaa" };
connection.query(sql`
    INSERT INTO my_table (my_json_col)
    VALUES (${sql.json(myObject)});
`);
```

A verbose workaround is to use `sql.raw` like the following:

```js
const myObject = { a: "aaa" };
connection.query(sql`
    INSERT INTO my_table (my_json_col)
    VALUES (${sql.raw("$1::json", [JSON.stringify(myObject)])});
`);
```

**Comment by gajus** [comment]
You can simply do:

```js
const myObject = { a: "aaa" };
connection.query(sql`
  INSERT INTO my_table (my_json_col)
  VALUES (${JSON.stringify(myObject)});
`);

```

While I can add `json` helper, what would be the benefit of it?

**Comment by Sharaal** [comment]
It's not useful to have a simple?

```javascript
const myObject = { a: "aaa" };
connection.query(sql`
  INSERT INTO my_table (my_json_col)
  VALUES (${myObject});
`);
```

And the lib converts objects into JSON?

**Comment by gajus** [comment]
I can see perhaps the appeal for `sql.json` helper. Will add it.

**Comment by gajus** [comment]
Would not do it without a helper (as in your example) as it would introduce ambiguity.

**Comment by Sharaal** [comment]
I figured out `node-postgres` already supporting objects as parameters and stringify them for the JSON columns:
https://node-postgres.com/features/types#uuid-json-jsonb

So maybe the helper is not needed?

**Comment by gajus** [comment]
> I figured out node-postgres already supporting objects as parameters and stringify them for the JSON columns:
https://node-postgres.com/features/types#uuid-json-jsonb

I am aware, however, performing stringification at the time of creating the query object reduces the chances of bug as a result of side-effects mutating the subject object and allows to debug the exact values that were sent to postgres server.

**Comment by yosbelms** [comment]
@gajus It would be useful to support JSONB as well.
