### ISSUE TITLE
Validate values added to SQL fragments

### ISSUE THREAD

**Issue by gajus** [gajus/slonik#71]
Example:

```js
sql`SELECT {new Date()}`;

```

is going to throw error:

> TypeError: Unexpected value expression.

However,

```js
sql`SELECT {sql.unnest([[new Date()]], ['timestamp'])}`;

```

is going to be evaluated as:

```js
{
  sql: 'SELECT * FROM unnest($1::"timestamp"[])',
  type: Symbol(SLONIK_SQL),
  values: [
    [
      Date 2019-06-26 07:30:20 578ms UTC {}
    ]
  ],
}

```

This is because `createUnnestSqlFragment` simply assumes primitive values and pushes them to the value binding array.

https://github.com/gajus/slonik/blob/d511ede91da9466864eafaaaa3efbc7e9a22fde1/src/sqlFragmentFactories/createUnnestSqlFragment.js#L55

This is unlikely a security issue (since this is how `node-postgres` behaves by default), but it can lead to some unexpected behaviour, such as with the timestamp/ Date example.

We should likely require that bound values are primitives.

**Comment by rtbo** [comment]
As `pg` is already consuming javascript `Date` objects, is it not possible to pass them all the way through to `pg`?
This is what I naively expected.
Everything that map to a primitive postgresql type (such as `date`, `timestamp`, `timestamptz`) should be also considered primitive (I guess javascript Date would be the only exception to actual primitive types).
This would avoid resorting to `to_timestamp` call, which is IMO unnecessary. (At least it is not needed when using `pg` directly).

BTW according docs, `to_timestamp` convert string to timestamps, using a format string. I can't find in the doc a use of `to_timestamp` that takes a float or integer in seconds.

**Comment by gajus** [comment]
> As `pg` is already consuming javascript `Date` objects, is it not possible to pass them all the way through to `pg`?
> This is what I naively expected.
> Everything that map to a primitive postgresql type (such as `date`, `timestamp`, `timestamptz`) should be also considered primitive (I guess javascript Date would be the only exception to actual primitive types).
> This would avoid resorting to `to_timestamp` call, which is IMO unnecessary. (At least it is not needed when using `pg` directly).

https://github.com/gajus/slonik/issues/113
