### ISSUE TITLE
[Question] Build a dynamic sql

### ISSUE THREAD

**Issue by mojoTliu** [gajus/slonik#73]
_For example:_
```jsx
sql`
      INSERT INTO ${sql.identifier([schema, table])} (${columns})
      VALUES ${sql.tuple(values)}
     RETURNING id
`
```
This code will cause the error below:
```jsx
UnhandledPromiseRejectionWarning: error: syntax error at or near "$1"
```
Produces:
```jsx
INSERT INTO "public"."USERS" ($1, $2) VALUES ($3, $4) RETURNING id
```
**QUESTIONS**: I wonder whether the **columns** can also be imported dynamically?

_p.s. schema, table, columns, values are variable._

**Comment by gajus** [comment]
https://github.com/gajus/slonik#slonik-query-building-sql-identifierlist

**Comment by gajus** [comment]
You might also want to check out https://github.com/gajus/slonik-utilities
