### ISSUE TITLE
Can same value use same placeholder in output sql?

### ISSUE THREAD

**Issue by hackwaly** [gajus/slonik#75]
Consider this sql query. Currently slonik will map two occurrences of `${type}` to two placeholders eg. $1, $2. This results the sql won't be accepted by database.
```
sql`SELECT sum(value) as value, date_trunc(${type}, date) FROM commit GROUP BY date_trunc(${type}, date)`
```

**Comment by gajus** [comment]
https://github.com/gajus/slonik/issues/5
