### ISSUE TITLE
Joining tagged template fragments

### ISSUE THREAD

**Issue by nodefish** [gajus/slonik#78]
I know you want to discourage dynamic queries, but surely they should have some support in `Slonik` that is safer than `sql.raw` and doesn't make me leave `Slonik`'s API completely in favor of a query builder like `sqorn`.

I find myself doing things like this...
```js
const and_conditions = [];
conditions.forEach(cnd => or_conditions.push(`${cnd.col} LIKE '%${cnd.val}%'`));
const or_fragment = `(${or_conditions.join(' OR ')})`;
if (or_fragment) and_conditions.push(or_fragment);
```
...and subsequently either using `sql.raw` for everything at the last stage when I combine the fragments, or fighting against `Slonik` in an attempt to get some safety, e.g. trying to add `Slonik` safety like:
```js
const and_conditions = [];
conditions.forEach(cnd => or_conditions.push(sql`${sql.identifier([cnd.col])} LIKE '%${cnd.val}%'`));
const or_fragment = `(${or_conditions.join(' OR ')})`; // <-- no longer valid
if (or_fragment) and_conditions.push(or_fragment);
[...]
const fragment = sql`${base_fragment} WHERE ${and_conditions.join(' AND ')}; // <-- no longer valid
```
Would it be possible to provide something like a `join` method on the output object of tagged template literals or something along those lines in order to enhance composability? I'm not actually sure what a good solution would look like, but I feel like composability without totally losing safety is a reasonable goal for this project given that's supposed to be its main strength compared to using node-pg.

**Comment by gajus** [comment]
https://github.com/gajus/slonik#slonik-query-building-sql-booleanexpression

**Comment by baerrach** [comment]
`sql.booleanExpression` was removed in favour of `sql.join` but the article has not been updated.

See [feat: remove multiple methods in favor of sql.join ](https://github.com/gajus/slonik/commit/910177db4e8bdb8f2d2b4a9e82bd017044a6801d)

The doc link is now https://github.com/gajus/slonik#slonik-query-building-sql-join
