### ISSUE TITLE
PostGIS functions in sql.unnest

### ISSUE THREAD

**Issue by lamuertepeluda** [gajus/slonik#79]
Hello,

while I appreciate a lot the philosophy of this library and its effort to get rid of ORMs like Sequelize, TypeORM and similars, I still do not understand how to call a SQL function when performing sql.unnest.

I am using PostGIS extension, although I assume the problem may occur with any Postgres function.

Now, assuming I have a table named `metrics` like this

```sql
    timestamp TIMESTAMPTZ NOT NULL,
    geolocation geography (POINT),
    data JSONB NOT NULL,
```

The queries I am trying to execute are like the following ones:

 #### Query 1
```sql
INSERT INTO metrics (timestamp, data, geolocation)
SELECT *
FROM unnest(
	ARRAY['2019-08-07T09:02:53.174Z']::"timestamptz"[], 
	ARRAY['{"someInt": 0, "someFloat": 0.3, "someString": "str_0"}']::"jsonb"[],
	ARRAY[ST_GeographyFromText('POINT EMPTY')]::"geography"[]
)
```

 #### Query 2
```sql
INSERT INTO metrics (timestamp, data, geolocation)
SELECT *
FROM unnest(
	ARRAY['2019-08-07T08:02:53.174Z']::"timestamptz"[], 
	ARRAY['{"someInt": 0, "someFloat": 0.3, "someString": "str_0"}']::"jsonb"[],
	ARRAY[NULL]::"geography"[]
)
```

tried those in my client (Postico) and they work just fine.

This is how I'm trying it via slonik

```js
// Generate random data
function genRecord(i = 0) {
  return {
    timestamp: new Date(),
    data: {
      someInt: i,
      someFloat: Date.now() * Math.random(),
      someString: `str_${i}`,
    },
    geolocation: null // I could generate some random lat lon, but this has not to do with the issue
  };
}

// Serialize data so that they can be chewed by slonik
function serializeRecord(record) {
  const wkt = `POINT ${
    record.geolocation
      ? `(${record.geolocation.longitude} ${record.geolocation.latitude})`
       : 'EMPTY'
   }`;
  const geolocation = sql`${sql.raw(`ST_GeographyFromText('$1')`, [wkt])}`; 
  return [record.timestamp, sql.json(record.data), geolocation];
}
const SIZE = 3;
const records = Array.from(Array(SIZE)).map((un, i) => genRecord(i));


const testInsert = records.map(serializeRecord);

const pool = createPool(connectionString);

async function runQuery(query) {
  await pool.connect(async connection => {
    try {
      await connection.query(query);
    } catch (err) {
      console.error('Query Error', err);
    }
  });
}

let query = sql`
INSERT INTO metrics (timestamp, data, geolocation)
SELECT *
FROM ${sql.unnest(testInsert, ['timestamptz', 'jsonb', 'geography'])}
`;

runQuery(query);
```

If I try to use `ST_GeographyFromText` I always get "malformed array literal error".
Even weirder, if I set NULL values for geometry I get `parse error - invalid geometry`

I also have tried the following approaches, all failing (yeah, kind of brute-force attempts):

```js
const geolocation = null;
const geolocation = `ST_GeographyFromText('${wkt}')`;
const geolocation = sql.raw(`ST_GeographyFromText('$1')`, wkt)
const geolocation = sql.raw(`ST_GeographyFromText('$1')`, [wkt]);
```

### The final Question

How to use functions like `ST_GeographyFromText` ? How to make it work with unnest?

Thanks

**Comment by gajus** [comment]
`unnest` currently does not support custom expressions.

It would be a nice feature to have, though.

In the mean time, consider raising a PR or donating to the project.

**Comment by gajus** [comment]
To break down the issue, the real enhancement that needs to be made is to allow `sql.array` to accept `sql.raw` expressions, e.g.

```js
sql`
INSERT INTO metrics (timestamp, data, geolocation)
SELECT *
FROM unnest(
  ${sql.array(['2019-08-07T09:02:53.174Z'], 'timestamptz')},
  ${sql.array(['{"someInt": 0, "someFloat": 0.3, "someString": "str_0"}'], 'jsonb')},
  ${sql.array(['{"someInt": 0, "someFloat": 0.3, "someString": "str_0"}'], 'jsonb')},
  ${sql.array([sql.raw(`ST_GeographyFromText('POINT EMPTY')`, 'geography')], 'timestamptz')},
)
`

```

(Note, this is currently not supported.)

**Comment by lamuertepeluda** [comment]
Hi,

this is the closest I could get but looks like sql.raw prevents me to use arrays

```js
let query = sql`${sql.raw(
  `
  INSERT INTO metrics (timestamp, data, geolocation)
  SELECT *
  FROM unnest(ARRAY[$1]::"timestamptz"[], ARRAY[$2]::"jsonb"[], ARRAY[$3]::"geography"[])
`,
  ...testInsert,
)}`;
```

So it just inserts the first record 😞

**Comment by lamuertepeluda** [comment]
Hi again,

I found an hack by myself I'm not really proud of, since it does not scale well, but basically I had to:

1) change serializeRecord like this

```js
// Return Record as a 3-fields tuple
function serializeRecord(record) {
  const geolocation = record.geolocation
    ? `ST_GeographyFromText('POINT (${record.geolocation.longitude} ${record.geolocation.latitude})')`
    : 'NULL';
  return [
    record.timestamp.toISOString(), // string
    JSON.stringify(record.data), // string too
    geolocation, // also string
  ];
}
```

2) transpose records

```js
const SIZE = 80000; // over the limit of 65535
// Array<Record> SIZE x 3
const records = Array.from(Array(SIZE)).map((un, i) => genRecord(i));

/**
 * Transpose array. On the original article is called invert, but I feel it's wrong named, although working
 * @see https://stackoverflow.com/questions/17428587/transposing-a-2d-array-in-javascript
 * @param {Array} a
 */
const transpose = a => a[0].map((col, c) => a.map((row, r) => a[r][c]));

// Array 3 x SIZE
const testInsert = transpose(records.map(serializeRecord));
```

3) Resort to using ES6 literals and `sql.raw`

```js
/**
 * Convert to SQL string, with single quotes, e.g. 9 -> '9'
 * @param {any} x
 */
const toSQLString = x => `'${x}'`;

// Must resort to template string
const queryText = `INSERT INTO metrics (timestamp, data, geolocation)
SELECT *
FROM unnest(
  ARRAY[${testInsert[0].map(toSQLString).join(', ')}]::"timestamptz"[],
  ARRAY[${testInsert[1].map(toSQLString).join(', ')}]::"jsonb"[],
  ARRAY[${testInsert[2].join(', ')}]::"geography"[]
)`;

let query = sql` 
  ${sql.raw(queryText)}
`;
```

Now this, while does solve my real problem (inserting more than 65535 records in the table), does not make use of slonik query building methods, but resorts to sql.raw to work, in an hacky way.  
Should be safe enough, but I'd like to have some a more integrated way of doing this.

**Comment by gajus** [comment]
This is how you would bind a value to a function:

```js
await pool.any(sql`
  SELECT ST_GeogFromText(${sql.valueList(['SRID=4267;POINT(-77.0092 38.889588)'])})
`)

```

This is how you would use a dynamic function:

```js
await pool.any(sql`
  SELECT ${sql.raw('ST_GeogFromText($1)', [sql.valueList(['SRID=4267;POINT(-77.0092 38.889588)'])])}
`)

```

Finally, the newly added [`sql.rawList`](https://github.com/gajus/slonik#slonik-query-building-sql-rawlist) allows you to have a list of these expressions, e.g.

```js
sql`
  SELECT ARRAY[
    ${sql.rawList([
      sql.raw('ST_GeogFromText($1)', [sql.valueList(['SRID=4267;POINT(-77.0092 38.889588)'])]),
      sql.raw('ST_GeogFromText($1)', [sql.valueList(['SRID=4267;POINT(-77.0092 38.889588)'])]),
    ])}
  ]::geography[]
`

```

**Comment by lamuertepeluda** [comment]
this one has been completely broken now that sql.raw is no more available, right? 😞

**Comment by gajus** [comment]
Not at all.

```js
const coordinatePairs = [
  'SRID=4267;POINT(-77.0092 38.889588)',
  'SRID=4267;POINT(-77.0092 38.889588)'
];

sql`
SELECT ARRAY[
  ${sql.join(
    coordinatePairs.map((coordinatePair) => {
      return sql`ST_GeogFromText(${coordinatePair})`;
    }),
    sql`, `,
  )}
]::geography[]


```

**Comment by lamuertepeluda** [comment]
ok but how does it play with `sql.unnest`? because I keep getting `TypeError: Unexpected value expression.`

**Comment by gajus** [comment]
Please provide code throwing the error.

**Comment by lamuertepeluda** [comment]
Ok I got it working like this:

The following is my table

```sql
CREATE TABLE my_table (
    id serial,
    name citext UNIQUE NOT NULL CHECK ( length(name) > 0 ),
    metadata JSONB,
    location geometry (POINT,4326) NOT NULL,
    PRIMARY KEY (id)
);
```

And here I try uploading the attached geojson file (as txt because of github attachment rules)

```js
const wkx = require('wkx') // this is a library for converting from/to multiple geo* formats

const fc = MyFeatureCollection // load from any geojson file, I attach one here which is open data

const transpose = a => a[0].map((col, c) => a.map((row, r) => a[r][c]))

const records = transpose(fc.features.map(({ properties, geometry }) => {
        const { Name: name, ...metadata } = properties
        const location = wkx.Geometry.parseGeoJSON(geometry)
        location.srid = 4326

        return [
          name,
          sql.json(metadata),
          sql`ST_GeomFromEWKT(${location.toEwkt()})`
        ]
      })
)
   // MOST RELEVANT PART
    await pool.connect(async connection => {
      const query = sql`
    INSERT INTO my_table (name, metadata, location)
    SELECT *
    FROM unnest(
        ARRAY[${sql.join(records[0], sql`, `)}]::text[],
        ARRAY[${sql.join(records[1], sql`, `)}]::jsonb[],
        ARRAY[${sql.join(records[2], sql`, `)}]::geometry[]
    )
   await connection.query(query)
})
```

Attached file for testing: [sensori_meteo_arpa_campania.geojson.txt](https://github.com/gajus/slonik/files/3852095/sensori_meteo_arpa_campania.geojson.txt)

No way of gettin' it working with `sql.unnest()` but I'm also fine like this.

When I tried with sql.unnest (without transposing the array of records) I always got `There were errors: Invalid unnest tuple member type. Must be a primitive value expression.`


```js
const records = fc.features.map(({ properties, geometry }) => {
        const { Name: name, ...metadata } = properties
        const location = wkx.Geometry.parseGeoJSON(geometry)
        location.srid = 4326

        return [
          name,
          sql.json(metadata),
          sql`ST_GeomFromEWKT(${location.toEwkt()})`
        ]
      })

await pool.connect(async connection => {
     const query = sql`
      INSERT INTO stations (name, metadata, location)
      SELECT *
      FROM ${sql.unnest(stationsRecords, ['text', 'jsonb', 'geometry'])}
      `
      await connection.query(query)
    })

```

Or changing a bit, `TypeError: Unexpected value expression`


I love this library approach, but I think the documentation should be a bit clearer about how to use SQL Functions within queries, i.e. like ST_* or even to_json(), json_build_object() and the other 1000 powerful functions that make PostgreSQL awesome

**Comment by jokesterfr** [comment]
Just found out undefined and null have a different interpretation against `sql.unnest()` :

```
const sqlUnest = sql.unnest(
  [
    [null, '', ''],
    ['', '', ''],
  ],
  types,
);
// gives no error 
```


```
const sqlUnest = sql.unnest(
  [
    [undefined, '', ''],
    ['', '', ''],
  ],
  types,
);
// gives "InvalidInputError: Invalid unnest tuple member type. Must be a primitive value expression."
```

**Comment by StarpTech** [comment]
Hello, it looks like the issue was not addressed. Please reopen.

**Comment by StarpTech** [comment]
I'm looking for a way to use a regular postgres function with `sql.unnest`. Could you provide an example?

**Comment by devthejo** [comment]
@lamuertepeluda using the solution you provide give me `could not determine data type of parameter $4`, here is my code:
```js
const rowsToColumns = (a) => a[0].map((_col, c) => a.map((_row, r) => a[r][c]))
const insertRows = linkUserIdList.map((alertingUserid) => {
  ...
  const initialLocation = sql`ST_GeomFromGeoJSON('${locationJSON}')`
  return [
    alertId,
    alertingUserid,
    deviceId,
    initialLocation,
    initialDistance,
  ]
})
const insertColumns = rowsToColumns(insertRows)
await pg.query(
  sql`
    INSERT INTO "alerting" ("alert_id", "user_id", "device_id", "initial_location", "initial_distance")
    SELECT
      *
    FROM
      unnest(
        ARRAY[${sql.join(insertColumns[0], sql`, `)}]::int8[],
        ARRAY[${sql.join(insertColumns[1], sql`, `)}]::int8[],
        ARRAY[${sql.join(insertColumns[2], sql`, `)}]::int8[],
        ARRAY[${sql.join(insertColumns[3], sql`, `)}]::geography[],
        ARRAY[${sql.join(insertColumns[4], sql`, `)}]::numeric[]
      )
    ON CONFLICT ("user_id",
      "alert_id")
      DO NOTHING
    `
)

```

**Comment by devthejo** [comment]
here is my workaround:
```js
const format = require("pg-format")
const { raw } = require("slonik-sql-tag-raw")

const pgInsertValues = (rows, types) => {
  return rows
    .map((row) => {
      const formattedRow = []
      for (let i = 0; i < types.length; i++) {
        const type = types[i]
        const col = row[i]
        let sqlString
        if (Array.isArray(type)) {
          const [t, field] = type
          sqlString = `${field}::${t}`
        } else {
          sqlString = `%L::${type}`
        }
        let vars
        if (Array.isArray(col)) {
          vars = col
        } else {
          vars = [col]
        }
        formattedRow.push(format(sqlString, vars))
      }
      return `(${formattedRow.join(",")})`
    })
    .join(",")
}

const values = pgInsertValues(insertRows, [
  "int8",
  "int8",
  "int8",
  ["geography", "ST_GeomFromGeoJSON('%s')"],
  "numeric",
])

await pg.query(sql`
  INSERT INTO "alerting" ("alert_id", "user_id", "device_id", "initial_location", "initial_distance")
    VALUES
      ${raw(values)}
    ON CONFLICT ("user_id", "alert_id")
      DO NOTHING
`)
```

**Comment by akutruff** [comment]
@gajus Suggest adding something like the following to show a full end-to-end example of a way of dealing with a custom type somehow.  The information below was rather scattered in the docs.

Dropping this here since I had to reference this thread for PostGIS quite a bit and also ran into the `could not determine data type of parameter` issue. 

It turned out for me that trying to use a query parameter `$8` to insert inside a string does not work.  `ST_GeogFromText` takes  a single quoted string, and when you try to put in a dynamic value inside of it, the underlying driver does not like it because it cannot insert params into a single quoted string.  Instead, you can use the built-in PostGIS SQL functions that are not text based and go from a `Point` with real numeric parameters and then cast to `geography` and all is good.  

See the following for all the code to support a geography field.  The `toGeography` function has the main fix in it.

```typescript
import { Geometry, type Point } from 'wkx';
import { createPool, createTypeParserPreset, } from 'slonik';

//setup a pool that automatically converts geography types to a simple Json object with latitude and long
export const pool = await createPool(process.env.DATABASE_URL, {
  typeParsers: [
    ...createTypeParserPreset(),
    {
      name: 'geography',
      parse: fromGeography
    }
  ]
});

export interface Geography {
  longitude: number;
  latitude: number;
}

// SQL to insert a value with SQL functions rather than text.  Fixes issue with parms in single quoted string.
export const toGeography = (location: Geography | undefined | null) =>
  !!location ? sql.fragment`ST_POINT(${location.longitude}, ${location.latitude}, 4326)::geography` : null;

//parser that uses wkx with hex encoded binary 
export const fromGeography = (geo: string | null) => {
  if (!geo) {
    return null;
  }

  const { x, y } = Geometry.parse(Buffer.from(geo, 'hex')) as Point;

  if (x === null || y === null) {
    return null;
  }

  return { longitude: x, latitude: y  };
};
```
For completeness, here's how a `geography` field is defined.
```sql
create table places (
    id uuid PRIMARY KEY,
    location geography(point),
);
```

**Comment by gajus** [comment]
This is great. Where do you think this would go in documentation?

**Comment by akutruff** [comment]
Note,  I just edited the example comment to use Zod instead of an interface and added an example query. 

I suggest in recipes or as an intro.  It's kind of the full closing of the 'loop' for wanting to use Slonik IMHO.

**Comment by pablosproject** [comment]
@akutruff Nice stuff. I am trying to do the same for `Geometry` and I don't understand how you are using the `toGeography()` function.

I have same issues as you, the type of the parameter is not detected.

**Comment by akutruff** [comment]
@pablosproject 

The natural thing people try to do is to use `ST_GeogFromText` as that's what the examples in the docs use.  The key thing to notice is that this function takes _text_ as an input and not actual numbers.  The Postgres driver does not insert values into strings for you like this.

Here's the bad way:
```ts 
const long= -77.0092 ;
const lat = 38.889588)';
sql.fragment`ST_GeogFromText('SRID=4267;POINT(${long}, ${lat})')`;
```
At the end of the day, those references to `${long}` and `${lat}` get turned sent to the database by `pg` in something that looks like this:

#### Strings with params are bad
```SQL
ST_GeogFromText('SRID=4267;POINT($1, $2)')
```
and along side it is a map of what $1 and $2 are.  The DB then does the parameter substitution.  That's how we prevent SQL injection etc.  BUT, see those single quotes?  That's the issue.  The DB says "yo, you're trying to insert a parameter you sent me into a string. That's not allowed."  In other words, we're trying to ask the DB to do an implicit string concatenation for us from the parameters and it doesn't like it.   So, to get around it, we use SQL functions that don't take **text** as input.  

#### SQL Functions are good
```ts
sql.fragment`ST_POINT(${location.longitude}, ${location.latitude}, 4326)::geography`
```
So here, instead of using SQL functions that deal directly with the actual typed values and not text.

This is what gets spit out now:
```SQL
ST_POINT($1, $2, 4326)::geography
```
See how there's no single quotes anywhere?  That's because we are calling actual SQL functions rather than using `ST_GeogFromText` that parses and interprets a string.

In the above, we create an actual real PostGIS `Point` that is a real typed value in the SQL world, and then we use `::geography` which converts the point value to a `Geography`.    

The DB has no problem inserting `$1` and `$2` into the SQL because it's not inside of a string.

#### Don't do this, but you could still use `ST_GeogFromText`

Now, if you are dead set on using `ST_GeogFromText`, you actually can do something really hacky and use a string concatenation to get it done:

```ts
sql.fragment`ST_GeogFromText('SRID=4267;POINT(' || ${long} ',' || ${lat} || ')')`;
```
Gets set to be:

```SQL
ST_GeogFromText('SRID=4267;POINT(' || $1 ',' || $2 || ')')
```
The `||` is a string concatenation, and it all now works because the DB is fine with you you inserting parameters at the top and not inside the string.
