### ISSUE TITLE
missing comparison operators

### ISSUE THREAD

**Issue by benjamine** [gajus/slonik#80]
I wonder if I'm misuing this but, I was trying to use `sql.comparisonPredicate` with operators like `IN` and `LIKE`, but I noticed these are invalid operators for this helper
(getting this error https://github.com/gajus/slonik/blob/6ba9645bdd79056c189d3b2bcc724085f153486c/src/sqlFragmentFactories/createComparisonPredicateSqlFragment.js#L30 )

is this intentional should we used a different helper? or just `sql.raw` for them?

**Comment by gajus** [comment]
You most likely want `sql.tuple`.

https://github.com/gajus/slonik#slonik-query-building-sql-tuple

**Comment by gajus** [comment]
If not, share an example query.

**Comment by benjamine** [comment]
sorry, should have included an example:
``` js
const isLike = criteria.includes('%');
return sql`
  SELECT * FROM table WHERE  
    ${sql.comparisonPredicate("name", isLike ? 'LIKE' : '=', criteria)}
  ;`;
```
OR
``` js
return sql`
  SELECT * FROM table WHERE  
    # filter by city, or city not set if value is null
    ${sql.comparisonPredicate("city", value === null ? 'IS' : '=', value)}
  ;`;
```

**Comment by benjamine** [comment]
perhaps this is this too dynamic and you would recommend a query builder instead?

**Comment by gajus** [comment]
```js
sql`
  SELECT *
  FROM table
  WHERE name ${sql.raw(isLike ? 'LIKE' : '=')} ${criteria}
 `;
```

**Comment by gajus** [comment]
I guess `LIKE` could be included as an allow comparison predicate.

Seems like a reasonable use case.

**Comment by gajus** [comment]
Cannot remember what is the reason for excluding it, esp. seeing that `<->` and `%` are supported.

**Comment by benjamine** [comment]
wow, that was fast 👏 , thank you!!
