### ISSUE TITLE
Incorrect Datatype of QueryContextType.queryInputTime

### ISSUE THREAD

**Issue by dennismphil** [gajus/slonik#81]
# Description

The datatype of [QueryContextType.queryInputTime](https://github.com/gajus/slonik/blob/d2668503e5c300c9723054acd6c703dd581f2029/src/types.js#L238) should be `bigint` instead of `number` based on the implementation in [executeQuery.js](https://github.com/gajus/slonik/blob/26814b54a491885b5b7d631ec602c1d87a2d18e6/src/routines/executeQuery.js#L54).

```js
// types.js
export type QueryContextType = {|
  ...
  +queryInputTime: number,
  ...
|};
```

```js
// executeQuery.js
...
...
const queryInputTime = process.hrtime.bigint();
...
...
```

Thank you for all the effort put into building this library. 

![bitmoji](https://render.bitstrips.com/v2/cpanel/cf7648af-2035-4e07-9237-89aa82985b3c-27f3d64a-b3a3-43b8-a269-f9caa01ea0d8-v1.png?transparent=1&palette=1&width=100)

**Comment by gajus** [comment]
Flow does not support `bigint` at the moment.

**Comment by gajus** [comment]
We are not using Flow anymore.
