### ISSUE TITLE
Dynamic INSERT + ON CONFLICT DO UPDATE

### ISSUE THREAD

**Issue by ivan-kleshnin** [gajus/slonik#83]
Hi! I have a couple of noob questions 😄 

1) I need to generate a query like:

```sql
INSERT INTO "tutorial"
  ("id", "name", "title", "shortTitle", "seoTitle"...)
VALUES
  ($1, $2, $3, $4...)
ON CONFLICT ("id") 
DO UPDATE SET 
  "name" = $2,
  "title" = $3,
  "shortTitle" =  $4,
  ...
```

How would I approach it with `slonik`?

I guess, it's possible with `sql.tuple` and `sql.assignmentList` or something like that?

2) In general, is it a good idea to use `INSERT + ON CONFLICT UPDATE` in e.g. `saveTutorial()` (JS function) instead of defining separate `insertTutorial()` and `updateTutorial()` functions? 

Note: I have an extremely limited experience with Postgres, so it's hard to guess.

**Comment by gajus** [comment]
Assuming that all parts of the query are dynamic, then:

```js
sql`
INSERT INTO tutorial
  ${sql.identifierList([])}
VALUES
  ${sql.tuple([])}
ON CONFLICT (id)
DO UPDATE SET
  ${sql.assignmentList([])}

`

```

If columns are known, then:

```js
sql`
INSERT INTO tutorial
(
  id,
  name
)
VALUES
  ${sql.tuple([tutorial.id, tutorial.name])}
ON CONFLICT (id)
DO UPDATE SET
  name = excluded.name

`

```

Alternatively, consider `upsert`:

https://github.com/gajus/slonik-utilities#slonik-utilities-usage-upsert
