### ISSUE TITLE
Query without transaction nesting?

### ISSUE THREAD

**Issue by lineldcosta** [gajus/slonik#84]
Hello guys,

Is there a way to do transaction without nesting?
I mean to say.

await connection.startTransaction();
await connection.query(sql``);
await connction.commitTransaction();

Please let me know if anything like this possible? which i used to do with mysql previously with other libs.

**Comment by gajus** [comment]
```js
await connection.query(sql`BEGIN`);
await connection.query(sql`SELECT 1`);
await connection.query(sql`COMMIT`);

```

However, don't do it.

https://github.com/gajus/slonik#protecting-against-unsafe-transaction-handling
