### ISSUE TITLE
How to use correctly in graphql resolvers (apollo-server)

### ISSUE THREAD

**Issue by underbluewaters** [gajus/slonik#85]
I'd like to use slonik with apollo-server and am unsure how to go about implementing resolvers. It seems that best practice (and a major motivation of slonik) is to create a new connection for each request.
In apollo-server, they encourage adding [dataSources](https://www.apollographql.com/docs/apollo-server/features/data-sources/) or other resources that should last the lifetime of a request on the [context](https://www.apollographql.com/docs/apollo-server/features/authentication/). These values are set on a callback function in the apollo constructor like so:

```javascript
const server = new ApolloServer({
 typeDefs,
 resolvers,
 context: ({ req }) => {
   const pool = createPool(process.env.PG_CONNECTION)
   return { db: new DataAPI(pool) };
 },
});
```

Setup this way, I could then write resolvers without worrying too much about the details of how data is accessed:

```javascript
const resolvers = {
  Project: {
    tags: async ({id}, _, {db}) => return db.Projects.getTags(),
    ...
  },
  ...
```

This doesn't really work with slonik unless I just use a pool and having my requests assigned to random connections. From the documentation it sounds like there might be negative consequences to this, but it's not clearly spelled out. Any advice? It feels like maybe I'm entirely off track structuring my code this way.

**Comment by gajus** [comment]
> It seems that best practice (and a major motivation of slonik) is to create a new connection for each request.

No. Where is this implied in the documentation?

Your setup description is exactly how you would use it.

**Comment by underbluewaters** [comment]
Thanks for the clarification. What gave me the idea that I was doing things wrong was the [section on unsafe connection handling](https://github.com/gajus/slonik#protecting-against-unsafe-connection-handling). I thought that passing around a pool might be an unsafe workaround given the ability to pass a connection to a Promise. It's very likely then that I will be using multiple connections if any of my resolvers use multiple *DataAPI* methods in this example.

**Comment by gajus** [comment]
If you are passing around pool, then you have no guarantees over using the same connection in your resolvers _unless_ you explicitly create a connection or transaction within that resolver. You should never pre-allocate a connection for a HTTP request. Keeping a connection is expensive and non-scalable.

**Comment by TriStarGod** [comment]
@gajus Follow up question on the graphql implementation. I was planning to call an instantiated pool as needed into the respective models rather than pass an instantiated pool via context.

It would be as follows

```
// models/index.js
export const db = createPool(...

// models/SomeModel.js
export const SomeModelRes = db.query(sql`....

// graphql/resolvers/SomeType.js
import { SomeModelRes } from '../../models/SomeModel'
...
export const resolvers = {
...
  someField: async (p, a, c, i) => {
...
    return SomeModelRes(a);
```

From my tests, it creates the pool once through the server process lifetime and then random connections are passed to the models as needed. Are there any problems with this implementation?
