### ISSUE TITLE
Deprecate sql.rawList in favour of sql.expressionList

### ISSUE THREAD

**Issue by gajus** [gajus/slonik#91]
`sql.rawList` misleading implies use of `sql.raw` as a requirement.

Same goes for `sql.valueList`, `sql.tupleList`, `sql.identifierList` and `sql.booleanExpression`.

All of them can be replaced with a generic `sql.expressionList` that works similar to `.join()`.

**Comment by gajus** [comment]
And add an option to specify glue expression.

**Comment by gajus** [comment]
This has been already done.

**Comment by rakibtg** [comment]
Is `expressionList` is still valid?

**Comment by gajus** [comment]
No. Just use `sql.join`.
