### ISSUE TITLE
Allow empty string in sql``

### ISSUE THREAD

**Issue by gajus** [gajus/slonik#93]
I have added a constraint that restrict use of empty ``sql` ` ``, https://github.com/gajus/slonik/commit/ffa017bb9ef15711d9759da71c319a572a05ecff#diff-da1685de4700740100be31e15a3fdc0bR106. I do not recall the original reason.

Allowing empty sql tag would be useful as a fallback value when constructing SQL, e.g.

```js
sql`
  SELECT 1
  ORDER BY ${true ? sql`1` : sql``}
`

```

This will throw. One can workaround this by using a comment, e.g.

```js
sql`
  SELECT 1
  ORDER BY ${true ? sql`1` : sql`--`}
`

```

See this issue thread for more context:

https://dev.to/gajus/dynamically-generating-sql-queries-using-node-js-2c1g/comments#/gajus/dynamically-generating-sql-queries-using-node-js-2c1g/comments/new/epd2

**Comment by nodefish** [comment]
Seems intuitive to use `sql.raw('')` for the empty fragment.

**Comment by nodefish** [comment]
What's wrong with:

```js
${sort ? sql`ORDER BY ${makeOrder(sort)}` : sql``} // throws
```
-> 
```js
${sort ? sql`ORDER BY ${makeOrder(sort)}` : sql.raw('')}
```

**Comment by ivan-kleshnin** [comment]
I guess you should explain what's wrong with 

```
sql``
```

and why it shouldn't work in your opinion?

**Comment by gajus** [comment]
@nodefish `sql.raw` will be removed. Don't use it.

**Comment by gajus** [comment]
`sql.raw` has been removed.

https://github.com/gajus/slonik/releases/tag/v20.0.0
